from enum import Enum

class AmfEventType(str, Enum):
    LOCATION_REPORT = "LOCATION_REPORT"
    PRESENCE_IN_AOI_REPORT = "PRESENCE_IN_AOI_REPORT"
    TIMEZONE_REPORT = "TIMEZONE_REPORT"
    ACCESS_TYPE_REPORT = "ACCESS_TYPE_REPORT"
    REGISTRATION_STATE_REPORT = "REGISTRATION_STATE_REPORT"
    CONNECTIVITY_STATE_REPORT = "CONNECTIVITY_STATE_REPORT"
    REACHABILITY_REPORT = "REACHABILITY_REPORT"
    SUBSCRIBED_DATA_REPORT = "SUBSCRIBED_DATA_REPORT"
    COMMIUNICATION_FAILURE_REPORT = "COMMIUNICATION_FAILURE_REPORT"
    UES_IN_AREA_REPORT = "UES_IN_AREA_REPORT"