# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.ipv6_addr import Ipv6Addr
import re
import util

from models.ipv6_addr import Ipv6Addr  # noqa: E501
import re  # noqa: E501

class AccNetChargingAddress(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, an_charg_ipv4_addr=None, an_charg_ipv6_addr=None):  # noqa: E501
        """AccNetChargingAddress - a model defined in OpenAPI

        :param an_charg_ipv4_addr: The an_charg_ipv4_addr of this AccNetChargingAddress.  # noqa: E501
        :type an_charg_ipv4_addr: str
        :param an_charg_ipv6_addr: The an_charg_ipv6_addr of this AccNetChargingAddress.  # noqa: E501
        :type an_charg_ipv6_addr: Ipv6Addr
        """
        self.openapi_types = {
            'an_charg_ipv4_addr': str,
            'an_charg_ipv6_addr': Ipv6Addr
        }

        self.attribute_map = {
            'an_charg_ipv4_addr': 'anChargIpv4Addr',
            'an_charg_ipv6_addr': 'anChargIpv6Addr'
        }

        self._an_charg_ipv4_addr = an_charg_ipv4_addr
        self._an_charg_ipv6_addr = an_charg_ipv6_addr

    @classmethod
    def from_dict(cls, dikt) -> 'AccNetChargingAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccNetChargingAddress of this AccNetChargingAddress.  # noqa: E501
        :rtype: AccNetChargingAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def an_charg_ipv4_addr(self):
        """Gets the an_charg_ipv4_addr of this AccNetChargingAddress.

        String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.   # noqa: E501

        :return: The an_charg_ipv4_addr of this AccNetChargingAddress.
        :rtype: str
        """
        return self._an_charg_ipv4_addr

    @an_charg_ipv4_addr.setter
    def an_charg_ipv4_addr(self, an_charg_ipv4_addr):
        """Sets the an_charg_ipv4_addr of this AccNetChargingAddress.

        String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.   # noqa: E501

        :param an_charg_ipv4_addr: The an_charg_ipv4_addr of this AccNetChargingAddress.
        :type an_charg_ipv4_addr: str
        """
        if an_charg_ipv4_addr is not None and not re.search(r'^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$', an_charg_ipv4_addr):  # noqa: E501
            raise ValueError("Invalid value for `an_charg_ipv4_addr`, must be a follow pattern or equal to `/^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$/`")  # noqa: E501

        self._an_charg_ipv4_addr = an_charg_ipv4_addr

    @property
    def an_charg_ipv6_addr(self):
        """Gets the an_charg_ipv6_addr of this AccNetChargingAddress.


        :return: The an_charg_ipv6_addr of this AccNetChargingAddress.
        :rtype: Ipv6Addr
        """
        return self._an_charg_ipv6_addr

    @an_charg_ipv6_addr.setter
    def an_charg_ipv6_addr(self, an_charg_ipv6_addr):
        """Sets the an_charg_ipv6_addr of this AccNetChargingAddress.


        :param an_charg_ipv6_addr: The an_charg_ipv6_addr of this AccNetChargingAddress.
        :type an_charg_ipv6_addr: Ipv6Addr
        """

        self._an_charg_ipv6_addr = an_charg_ipv6_addr
