# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.any_of_af_event_exposure_data_af_events_items import AnyOfAfEventExposureDataAfEventsItems  # noqa: F401,E501
import util


class AfEventExposureData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, af_events: List[AnyOfAfEventExposureDataAfEventsItems]=None, af_ids: List[str]=None, app_ids: List[str]=None):  # noqa: E501
        """AfEventExposureData - a model defined in Swagger

        :param af_events: The af_events of this AfEventExposureData.  # noqa: E501
        :type af_events: List[AnyOfAfEventExposureDataAfEventsItems]
        :param af_ids: The af_ids of this AfEventExposureData.  # noqa: E501
        :type af_ids: List[str]
        :param app_ids: The app_ids of this AfEventExposureData.  # noqa: E501
        :type app_ids: List[str]
        """
        self.openapi_types = {
            'af_events': List[AnyOfAfEventExposureDataAfEventsItems],
            'af_ids': List[str],
            'app_ids': List[str]
        }

        self.attribute_map = {
            'af_events': 'afEvents',
            'af_ids': 'afIds',
            'app_ids': 'appIds'
        }
        self._af_events = af_events
        self._af_ids = af_ids
        self._app_ids = app_ids

    @classmethod
    def from_dict(cls, dikt) -> 'AfEventExposureData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AfEventExposureData of this AfEventExposureData.  # noqa: E501
        :rtype: AfEventExposureData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def af_events(self) -> List[AnyOfAfEventExposureDataAfEventsItems]:
        """Gets the af_events of this AfEventExposureData.


        :return: The af_events of this AfEventExposureData.
        :rtype: List[AnyOfAfEventExposureDataAfEventsItems]
        """
        return self._af_events

    @af_events.setter
    def af_events(self, af_events: List[AnyOfAfEventExposureDataAfEventsItems]):
        """Sets the af_events of this AfEventExposureData.


        :param af_events: The af_events of this AfEventExposureData.
        :type af_events: List[AnyOfAfEventExposureDataAfEventsItems]
        """
        if af_events is None:
            raise ValueError("Invalid value for `af_events`, must not be `None`")  # noqa: E501

        self._af_events = af_events

    @property
    def af_ids(self) -> List[str]:
        """Gets the af_ids of this AfEventExposureData.


        :return: The af_ids of this AfEventExposureData.
        :rtype: List[str]
        """
        return self._af_ids

    @af_ids.setter
    def af_ids(self, af_ids: List[str]):
        """Sets the af_ids of this AfEventExposureData.


        :param af_ids: The af_ids of this AfEventExposureData.
        :type af_ids: List[str]
        """

        self._af_ids = af_ids

    @property
    def app_ids(self) -> List[str]:
        """Gets the app_ids of this AfEventExposureData.


        :return: The app_ids of this AfEventExposureData.
        :rtype: List[str]
        """
        return self._app_ids

    @app_ids.setter
    def app_ids(self, app_ids: List[str]):
        """Sets the app_ids of this AfEventExposureData.


        :param app_ids: The app_ids of this AfEventExposureData.
        :type app_ids: List[str]
        """

        self._app_ids = app_ids
