# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import re  # noqa: F401,E501
from models.any_of_amf_update_event_option_item_notif_flag import AnyOfAmfUpdateEventOptionItemNotifFlag  # noqa: F401,E501
import util


class AmfUpdateEventOptionItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, op: str=None, path: str=None, value: datetime=None, notif_flag: AnyOfAmfUpdateEventOptionItemNotifFlag=None):  # noqa: E501
        """AmfUpdateEventOptionItem - a model defined in Swagger

        :param op: The op of this AmfUpdateEventOptionItem.  # noqa: E501
        :type op: str
        :param path: The path of this AmfUpdateEventOptionItem.  # noqa: E501
        :type path: str
        :param value: The value of this AmfUpdateEventOptionItem.  # noqa: E501
        :type value: datetime
        :param notif_flag: The notif_flag of this AmfUpdateEventOptionItem.  # noqa: E501
        :type notif_flag: AnyOfAmfUpdateEventOptionItemNotifFlag
        """
        self.swagger_types = {
            'op': str,
            'path': str,
            'value': datetime,
            'notif_flag': AnyOfAmfUpdateEventOptionItemNotifFlag
        }

        self.attribute_map = {
            'op': 'op',
            'path': 'path',
            'value': 'value',
            'notif_flag': 'notifFlag'
        }
        self._op = op
        self._path = path
        self._value = value
        self._notif_flag = notif_flag

    @classmethod
    def from_dict(cls, dikt) -> 'AmfUpdateEventOptionItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmfUpdateEventOptionItem of this AmfUpdateEventOptionItem.  # noqa: E501
        :rtype: AmfUpdateEventOptionItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def op(self) -> str:
        """Gets the op of this AmfUpdateEventOptionItem.


        :return: The op of this AmfUpdateEventOptionItem.
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op: str):
        """Sets the op of this AmfUpdateEventOptionItem.


        :param op: The op of this AmfUpdateEventOptionItem.
        :type op: str
        """
        allowed_values = ["replace"]  # noqa: E501
        if op not in allowed_values:
            raise ValueError(
                "Invalid value for `op` ({0}), must be one of {1}"
                .format(op, allowed_values)
            )

        self._op = op

    @property
    def path(self) -> str:
        """Gets the path of this AmfUpdateEventOptionItem.


        :return: The path of this AmfUpdateEventOptionItem.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this AmfUpdateEventOptionItem.


        :param path: The path of this AmfUpdateEventOptionItem.
        :type path: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def value(self) -> datetime:
        """Gets the value of this AmfUpdateEventOptionItem.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The value of this AmfUpdateEventOptionItem.
        :rtype: datetime
        """
        return self._value

    @value.setter
    def value(self, value: datetime):
        """Sets the value of this AmfUpdateEventOptionItem.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param value: The value of this AmfUpdateEventOptionItem.
        :type value: datetime
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def notif_flag(self) -> AnyOfAmfUpdateEventOptionItemNotifFlag:
        """Gets the notif_flag of this AmfUpdateEventOptionItem.

        Possible values are: - ACTIVATE: The event notification is activated. - DEACTIVATE: The event notification is deactivated and shall be muted. The available    event(s) shall be stored. - RETRIEVAL: The event notification shall be sent to the NF service consumer(s),   after that, is muted again.    # noqa: E501

        :return: The notif_flag of this AmfUpdateEventOptionItem.
        :rtype: AnyOfAmfUpdateEventOptionItemNotifFlag
        """
        return self._notif_flag

    @notif_flag.setter
    def notif_flag(self, notif_flag: AnyOfAmfUpdateEventOptionItemNotifFlag):
        """Sets the notif_flag of this AmfUpdateEventOptionItem.

        Possible values are: - ACTIVATE: The event notification is activated. - DEACTIVATE: The event notification is deactivated and shall be muted. The available    event(s) shall be stored. - RETRIEVAL: The event notification shall be sent to the NF service consumer(s),   after that, is muted again.    # noqa: E501

        :param notif_flag: The notif_flag of this AmfUpdateEventOptionItem.
        :type notif_flag: AnyOfAmfUpdateEventOptionItemNotifFlag
        """

        self._notif_flag = notif_flag
