# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_event_report import AmfEventReport  # noqa: F401,E501
from models.amf_event_subscription import AmfEventSubscription  # noqa: F401,E501
import util


class AmfUpdatedEventSubscription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subscription: AmfEventSubscription=None, report_list: List[AmfEventReport]=None):  # noqa: E501
        """AmfUpdatedEventSubscription - a model defined in Swagger

        :param subscription: The subscription of this AmfUpdatedEventSubscription.  # noqa: E501
        :type subscription: AmfEventSubscription
        :param report_list: The report_list of this AmfUpdatedEventSubscription.  # noqa: E501
        :type report_list: List[AmfEventReport]
        """
        self.swagger_types = {
            'subscription': AmfEventSubscription,
            'report_list': List[AmfEventReport]
        }

        self.attribute_map = {
            'subscription': 'subscription',
            'report_list': 'reportList'
        }
        self._subscription = subscription
        self._report_list = report_list

    @classmethod
    def from_dict(cls, dikt) -> 'AmfUpdatedEventSubscription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmfUpdatedEventSubscription of this AmfUpdatedEventSubscription.  # noqa: E501
        :rtype: AmfUpdatedEventSubscription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription(self) -> AmfEventSubscription:
        """Gets the subscription of this AmfUpdatedEventSubscription.


        :return: The subscription of this AmfUpdatedEventSubscription.
        :rtype: AmfEventSubscription
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: AmfEventSubscription):
        """Sets the subscription of this AmfUpdatedEventSubscription.


        :param subscription: The subscription of this AmfUpdatedEventSubscription.
        :type subscription: AmfEventSubscription
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription

    @property
    def report_list(self) -> List[AmfEventReport]:
        """Gets the report_list of this AmfUpdatedEventSubscription.


        :return: The report_list of this AmfUpdatedEventSubscription.
        :rtype: List[AmfEventReport]
        """
        return self._report_list

    @report_list.setter
    def report_list(self, report_list: List[AmfEventReport]):
        """Sets the report_list of this AmfUpdatedEventSubscription.


        :param report_list: The report_list of this AmfUpdatedEventSubscription.
        :type report_list: List[AmfEventReport]
        """

        self._report_list = report_list
