# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_event_trigger import AmfEventTrigger  # noqa: F401,E501
from models.any_of_amf_event_mode_partitioning_criteria_items import AnyOfAmfEventModePartitioningCriteriaItems  # noqa: F401,E501
from models.any_of_amf_event_mode_notif_flag import AnyOfAmfEventModeNotifFlag  # noqa: F401,E501
import util


class AmfEventMode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, trigger: AmfEventTrigger=None, max_reports: int=None, expiry: datetime=None, rep_period: int=None, samp_ratio: int=None, partitioning_criteria: List[AnyOfAmfEventModePartitioningCriteriaItems]=None, notif_flag: AnyOfAmfEventModeNotifFlag=None):  # noqa: E501
        """AmfEventMode - a model defined in Swagger

        :param trigger: The trigger of this AmfEventMode.  # noqa: E501
        :type trigger: AmfEventTrigger
        :param max_reports: The max_reports of this AmfEventMode.  # noqa: E501
        :type max_reports: int
        :param expiry: The expiry of this AmfEventMode.  # noqa: E501
        :type expiry: datetime
        :param rep_period: The rep_period of this AmfEventMode.  # noqa: E501
        :type rep_period: int
        :param samp_ratio: The samp_ratio of this AmfEventMode.  # noqa: E501
        :type samp_ratio: int
        :param partitioning_criteria: The partitioning_criteria of this AmfEventMode.  # noqa: E501
        :type partitioning_criteria: List[AnyOfAmfEventModePartitioningCriteriaItems]
        :param notif_flag: The notif_flag of this AmfEventMode.  # noqa: E501
        :type notif_flag: AnyOfAmfEventModeNotifFlag
        """
        self.swagger_types = {
            'trigger': AmfEventTrigger,
            'max_reports': int,
            'expiry': datetime,
            'rep_period': int,
            'samp_ratio': int,
            'partitioning_criteria': List[AnyOfAmfEventModePartitioningCriteriaItems],
            'notif_flag': AnyOfAmfEventModeNotifFlag
        }

        self.attribute_map = {
            'trigger': 'trigger',
            'max_reports': 'maxReports',
            'expiry': 'expiry',
            'rep_period': 'repPeriod',
            'samp_ratio': 'sampRatio',
            'partitioning_criteria': 'partitioningCriteria',
            'notif_flag': 'notifFlag'
        }
        self._trigger = trigger
        self._max_reports = max_reports
        self._expiry = expiry
        self._rep_period = rep_period
        self._samp_ratio = samp_ratio
        self._partitioning_criteria = partitioning_criteria
        self._notif_flag = notif_flag

    @classmethod
    def from_dict(cls, dikt) -> 'AmfEventMode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmfEventMode of this AmfEventMode.  # noqa: E501
        :rtype: AmfEventMode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def trigger(self) -> AmfEventTrigger:
        """Gets the trigger of this AmfEventMode.


        :return: The trigger of this AmfEventMode.
        :rtype: AmfEventTrigger
        """
        return self._trigger

    @trigger.setter
    def trigger(self, trigger: AmfEventTrigger):
        """Sets the trigger of this AmfEventMode.


        :param trigger: The trigger of this AmfEventMode.
        :type trigger: AmfEventTrigger
        """
        if trigger is None:
            raise ValueError("Invalid value for `trigger`, must not be `None`")  # noqa: E501

        self._trigger = trigger

    @property
    def max_reports(self) -> int:
        """Gets the max_reports of this AmfEventMode.


        :return: The max_reports of this AmfEventMode.
        :rtype: int
        """
        return self._max_reports

    @max_reports.setter
    def max_reports(self, max_reports: int):
        """Sets the max_reports of this AmfEventMode.


        :param max_reports: The max_reports of this AmfEventMode.
        :type max_reports: int
        """

        self._max_reports = max_reports

    @property
    def expiry(self) -> datetime:
        """Gets the expiry of this AmfEventMode.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The expiry of this AmfEventMode.
        :rtype: datetime
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry: datetime):
        """Sets the expiry of this AmfEventMode.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param expiry: The expiry of this AmfEventMode.
        :type expiry: datetime
        """

        self._expiry = expiry

    @property
    def rep_period(self) -> int:
        """Gets the rep_period of this AmfEventMode.

        indicating a time in seconds.  # noqa: E501

        :return: The rep_period of this AmfEventMode.
        :rtype: int
        """
        return self._rep_period

    @rep_period.setter
    def rep_period(self, rep_period: int):
        """Sets the rep_period of this AmfEventMode.

        indicating a time in seconds.  # noqa: E501

        :param rep_period: The rep_period of this AmfEventMode.
        :type rep_period: int
        """

        self._rep_period = rep_period

    @property
    def samp_ratio(self) -> int:
        """Gets the samp_ratio of this AmfEventMode.

        Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.    # noqa: E501

        :return: The samp_ratio of this AmfEventMode.
        :rtype: int
        """
        return self._samp_ratio

    @samp_ratio.setter
    def samp_ratio(self, samp_ratio: int):
        """Sets the samp_ratio of this AmfEventMode.

        Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.    # noqa: E501

        :param samp_ratio: The samp_ratio of this AmfEventMode.
        :type samp_ratio: int
        """

        self._samp_ratio = samp_ratio

    @property
    def partitioning_criteria(self) -> List[AnyOfAmfEventModePartitioningCriteriaItems]:
        """Gets the partitioning_criteria of this AmfEventMode.


        :return: The partitioning_criteria of this AmfEventMode.
        :rtype: List[AnyOfAmfEventModePartitioningCriteriaItems]
        """
        return self._partitioning_criteria

    @partitioning_criteria.setter
    def partitioning_criteria(self, partitioning_criteria: List[AnyOfAmfEventModePartitioningCriteriaItems]):
        """Sets the partitioning_criteria of this AmfEventMode.


        :param partitioning_criteria: The partitioning_criteria of this AmfEventMode.
        :type partitioning_criteria: List[AnyOfAmfEventModePartitioningCriteriaItems]
        """

        self._partitioning_criteria = partitioning_criteria

    @property
    def notif_flag(self) -> AnyOfAmfEventModeNotifFlag:
        """Gets the notif_flag of this AmfEventMode.

        Possible values are: - ACTIVATE: The event notification is activated. - DEACTIVATE: The event notification is deactivated and shall be muted. The available    event(s) shall be stored. - RETRIEVAL: The event notification shall be sent to the NF service consumer(s),   after that, is muted again.    # noqa: E501

        :return: The notif_flag of this AmfEventMode.
        :rtype: AnyOfAmfEventModeNotifFlag
        """
        return self._notif_flag

    @notif_flag.setter
    def notif_flag(self, notif_flag: AnyOfAmfEventModeNotifFlag):
        """Sets the notif_flag of this AmfEventMode.

        Possible values are: - ACTIVATE: The event notification is activated. - DEACTIVATE: The event notification is deactivated and shall be muted. The available    event(s) shall be stored. - RETRIEVAL: The event notification shall be sent to the NF service consumer(s),   after that, is muted again.    # noqa: E501

        :param notif_flag: The notif_flag of this AmfEventMode.
        :type notif_flag: AnyOfAmfEventModeNotifFlag
        """

        self._notif_flag = notif_flag
