# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_event_global_ran_node_id_list import AmfEventGlobalRanNodeIdList  # noqa: F401,E501
from models.amf_event_ncgi_list import AmfEventNcgiList  # noqa: F401,E501
from models.amf_event_tracking_area_list import AmfEventTrackingAreaList  # noqa: F401,E501
import re  # noqa: F401,E501
import util


class AmfEventReportLocationNrLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tai: AmfEventTrackingAreaList=None, ncgi: AmfEventNcgiList=None, ignore_ncgi: bool=False, age_of_location_information: int=None, ue_location_timestamp: datetime=None, geographical_information: str=None, geodetic_information: str=None, global_gnb_id: AmfEventGlobalRanNodeIdList=None):  # noqa: E501
        """AmfEventReportLocationNrLocation - a model defined in Swagger

        :param tai: The tai of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type tai: AmfEventTrackingAreaList
        :param ncgi: The ncgi of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type ncgi: AmfEventNcgiList
        :param ignore_ncgi: The ignore_ncgi of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type ignore_ncgi: bool
        :param age_of_location_information: The age_of_location_information of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type age_of_location_information: int
        :param ue_location_timestamp: The ue_location_timestamp of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type ue_location_timestamp: datetime
        :param geographical_information: The geographical_information of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type geographical_information: str
        :param geodetic_information: The geodetic_information of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type geodetic_information: str
        :param global_gnb_id: The global_gnb_id of this AmfEventReportLocationNrLocation.  # noqa: E501
        :type global_gnb_id: AmfEventGlobalRanNodeIdList
        """
        self.swagger_types = {
            'tai': AmfEventTrackingAreaList,
            'ncgi': AmfEventNcgiList,
            'ignore_ncgi': bool,
            'age_of_location_information': int,
            'ue_location_timestamp': datetime,
            'geographical_information': str,
            'geodetic_information': str,
            'global_gnb_id': AmfEventGlobalRanNodeIdList
        }

        self.attribute_map = {
            'tai': 'tai',
            'ncgi': 'ncgi',
            'ignore_ncgi': 'ignoreNcgi',
            'age_of_location_information': 'ageOfLocationInformation',
            'ue_location_timestamp': 'ueLocationTimestamp',
            'geographical_information': 'geographicalInformation',
            'geodetic_information': 'geodeticInformation',
            'global_gnb_id': 'globalGnbId'
        }
        self._tai = tai
        self._ncgi = ncgi
        self._ignore_ncgi = ignore_ncgi
        self._age_of_location_information = age_of_location_information
        self._ue_location_timestamp = ue_location_timestamp
        self._geographical_information = geographical_information
        self._geodetic_information = geodetic_information
        self._global_gnb_id = global_gnb_id

    @classmethod
    def from_dict(cls, dikt) -> 'AmfEventReportLocationNrLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmfEventReport_location_nrLocation of this AmfEventReportLocationNrLocation.  # noqa: E501
        :rtype: AmfEventReportLocationNrLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tai(self) -> AmfEventTrackingAreaList:
        """Gets the tai of this AmfEventReportLocationNrLocation.


        :return: The tai of this AmfEventReportLocationNrLocation.
        :rtype: AmfEventTrackingAreaList
        """
        return self._tai

    @tai.setter
    def tai(self, tai: AmfEventTrackingAreaList):
        """Sets the tai of this AmfEventReportLocationNrLocation.


        :param tai: The tai of this AmfEventReportLocationNrLocation.
        :type tai: AmfEventTrackingAreaList
        """
        if tai is None:
            raise ValueError("Invalid value for `tai`, must not be `None`")  # noqa: E501

        self._tai = tai

    @property
    def ncgi(self) -> AmfEventNcgiList:
        """Gets the ncgi of this AmfEventReportLocationNrLocation.


        :return: The ncgi of this AmfEventReportLocationNrLocation.
        :rtype: AmfEventNcgiList
        """
        return self._ncgi

    @ncgi.setter
    def ncgi(self, ncgi: AmfEventNcgiList):
        """Sets the ncgi of this AmfEventReportLocationNrLocation.


        :param ncgi: The ncgi of this AmfEventReportLocationNrLocation.
        :type ncgi: AmfEventNcgiList
        """
        if ncgi is None:
            raise ValueError("Invalid value for `ncgi`, must not be `None`")  # noqa: E501

        self._ncgi = ncgi

    @property
    def ignore_ncgi(self) -> bool:
        """Gets the ignore_ncgi of this AmfEventReportLocationNrLocation.


        :return: The ignore_ncgi of this AmfEventReportLocationNrLocation.
        :rtype: bool
        """
        return self._ignore_ncgi

    @ignore_ncgi.setter
    def ignore_ncgi(self, ignore_ncgi: bool):
        """Sets the ignore_ncgi of this AmfEventReportLocationNrLocation.


        :param ignore_ncgi: The ignore_ncgi of this AmfEventReportLocationNrLocation.
        :type ignore_ncgi: bool
        """

        self._ignore_ncgi = ignore_ncgi

    @property
    def age_of_location_information(self) -> int:
        """Gets the age_of_location_information of this AmfEventReportLocationNrLocation.

        The value represents the elapsed time in minutes since the last network contact of the mobile station. Value \"0\" indicates that the location information was obtained after a successful paging procedure for Active Location Retrieval when the UE is in idle mode or after a successful  NG-RAN location reporting procedure with the eNB when the UE is in connected mode. Any other value than \"0\" indicates that the location information is the last known one. See 3GPP TS 29.002 clause 17.7.8.   # noqa: E501

        :return: The age_of_location_information of this AmfEventReportLocationNrLocation.
        :rtype: int
        """
        return self._age_of_location_information

    @age_of_location_information.setter
    def age_of_location_information(self, age_of_location_information: int):
        """Sets the age_of_location_information of this AmfEventReportLocationNrLocation.

        The value represents the elapsed time in minutes since the last network contact of the mobile station. Value \"0\" indicates that the location information was obtained after a successful paging procedure for Active Location Retrieval when the UE is in idle mode or after a successful  NG-RAN location reporting procedure with the eNB when the UE is in connected mode. Any other value than \"0\" indicates that the location information is the last known one. See 3GPP TS 29.002 clause 17.7.8.   # noqa: E501

        :param age_of_location_information: The age_of_location_information of this AmfEventReportLocationNrLocation.
        :type age_of_location_information: int
        """

        self._age_of_location_information = age_of_location_information

    @property
    def ue_location_timestamp(self) -> datetime:
        """Gets the ue_location_timestamp of this AmfEventReportLocationNrLocation.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The ue_location_timestamp of this AmfEventReportLocationNrLocation.
        :rtype: datetime
        """
        return self._ue_location_timestamp

    @ue_location_timestamp.setter
    def ue_location_timestamp(self, ue_location_timestamp: datetime):
        """Sets the ue_location_timestamp of this AmfEventReportLocationNrLocation.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param ue_location_timestamp: The ue_location_timestamp of this AmfEventReportLocationNrLocation.
        :type ue_location_timestamp: datetime
        """

        self._ue_location_timestamp = ue_location_timestamp

    @property
    def geographical_information(self) -> str:
        """Gets the geographical_information of this AmfEventReportLocationNrLocation.

        Refer to geographical Information. See 3GPP TS 23.032 clause 7.3.2. Only the description of an ellipsoid point with uncertainty circle is allowed to be used.   # noqa: E501

        :return: The geographical_information of this AmfEventReportLocationNrLocation.
        :rtype: str
        """
        return self._geographical_information

    @geographical_information.setter
    def geographical_information(self, geographical_information: str):
        """Sets the geographical_information of this AmfEventReportLocationNrLocation.

        Refer to geographical Information. See 3GPP TS 23.032 clause 7.3.2. Only the description of an ellipsoid point with uncertainty circle is allowed to be used.   # noqa: E501

        :param geographical_information: The geographical_information of this AmfEventReportLocationNrLocation.
        :type geographical_information: str
        """

        self._geographical_information = geographical_information

    @property
    def geodetic_information(self) -> str:
        """Gets the geodetic_information of this AmfEventReportLocationNrLocation.

        Refers to Calling Geodetic Location. See ITU-T Recommendation Q.763 (1999) [24] clause 3.88.2. Only the description of an ellipsoid point with uncertainty circle is allowed to be used.   # noqa: E501

        :return: The geodetic_information of this AmfEventReportLocationNrLocation.
        :rtype: str
        """
        return self._geodetic_information

    @geodetic_information.setter
    def geodetic_information(self, geodetic_information: str):
        """Sets the geodetic_information of this AmfEventReportLocationNrLocation.

        Refers to Calling Geodetic Location. See ITU-T Recommendation Q.763 (1999) [24] clause 3.88.2. Only the description of an ellipsoid point with uncertainty circle is allowed to be used.   # noqa: E501

        :param geodetic_information: The geodetic_information of this AmfEventReportLocationNrLocation.
        :type geodetic_information: str
        """

        self._geodetic_information = geodetic_information

    @property
    def global_gnb_id(self) -> AmfEventGlobalRanNodeIdList:
        """Gets the global_gnb_id of this AmfEventReportLocationNrLocation.


        :return: The global_gnb_id of this AmfEventReportLocationNrLocation.
        :rtype: AmfEventGlobalRanNodeIdList
        """
        return self._global_gnb_id

    @global_gnb_id.setter
    def global_gnb_id(self, global_gnb_id: AmfEventGlobalRanNodeIdList):
        """Sets the global_gnb_id of this AmfEventReportLocationNrLocation.


        :param global_gnb_id: The global_gnb_id of this AmfEventReportLocationNrLocation.
        :type global_gnb_id: AmfEventGlobalRanNodeIdList
        """

        self._global_gnb_id = global_gnb_id
