# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_event_area_s_nssai import AmfEventAreaSNssai  # noqa: F401,E501
from models.amf_event_presence_info_list import AmfEventPresenceInfoList  # noqa: F401,E501
from models.ladn_info import LadnInfo  # noqa: F401,E501
import util


class AmfEventArea(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, presence_info: AmfEventPresenceInfoList=None, ladn_info: LadnInfo=None, s_nssai: AmfEventAreaSNssai=None, nsi_id: str=None):  # noqa: E501
        """AmfEventArea - a model defined in Swagger

        :param presence_info: The presence_info of this AmfEventArea.  # noqa: E501
        :type presence_info: AmfEventPresenceInfoList
        :param ladn_info: The ladn_info of this AmfEventArea.  # noqa: E501
        :type ladn_info: LadnInfo
        :param s_nssai: The s_nssai of this AmfEventArea.  # noqa: E501
        :type s_nssai: AmfEventAreaSNssai
        :param nsi_id: The nsi_id of this AmfEventArea.  # noqa: E501
        :type nsi_id: str
        """
        self.swagger_types = {
            'presence_info': AmfEventPresenceInfoList,
            'ladn_info': LadnInfo,
            's_nssai': AmfEventAreaSNssai,
            'nsi_id': str
        }

        self.attribute_map = {
            'presence_info': 'presenceInfo',
            'ladn_info': 'ladnInfo',
            's_nssai': 'sNssai',
            'nsi_id': 'nsiId'
        }
        self._presence_info = presence_info
        self._ladn_info = ladn_info
        self._s_nssai = s_nssai
        self._nsi_id = nsi_id

    @classmethod
    def from_dict(cls, dikt) -> 'AmfEventArea':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmfEventArea of this AmfEventArea.  # noqa: E501
        :rtype: AmfEventArea
        """
        return util.deserialize_model(dikt, cls)

    @property
    def presence_info(self) -> AmfEventPresenceInfoList:
        """Gets the presence_info of this AmfEventArea.


        :return: The presence_info of this AmfEventArea.
        :rtype: AmfEventPresenceInfoList
        """
        return self._presence_info

    @presence_info.setter
    def presence_info(self, presence_info: AmfEventPresenceInfoList):
        """Sets the presence_info of this AmfEventArea.


        :param presence_info: The presence_info of this AmfEventArea.
        :type presence_info: AmfEventPresenceInfoList
        """

        self._presence_info = presence_info

    @property
    def ladn_info(self) -> LadnInfo:
        """Gets the ladn_info of this AmfEventArea.


        :return: The ladn_info of this AmfEventArea.
        :rtype: LadnInfo
        """
        return self._ladn_info

    @ladn_info.setter
    def ladn_info(self, ladn_info: LadnInfo):
        """Sets the ladn_info of this AmfEventArea.


        :param ladn_info: The ladn_info of this AmfEventArea.
        :type ladn_info: LadnInfo
        """

        self._ladn_info = ladn_info

    @property
    def s_nssai(self) -> AmfEventAreaSNssai:
        """Gets the s_nssai of this AmfEventArea.


        :return: The s_nssai of this AmfEventArea.
        :rtype: AmfEventAreaSNssai
        """
        return self._s_nssai

    @s_nssai.setter
    def s_nssai(self, s_nssai: AmfEventAreaSNssai):
        """Sets the s_nssai of this AmfEventArea.


        :param s_nssai: The s_nssai of this AmfEventArea.
        :type s_nssai: AmfEventAreaSNssai
        """

        self._s_nssai = s_nssai

    @property
    def nsi_id(self) -> str:
        """Gets the nsi_id of this AmfEventArea.

        Contains the Identifier of the selected Network Slice instance  # noqa: E501

        :return: The nsi_id of this AmfEventArea.
        :rtype: str
        """
        return self._nsi_id

    @nsi_id.setter
    def nsi_id(self, nsi_id: str):
        """Sets the nsi_id of this AmfEventArea.

        Contains the Identifier of the selected Network Slice instance  # noqa: E501

        :param nsi_id: The nsi_id of this AmfEventArea.
        :type nsi_id: str
        """

        self._nsi_id = nsi_id
