# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class AmfEventReportLocationN3gaLocationTnapId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ss_id: str=None, bss_id: str=None, civic_address: bytearray=None):  # noqa: E501
        """AmfEventReportLocationN3gaLocationTnapId - a model defined in Swagger

        :param ss_id: The ss_id of this AmfEventReportLocationN3gaLocationTnapId.  # noqa: E501
        :type ss_id: str
        :param bss_id: The bss_id of this AmfEventReportLocationN3gaLocationTnapId.  # noqa: E501
        :type bss_id: str
        :param civic_address: The civic_address of this AmfEventReportLocationN3gaLocationTnapId.  # noqa: E501
        :type civic_address: bytearray
        """
        self.swagger_types = {
            'ss_id': str,
            'bss_id': str,
            'civic_address': bytearray
        }

        self.attribute_map = {
            'ss_id': 'ssId',
            'bss_id': 'bssId',
            'civic_address': 'civicAddress'
        }
        self._ss_id = ss_id
        self._bss_id = bss_id
        self._civic_address = civic_address

    @classmethod
    def from_dict(cls, dikt) -> 'AmfEventReportLocationN3gaLocationTnapId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmfEventReport_location_n3gaLocation_tnapId of this AmfEventReportLocationN3gaLocationTnapId.  # noqa: E501
        :rtype: AmfEventReportLocationN3gaLocationTnapId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ss_id(self) -> str:
        """Gets the ss_id of this AmfEventReportLocationN3gaLocationTnapId.

        This IE shall be present if the UE is accessing the 5GC via a trusted WLAN access network.When present, it shall contain the SSID of the access point to which the UE is attached, that is received over NGAP,  see IEEE Std 802.11-2012.    # noqa: E501

        :return: The ss_id of this AmfEventReportLocationN3gaLocationTnapId.
        :rtype: str
        """
        return self._ss_id

    @ss_id.setter
    def ss_id(self, ss_id: str):
        """Sets the ss_id of this AmfEventReportLocationN3gaLocationTnapId.

        This IE shall be present if the UE is accessing the 5GC via a trusted WLAN access network.When present, it shall contain the SSID of the access point to which the UE is attached, that is received over NGAP,  see IEEE Std 802.11-2012.    # noqa: E501

        :param ss_id: The ss_id of this AmfEventReportLocationN3gaLocationTnapId.
        :type ss_id: str
        """

        self._ss_id = ss_id

    @property
    def bss_id(self) -> str:
        """Gets the bss_id of this AmfEventReportLocationN3gaLocationTnapId.

        When present, it shall contain the BSSID of the access point to which the UE is attached, that is received over NGAP, see IEEE Std 802.11-2012.    # noqa: E501

        :return: The bss_id of this AmfEventReportLocationN3gaLocationTnapId.
        :rtype: str
        """
        return self._bss_id

    @bss_id.setter
    def bss_id(self, bss_id: str):
        """Sets the bss_id of this AmfEventReportLocationN3gaLocationTnapId.

        When present, it shall contain the BSSID of the access point to which the UE is attached, that is received over NGAP, see IEEE Std 802.11-2012.    # noqa: E501

        :param bss_id: The bss_id of this AmfEventReportLocationN3gaLocationTnapId.
        :type bss_id: str
        """

        self._bss_id = bss_id

    @property
    def civic_address(self) -> bytearray:
        """Gets the civic_address of this AmfEventReportLocationN3gaLocationTnapId.

        string with format 'bytes' as defined in OpenAPI  # noqa: E501

        :return: The civic_address of this AmfEventReportLocationN3gaLocationTnapId.
        :rtype: bytearray
        """
        return self._civic_address

    @civic_address.setter
    def civic_address(self, civic_address: bytearray):
        """Sets the civic_address of this AmfEventReportLocationN3gaLocationTnapId.

        string with format 'bytes' as defined in OpenAPI  # noqa: E501

        :param civic_address: The civic_address of this AmfEventReportLocationN3gaLocationTnapId.
        :type civic_address: bytearray
        """

        self._civic_address = civic_address
