# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class BridgeManagementContainer(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bridge_man_cont=None):  # noqa: E501
        """BridgeManagementContainer - a model defined in OpenAPI

        :param bridge_man_cont: The bridge_man_cont of this BridgeManagementContainer.  # noqa: E501
        :type bridge_man_cont: str
        """
        self.openapi_types = {
            'bridge_man_cont': str
        }

        self.attribute_map = {
            'bridge_man_cont': 'bridgeManCont'
        }

        self._bridge_man_cont = bridge_man_cont

    @classmethod
    def from_dict(cls, dikt) -> 'BridgeManagementContainer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BridgeManagementContainer of this BridgeManagementContainer.  # noqa: E501
        :rtype: BridgeManagementContainer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bridge_man_cont(self):
        """Gets the bridge_man_cont of this BridgeManagementContainer.

        string with format 'bytes' as defined in OpenAPI  # noqa: E501

        :return: The bridge_man_cont of this BridgeManagementContainer.
        :rtype: str
        """
        return self._bridge_man_cont

    @bridge_man_cont.setter
    def bridge_man_cont(self, bridge_man_cont):
        """Sets the bridge_man_cont of this BridgeManagementContainer.

        string with format 'bytes' as defined in OpenAPI  # noqa: E501

        :param bridge_man_cont: The bridge_man_cont of this BridgeManagementContainer.
        :type bridge_man_cont: str
        """
        if bridge_man_cont is None:
            raise ValueError("Invalid value for `bridge_man_cont`, must not be `None`")  # noqa: E501

        self._bridge_man_cont = bridge_man_cont
