# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.cm_state import CmState  # noqa: F401,E501
import util


class CmInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cm_state: CmState=None, access_type: str=None):  # noqa: E501
        """CmInfo - a model defined in Swagger

        :param cm_state: The cm_state of this CmInfo.  # noqa: E501
        :type cm_state: CmState
        :param access_type: The access_type of this CmInfo.  # noqa: E501
        :type access_type: str
        """
        self.swagger_types = {
            'cm_state': CmState,
            'access_type': str
        }

        self.attribute_map = {
            'cm_state': 'cmState',
            'access_type': 'accessType'
        }
        self._cm_state = cm_state
        self._access_type = access_type

    @classmethod
    def from_dict(cls, dikt) -> 'CmInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CmInfo of this CmInfo.  # noqa: E501
        :rtype: CmInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cm_state(self) -> CmState:
        """Gets the cm_state of this CmInfo.


        :return: The cm_state of this CmInfo.
        :rtype: CmState
        """
        return self._cm_state

    @cm_state.setter
    def cm_state(self, cm_state: CmState):
        """Sets the cm_state of this CmInfo.


        :param cm_state: The cm_state of this CmInfo.
        :type cm_state: CmState
        """
        if cm_state is None:
            raise ValueError("Invalid value for `cm_state`, must not be `None`")  # noqa: E501

        self._cm_state = cm_state

    @property
    def access_type(self) -> str:
        """Gets the access_type of this CmInfo.

        Indicates whether the access is  via 3GPP or via non-3GPP.  # noqa: E501

        :return: The access_type of this CmInfo.
        :rtype: str
        """
        return self._access_type

    @access_type.setter
    def access_type(self, access_type: str):
        """Sets the access_type of this CmInfo.

        Indicates whether the access is  via 3GPP or via non-3GPP.  # noqa: E501

        :param access_type: The access_type of this CmInfo.
        :type access_type: str
        """
        allowed_values = ["3GPP_ACCESS", "NON_3GPP_ACCESS"]  # noqa: E501
        if access_type not in allowed_values:
            raise ValueError(
                "Invalid value for `access_type` ({0}), must be one of {1}"
                .format(access_type, allowed_values)
            )

        self._access_type = access_type
