# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.any_of_dnn_smf_info_item_dnn import AnyOfDnnSmfInfoItemDnn  # noqa: F401,E501
import util


class DnnSmfInfoItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dnn: AnyOfDnnSmfInfoItemDnn=None):  # noqa: E501
        """DnnSmfInfoItem - a model defined in Swagger

        :param dnn: The dnn of this DnnSmfInfoItem.  # noqa: E501
        :type dnn: AnyOfDnnSmfInfoItemDnn
        """
        self.swagger_types = {
            'dnn': AnyOfDnnSmfInfoItemDnn
        }

        self.attribute_map = {
            'dnn': 'dnn'
        }
        self._dnn = dnn

    @classmethod
    def from_dict(cls, dikt) -> 'DnnSmfInfoItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DnnSmfInfoItem of this DnnSmfInfoItem.  # noqa: E501
        :rtype: DnnSmfInfoItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dnn(self) -> AnyOfDnnSmfInfoItemDnn:
        """Gets the dnn of this DnnSmfInfoItem.


        :return: The dnn of this DnnSmfInfoItem.
        :rtype: AnyOfDnnSmfInfoItemDnn
        """
        return self._dnn

    @dnn.setter
    def dnn(self, dnn: AnyOfDnnSmfInfoItemDnn):
        """Sets the dnn of this DnnSmfInfoItem.


        :param dnn: The dnn of this DnnSmfInfoItem.
        :type dnn: AnyOfDnnSmfInfoItemDnn
        """
        if dnn is None:
            raise ValueError("Invalid value for `dnn`, must not be `None`")  # noqa: E501

        self._dnn = dnn
