# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.eas_server_address import EasServerAddress  # noqa: F401,E501
import util


class EasIpReplacementInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source: EasServerAddress=None, target: EasServerAddress=None):  # noqa: E501
        """EasIpReplacementInfo - a model defined in Swagger

        :param source: The source of this EasIpReplacementInfo.  # noqa: E501
        :type source: EasServerAddress
        :param target: The target of this EasIpReplacementInfo.  # noqa: E501
        :type target: EasServerAddress
        """
        self.swagger_types = {
            'source': EasServerAddress,
            'target': EasServerAddress
        }

        self.attribute_map = {
            'source': 'source',
            'target': 'target'
        }
        self._source = source
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'EasIpReplacementInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EasIpReplacementInfo of this EasIpReplacementInfo.  # noqa: E501
        :rtype: EasIpReplacementInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source(self) -> EasServerAddress:
        """Gets the source of this EasIpReplacementInfo.


        :return: The source of this EasIpReplacementInfo.
        :rtype: EasServerAddress
        """
        return self._source

    @source.setter
    def source(self, source: EasServerAddress):
        """Sets the source of this EasIpReplacementInfo.


        :param source: The source of this EasIpReplacementInfo.
        :type source: EasServerAddress
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def target(self) -> EasServerAddress:
        """Gets the target of this EasIpReplacementInfo.


        :return: The target of this EasIpReplacementInfo.
        :rtype: EasServerAddress
        """
        return self._target

    @target.setter
    def target(self, target: EasServerAddress):
        """Sets the target of this EasIpReplacementInfo.


        :param target: The target of this EasIpReplacementInfo.
        :type target: EasServerAddress
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501

        self._target = target
