# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.af_event_subscription import AfEventSubscription
from models.qos_monitoring_information_rm import QosMonitoringInformationRm
from models.requested_qos_monitoring_parameter import RequestedQosMonitoringParameter
from models.required_access_info import RequiredAccessInfo
from models.usage_threshold_rm import UsageThresholdRm
import util

from models.af_event_subscription import AfEventSubscription  # noqa: E501
from models.qos_monitoring_information_rm import QosMonitoringInformationRm  # noqa: E501
from models.requested_qos_monitoring_parameter import RequestedQosMonitoringParameter  # noqa: E501
from models.required_access_info import RequiredAccessInfo  # noqa: E501
from models.usage_threshold_rm import UsageThresholdRm  # noqa: E501

class EventsSubscReqDataRm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, events=None, notif_uri=None, req_qos_mon_params=None, qos_mon=None, req_anis=None, usg_thres=None, notif_corre_id=None, direct_notif_ind=None):  # noqa: E501
        """EventsSubscReqDataRm - a model defined in OpenAPI

        :param events: The events of this EventsSubscReqDataRm.  # noqa: E501
        :type events: List[AfEventSubscription]
        :param notif_uri: The notif_uri of this EventsSubscReqDataRm.  # noqa: E501
        :type notif_uri: str
        :param req_qos_mon_params: The req_qos_mon_params of this EventsSubscReqDataRm.  # noqa: E501
        :type req_qos_mon_params: List[RequestedQosMonitoringParameter]
        :param qos_mon: The qos_mon of this EventsSubscReqDataRm.  # noqa: E501
        :type qos_mon: QosMonitoringInformationRm
        :param req_anis: The req_anis of this EventsSubscReqDataRm.  # noqa: E501
        :type req_anis: List[RequiredAccessInfo]
        :param usg_thres: The usg_thres of this EventsSubscReqDataRm.  # noqa: E501
        :type usg_thres: UsageThresholdRm
        :param notif_corre_id: The notif_corre_id of this EventsSubscReqDataRm.  # noqa: E501
        :type notif_corre_id: str
        :param direct_notif_ind: The direct_notif_ind of this EventsSubscReqDataRm.  # noqa: E501
        :type direct_notif_ind: bool
        """
        self.openapi_types = {
            'events': List[AfEventSubscription],
            'notif_uri': str,
            'req_qos_mon_params': List[RequestedQosMonitoringParameter],
            'qos_mon': QosMonitoringInformationRm,
            'req_anis': List[RequiredAccessInfo],
            'usg_thres': UsageThresholdRm,
            'notif_corre_id': str,
            'direct_notif_ind': bool
        }

        self.attribute_map = {
            'events': 'events',
            'notif_uri': 'notifUri',
            'req_qos_mon_params': 'reqQosMonParams',
            'qos_mon': 'qosMon',
            'req_anis': 'reqAnis',
            'usg_thres': 'usgThres',
            'notif_corre_id': 'notifCorreId',
            'direct_notif_ind': 'directNotifInd'
        }

        self._events = events
        self._notif_uri = notif_uri
        self._req_qos_mon_params = req_qos_mon_params
        self._qos_mon = qos_mon
        self._req_anis = req_anis
        self._usg_thres = usg_thres
        self._notif_corre_id = notif_corre_id
        self._direct_notif_ind = direct_notif_ind

    @classmethod
    def from_dict(cls, dikt) -> 'EventsSubscReqDataRm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventsSubscReqDataRm of this EventsSubscReqDataRm.  # noqa: E501
        :rtype: EventsSubscReqDataRm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def events(self):
        """Gets the events of this EventsSubscReqDataRm.


        :return: The events of this EventsSubscReqDataRm.
        :rtype: List[AfEventSubscription]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this EventsSubscReqDataRm.


        :param events: The events of this EventsSubscReqDataRm.
        :type events: List[AfEventSubscription]
        """
        if events is None:
            raise ValueError("Invalid value for `events`, must not be `None`")  # noqa: E501

        self._events = events

    @property
    def notif_uri(self):
        """Gets the notif_uri of this EventsSubscReqDataRm.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :return: The notif_uri of this EventsSubscReqDataRm.
        :rtype: str
        """
        return self._notif_uri

    @notif_uri.setter
    def notif_uri(self, notif_uri):
        """Sets the notif_uri of this EventsSubscReqDataRm.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :param notif_uri: The notif_uri of this EventsSubscReqDataRm.
        :type notif_uri: str
        """

        self._notif_uri = notif_uri

    @property
    def req_qos_mon_params(self):
        """Gets the req_qos_mon_params of this EventsSubscReqDataRm.


        :return: The req_qos_mon_params of this EventsSubscReqDataRm.
        :rtype: List[RequestedQosMonitoringParameter]
        """
        return self._req_qos_mon_params

    @req_qos_mon_params.setter
    def req_qos_mon_params(self, req_qos_mon_params):
        """Sets the req_qos_mon_params of this EventsSubscReqDataRm.


        :param req_qos_mon_params: The req_qos_mon_params of this EventsSubscReqDataRm.
        :type req_qos_mon_params: List[RequestedQosMonitoringParameter]
        """
        if req_qos_mon_params is not None and len(req_qos_mon_params) < 1:
            raise ValueError("Invalid value for `req_qos_mon_params`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._req_qos_mon_params = req_qos_mon_params

    @property
    def qos_mon(self):
        """Gets the qos_mon of this EventsSubscReqDataRm.


        :return: The qos_mon of this EventsSubscReqDataRm.
        :rtype: QosMonitoringInformationRm
        """
        return self._qos_mon

    @qos_mon.setter
    def qos_mon(self, qos_mon):
        """Sets the qos_mon of this EventsSubscReqDataRm.


        :param qos_mon: The qos_mon of this EventsSubscReqDataRm.
        :type qos_mon: QosMonitoringInformationRm
        """

        self._qos_mon = qos_mon

    @property
    def req_anis(self):
        """Gets the req_anis of this EventsSubscReqDataRm.


        :return: The req_anis of this EventsSubscReqDataRm.
        :rtype: List[RequiredAccessInfo]
        """
        return self._req_anis

    @req_anis.setter
    def req_anis(self, req_anis):
        """Sets the req_anis of this EventsSubscReqDataRm.


        :param req_anis: The req_anis of this EventsSubscReqDataRm.
        :type req_anis: List[RequiredAccessInfo]
        """
        if req_anis is not None and len(req_anis) < 1:
            raise ValueError("Invalid value for `req_anis`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._req_anis = req_anis

    @property
    def usg_thres(self):
        """Gets the usg_thres of this EventsSubscReqDataRm.


        :return: The usg_thres of this EventsSubscReqDataRm.
        :rtype: UsageThresholdRm
        """
        return self._usg_thres

    @usg_thres.setter
    def usg_thres(self, usg_thres):
        """Sets the usg_thres of this EventsSubscReqDataRm.


        :param usg_thres: The usg_thres of this EventsSubscReqDataRm.
        :type usg_thres: UsageThresholdRm
        """

        self._usg_thres = usg_thres

    @property
    def notif_corre_id(self):
        """Gets the notif_corre_id of this EventsSubscReqDataRm.


        :return: The notif_corre_id of this EventsSubscReqDataRm.
        :rtype: str
        """
        return self._notif_corre_id

    @notif_corre_id.setter
    def notif_corre_id(self, notif_corre_id):
        """Sets the notif_corre_id of this EventsSubscReqDataRm.


        :param notif_corre_id: The notif_corre_id of this EventsSubscReqDataRm.
        :type notif_corre_id: str
        """

        self._notif_corre_id = notif_corre_id

    @property
    def direct_notif_ind(self):
        """Gets the direct_notif_ind of this EventsSubscReqDataRm.


        :return: The direct_notif_ind of this EventsSubscReqDataRm.
        :rtype: bool
        """
        return self._direct_notif_ind

    @direct_notif_ind.setter
    def direct_notif_ind(self, direct_notif_ind):
        """Sets the direct_notif_ind of this EventsSubscReqDataRm.


        :param direct_notif_ind: The direct_notif_ind of this EventsSubscReqDataRm.
        :type direct_notif_ind: bool
        """

        self._direct_notif_ind = direct_notif_ind
