# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_event_ecgi_list import AmfEventEcgiList  # noqa: F401,E501
from models.amf_event_ncgi_list import AmfEventNcgiList  # noqa: F401,E501
from models.amf_event_report_location_n3ga_location import AmfEventReportLocationN3gaLocation  # noqa: F401,E501
from models.amf_event_tracking_area_list import AmfEventTrackingAreaList  # noqa: F401,E501
import util


class MmTransactionLocationReportItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, tai: AmfEventTrackingAreaList=None, ncgi: AmfEventNcgiList=None, ecgi: AmfEventEcgiList=None, n3ga_location: AmfEventReportLocationN3gaLocation=None, timestamp: datetime=None, transactions: int=None):  # noqa: E501
        """MmTransactionLocationReportItem - a model defined in Swagger

        :param tai: The tai of this MmTransactionLocationReportItem.  # noqa: E501
        :type tai: AmfEventTrackingAreaList
        :param ncgi: The ncgi of this MmTransactionLocationReportItem.  # noqa: E501
        :type ncgi: AmfEventNcgiList
        :param ecgi: The ecgi of this MmTransactionLocationReportItem.  # noqa: E501
        :type ecgi: AmfEventEcgiList
        :param n3ga_location: The n3ga_location of this MmTransactionLocationReportItem.  # noqa: E501
        :type n3ga_location: AmfEventReportLocationN3gaLocation
        :param timestamp: The timestamp of this MmTransactionLocationReportItem.  # noqa: E501
        :type timestamp: datetime
        :param transactions: The transactions of this MmTransactionLocationReportItem.  # noqa: E501
        :type transactions: int
        """
        self.swagger_types = {
            'tai': AmfEventTrackingAreaList,
            'ncgi': AmfEventNcgiList,
            'ecgi': AmfEventEcgiList,
            'n3ga_location': AmfEventReportLocationN3gaLocation,
            'timestamp': datetime,
            'transactions': int
        }

        self.attribute_map = {
            'tai': 'tai',
            'ncgi': 'ncgi',
            'ecgi': 'ecgi',
            'n3ga_location': 'n3gaLocation',
            'timestamp': 'timestamp',
            'transactions': 'transactions'
        }
        self._tai = tai
        self._ncgi = ncgi
        self._ecgi = ecgi
        self._n3ga_location = n3ga_location
        self._timestamp = timestamp
        self._transactions = transactions

    @classmethod
    def from_dict(cls, dikt) -> 'MmTransactionLocationReportItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MmTransactionLocationReportItem of this MmTransactionLocationReportItem.  # noqa: E501
        :rtype: MmTransactionLocationReportItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tai(self) -> AmfEventTrackingAreaList:
        """Gets the tai of this MmTransactionLocationReportItem.


        :return: The tai of this MmTransactionLocationReportItem.
        :rtype: AmfEventTrackingAreaList
        """
        return self._tai

    @tai.setter
    def tai(self, tai: AmfEventTrackingAreaList):
        """Sets the tai of this MmTransactionLocationReportItem.


        :param tai: The tai of this MmTransactionLocationReportItem.
        :type tai: AmfEventTrackingAreaList
        """

        self._tai = tai

    @property
    def ncgi(self) -> AmfEventNcgiList:
        """Gets the ncgi of this MmTransactionLocationReportItem.


        :return: The ncgi of this MmTransactionLocationReportItem.
        :rtype: AmfEventNcgiList
        """
        return self._ncgi

    @ncgi.setter
    def ncgi(self, ncgi: AmfEventNcgiList):
        """Sets the ncgi of this MmTransactionLocationReportItem.


        :param ncgi: The ncgi of this MmTransactionLocationReportItem.
        :type ncgi: AmfEventNcgiList
        """

        self._ncgi = ncgi

    @property
    def ecgi(self) -> AmfEventEcgiList:
        """Gets the ecgi of this MmTransactionLocationReportItem.


        :return: The ecgi of this MmTransactionLocationReportItem.
        :rtype: AmfEventEcgiList
        """
        return self._ecgi

    @ecgi.setter
    def ecgi(self, ecgi: AmfEventEcgiList):
        """Sets the ecgi of this MmTransactionLocationReportItem.


        :param ecgi: The ecgi of this MmTransactionLocationReportItem.
        :type ecgi: AmfEventEcgiList
        """

        self._ecgi = ecgi

    @property
    def n3ga_location(self) -> AmfEventReportLocationN3gaLocation:
        """Gets the n3ga_location of this MmTransactionLocationReportItem.


        :return: The n3ga_location of this MmTransactionLocationReportItem.
        :rtype: AmfEventReportLocationN3gaLocation
        """
        return self._n3ga_location

    @n3ga_location.setter
    def n3ga_location(self, n3ga_location: AmfEventReportLocationN3gaLocation):
        """Sets the n3ga_location of this MmTransactionLocationReportItem.


        :param n3ga_location: The n3ga_location of this MmTransactionLocationReportItem.
        :type n3ga_location: AmfEventReportLocationN3gaLocation
        """

        self._n3ga_location = n3ga_location

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this MmTransactionLocationReportItem.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The timestamp of this MmTransactionLocationReportItem.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this MmTransactionLocationReportItem.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param timestamp: The timestamp of this MmTransactionLocationReportItem.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def transactions(self) -> int:
        """Gets the transactions of this MmTransactionLocationReportItem.


        :return: The transactions of this MmTransactionLocationReportItem.
        :rtype: int
        """
        return self._transactions

    @transactions.setter
    def transactions(self, transactions: int):
        """Sets the transactions of this MmTransactionLocationReportItem.


        :param transactions: The transactions of this MmTransactionLocationReportItem.
        :type transactions: int
        """
        if transactions is None:
            raise ValueError("Invalid value for `transactions`, must not be `None`")  # noqa: E501

        self._transactions = transactions
