# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.nef_event_filter_loc_area_plmn_id import NefEventFilterLocAreaPlmnId  # noqa: F401,E501
import re  # noqa: F401,E501
import util


class NefEventFilterLocAreaTais(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plmn_id: NefEventFilterLocAreaPlmnId=None, tac: str=None, nid: str=None):  # noqa: E501
        """NefEventFilterLocAreaTais - a model defined in Swagger

        :param plmn_id: The plmn_id of this NefEventFilterLocAreaTais.  # noqa: E501
        :type plmn_id: NefEventFilterLocAreaPlmnId
        :param tac: The tac of this NefEventFilterLocAreaTais.  # noqa: E501
        :type tac: str
        :param nid: The nid of this NefEventFilterLocAreaTais.  # noqa: E501
        :type nid: str
        """
        self.swagger_types = {
            'plmn_id': NefEventFilterLocAreaPlmnId,
            'tac': str,
            'nid': str
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            'tac': 'tac',
            'nid': 'nid'
        }
        self._plmn_id = plmn_id
        self._tac = tac
        self._nid = nid

    @classmethod
    def from_dict(cls, dikt) -> 'NefEventFilterLocAreaTais':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NefEventFilter_locArea_tais of this NefEventFilterLocAreaTais.  # noqa: E501
        :rtype: NefEventFilterLocAreaTais
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self) -> NefEventFilterLocAreaPlmnId:
        """Gets the plmn_id of this NefEventFilterLocAreaTais.


        :return: The plmn_id of this NefEventFilterLocAreaTais.
        :rtype: NefEventFilterLocAreaPlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id: NefEventFilterLocAreaPlmnId):
        """Sets the plmn_id of this NefEventFilterLocAreaTais.


        :param plmn_id: The plmn_id of this NefEventFilterLocAreaTais.
        :type plmn_id: NefEventFilterLocAreaPlmnId
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id

    @property
    def tac(self) -> str:
        """Gets the tac of this NefEventFilterLocAreaTais.


        :return: The tac of this NefEventFilterLocAreaTais.
        :rtype: str
        """
        return self._tac

    @tac.setter
    def tac(self, tac: str):
        """Sets the tac of this NefEventFilterLocAreaTais.


        :param tac: The tac of this NefEventFilterLocAreaTais.
        :type tac: str
        """
        if tac is None:
            raise ValueError("Invalid value for `tac`, must not be `None`")  # noqa: E501

        self._tac = tac

    @property
    def nid(self) -> str:
        """Gets the nid of this NefEventFilterLocAreaTais.


        :return: The nid of this NefEventFilterLocAreaTais.
        :rtype: str
        """
        return self._nid

    @nid.setter
    def nid(self, nid: str):
        """Sets the nid of this NefEventFilterLocAreaTais.


        :param nid: The nid of this NefEventFilterLocAreaTais.
        :type nid: str
        """

        self._nid = nid
