# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.nef_event_filter_loc_area_gnb_id import NefEventFilterLocAreaGNbId  # noqa: F401,E501
from models.nef_event_filter_loc_area_plmn_id import NefEventFilterLocAreaPlmnId  # noqa: F401,E501
import re  # noqa: F401,E501
import util


class NefEventFilterLocAreaGRanNodeIds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plmn_id: NefEventFilterLocAreaPlmnId=None, n3_iwf_id: str=None, g_nb_id: NefEventFilterLocAreaGNbId=None, nge_nb_id: str=None, wagf_id: str=None, tngf_id: str=None, nid: str=None, e_nb_id: str=None):  # noqa: E501
        """NefEventFilterLocAreaGRanNodeIds - a model defined in Swagger

        :param plmn_id: The plmn_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type plmn_id: NefEventFilterLocAreaPlmnId
        :param n3_iwf_id: The n3_iwf_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type n3_iwf_id: str
        :param g_nb_id: The g_nb_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type g_nb_id: NefEventFilterLocAreaGNbId
        :param nge_nb_id: The nge_nb_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type nge_nb_id: str
        :param wagf_id: The wagf_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type wagf_id: str
        :param tngf_id: The tngf_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type tngf_id: str
        :param nid: The nid of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type nid: str
        :param e_nb_id: The e_nb_id of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :type e_nb_id: str
        """
        self.swagger_types = {
            'plmn_id': NefEventFilterLocAreaPlmnId,
            'n3_iwf_id': str,
            'g_nb_id': NefEventFilterLocAreaGNbId,
            'nge_nb_id': str,
            'wagf_id': str,
            'tngf_id': str,
            'nid': str,
            'e_nb_id': str
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            'n3_iwf_id': 'n3IwfId',
            'g_nb_id': 'gNbId',
            'nge_nb_id': 'ngeNbId',
            'wagf_id': 'wagfId',
            'tngf_id': 'tngfId',
            'nid': 'nid',
            'e_nb_id': 'eNbId'
        }
        self._plmn_id = plmn_id
        self._n3_iwf_id = n3_iwf_id
        self._g_nb_id = g_nb_id
        self._nge_nb_id = nge_nb_id
        self._wagf_id = wagf_id
        self._tngf_id = tngf_id
        self._nid = nid
        self._e_nb_id = e_nb_id

    @classmethod
    def from_dict(cls, dikt) -> 'NefEventFilterLocAreaGRanNodeIds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NefEventFilter_locArea_gRanNodeIds of this NefEventFilterLocAreaGRanNodeIds.  # noqa: E501
        :rtype: NefEventFilterLocAreaGRanNodeIds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self) -> NefEventFilterLocAreaPlmnId:
        """Gets the plmn_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The plmn_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: NefEventFilterLocAreaPlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id: NefEventFilterLocAreaPlmnId):
        """Sets the plmn_id of this NefEventFilterLocAreaGRanNodeIds.


        :param plmn_id: The plmn_id of this NefEventFilterLocAreaGRanNodeIds.
        :type plmn_id: NefEventFilterLocAreaPlmnId
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id

    @property
    def n3_iwf_id(self) -> str:
        """Gets the n3_iwf_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The n3_iwf_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: str
        """
        return self._n3_iwf_id

    @n3_iwf_id.setter
    def n3_iwf_id(self, n3_iwf_id: str):
        """Sets the n3_iwf_id of this NefEventFilterLocAreaGRanNodeIds.


        :param n3_iwf_id: The n3_iwf_id of this NefEventFilterLocAreaGRanNodeIds.
        :type n3_iwf_id: str
        """

        self._n3_iwf_id = n3_iwf_id

    @property
    def g_nb_id(self) -> NefEventFilterLocAreaGNbId:
        """Gets the g_nb_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The g_nb_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: NefEventFilterLocAreaGNbId
        """
        return self._g_nb_id

    @g_nb_id.setter
    def g_nb_id(self, g_nb_id: NefEventFilterLocAreaGNbId):
        """Sets the g_nb_id of this NefEventFilterLocAreaGRanNodeIds.


        :param g_nb_id: The g_nb_id of this NefEventFilterLocAreaGRanNodeIds.
        :type g_nb_id: NefEventFilterLocAreaGNbId
        """

        self._g_nb_id = g_nb_id

    @property
    def nge_nb_id(self) -> str:
        """Gets the nge_nb_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The nge_nb_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: str
        """
        return self._nge_nb_id

    @nge_nb_id.setter
    def nge_nb_id(self, nge_nb_id: str):
        """Sets the nge_nb_id of this NefEventFilterLocAreaGRanNodeIds.


        :param nge_nb_id: The nge_nb_id of this NefEventFilterLocAreaGRanNodeIds.
        :type nge_nb_id: str
        """

        self._nge_nb_id = nge_nb_id

    @property
    def wagf_id(self) -> str:
        """Gets the wagf_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The wagf_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: str
        """
        return self._wagf_id

    @wagf_id.setter
    def wagf_id(self, wagf_id: str):
        """Sets the wagf_id of this NefEventFilterLocAreaGRanNodeIds.


        :param wagf_id: The wagf_id of this NefEventFilterLocAreaGRanNodeIds.
        :type wagf_id: str
        """

        self._wagf_id = wagf_id

    @property
    def tngf_id(self) -> str:
        """Gets the tngf_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The tngf_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: str
        """
        return self._tngf_id

    @tngf_id.setter
    def tngf_id(self, tngf_id: str):
        """Sets the tngf_id of this NefEventFilterLocAreaGRanNodeIds.


        :param tngf_id: The tngf_id of this NefEventFilterLocAreaGRanNodeIds.
        :type tngf_id: str
        """

        self._tngf_id = tngf_id

    @property
    def nid(self) -> str:
        """Gets the nid of this NefEventFilterLocAreaGRanNodeIds.


        :return: The nid of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: str
        """
        return self._nid

    @nid.setter
    def nid(self, nid: str):
        """Sets the nid of this NefEventFilterLocAreaGRanNodeIds.


        :param nid: The nid of this NefEventFilterLocAreaGRanNodeIds.
        :type nid: str
        """

        self._nid = nid

    @property
    def e_nb_id(self) -> str:
        """Gets the e_nb_id of this NefEventFilterLocAreaGRanNodeIds.


        :return: The e_nb_id of this NefEventFilterLocAreaGRanNodeIds.
        :rtype: str
        """
        return self._e_nb_id

    @e_nb_id.setter
    def e_nb_id(self, e_nb_id: str):
        """Sets the e_nb_id of this NefEventFilterLocAreaGRanNodeIds.


        :param e_nb_id: The e_nb_id of this NefEventFilterLocAreaGRanNodeIds.
        :type e_nb_id: str
        """

        self._e_nb_id = e_nb_id
