# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.any_of_nef_cond_event_ids_items import AnyOfNefCondEventIdsItems  # noqa: F401,E501
import util


class NefCond(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event_ids: List[AnyOfNefCondEventIdsItems]=None):  # noqa: E501
        """NefCond - a model defined in Swagger

        :param event_ids: The event_ids of this NefCond.  # noqa: E501
        :type event_ids: List[AnyOfNefCondEventIdsItems]
        """
        self.swagger_types = {
            'event_ids': List[AnyOfNefCondEventIdsItems]
        }

        self.attribute_map = {
            'event_ids': 'eventIds'
        }
        self._event_ids = event_ids

    @classmethod
    def from_dict(cls, dikt) -> 'NefCond':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NefCond of this NefCond.  # noqa: E501
        :rtype: NefCond
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_ids(self) -> List[AnyOfNefCondEventIdsItems]:
        """Gets the event_ids of this NefCond.


        :return: The event_ids of this NefCond.
        :rtype: List[AnyOfNefCondEventIdsItems]
        """
        return self._event_ids

    @event_ids.setter
    def event_ids(self, event_ids: List[AnyOfNefCondEventIdsItems]):
        """Sets the event_ids of this NefCond.


        :param event_ids: The event_ids of this NefCond.
        :type event_ids: List[AnyOfNefCondEventIdsItems]
        """

        self._event_ids = event_ids
