# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.condition_event_type import ConditionEventType  # noqa: F401,E501
from models.notification_data_profile_changes import NotificationDataProfileChanges  # noqa: F401,E501
from models.notification_event_type import NotificationEventType  # noqa: F401,E501
from models.all_of_notification_data_nf_profile import AllOfNotificationDataNfProfile  # noqa: F401,E501
import util


class NotificationData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event: NotificationEventType=None, nf_instance_uri: str=None, nf_profile: AllOfNotificationDataNfProfile=None, profile_changes: List[NotificationDataProfileChanges]=None, condition_event: ConditionEventType=None):  # noqa: E501
        """NotificationData - a model defined in Swagger

        :param event: The event of this NotificationData.  # noqa: E501
        :type event: NotificationEventType
        :param nf_instance_uri: The nf_instance_uri of this NotificationData.  # noqa: E501
        :type nf_instance_uri: str
        :param nf_profile: The nf_profile of this NotificationData.  # noqa: E501
        :type nf_profile: AllOfNotificationDataNfProfile
        :param profile_changes: The profile_changes of this NotificationData.  # noqa: E501
        :type profile_changes: List[NotificationDataProfileChanges]
        :param condition_event: The condition_event of this NotificationData.  # noqa: E501
        :type condition_event: ConditionEventType
        """
        self.swagger_types = {
            'event': NotificationEventType,
            'nf_instance_uri': str,
            'nf_profile': AllOfNotificationDataNfProfile,
            'profile_changes': List[NotificationDataProfileChanges],
            'condition_event': ConditionEventType
        }

        self.attribute_map = {
            'event': 'event',
            'nf_instance_uri': 'nfInstanceUri',
            'nf_profile': 'nfProfile',
            'profile_changes': 'profileChanges',
            'condition_event': 'conditionEvent'
        }
        self._event = event
        self._nf_instance_uri = nf_instance_uri
        self._nf_profile = nf_profile
        self._profile_changes = profile_changes
        self._condition_event = condition_event

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationData of this NotificationData.  # noqa: E501
        :rtype: NotificationData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event(self) -> NotificationEventType:
        """Gets the event of this NotificationData.


        :return: The event of this NotificationData.
        :rtype: NotificationEventType
        """
        return self._event

    @event.setter
    def event(self, event: NotificationEventType):
        """Sets the event of this NotificationData.


        :param event: The event of this NotificationData.
        :type event: NotificationEventType
        """
        if event is None:
            raise ValueError("Invalid value for `event`, must not be `None`")  # noqa: E501

        self._event = event

    @property
    def nf_instance_uri(self) -> str:
        """Gets the nf_instance_uri of this NotificationData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :return: The nf_instance_uri of this NotificationData.
        :rtype: str
        """
        return self._nf_instance_uri

    @nf_instance_uri.setter
    def nf_instance_uri(self, nf_instance_uri: str):
        """Sets the nf_instance_uri of this NotificationData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :param nf_instance_uri: The nf_instance_uri of this NotificationData.
        :type nf_instance_uri: str
        """
        if nf_instance_uri is None:
            raise ValueError("Invalid value for `nf_instance_uri`, must not be `None`")  # noqa: E501

        self._nf_instance_uri = nf_instance_uri

    @property
    def nf_profile(self) -> AllOfNotificationDataNfProfile:
        """Gets the nf_profile of this NotificationData.


        :return: The nf_profile of this NotificationData.
        :rtype: AllOfNotificationDataNfProfile
        """
        return self._nf_profile

    @nf_profile.setter
    def nf_profile(self, nf_profile: AllOfNotificationDataNfProfile):
        """Sets the nf_profile of this NotificationData.


        :param nf_profile: The nf_profile of this NotificationData.
        :type nf_profile: AllOfNotificationDataNfProfile
        """

        self._nf_profile = nf_profile

    @property
    def profile_changes(self) -> List[NotificationDataProfileChanges]:
        """Gets the profile_changes of this NotificationData.


        :return: The profile_changes of this NotificationData.
        :rtype: List[NotificationDataProfileChanges]
        """
        return self._profile_changes

    @profile_changes.setter
    def profile_changes(self, profile_changes: List[NotificationDataProfileChanges]):
        """Sets the profile_changes of this NotificationData.


        :param profile_changes: The profile_changes of this NotificationData.
        :type profile_changes: List[NotificationDataProfileChanges]
        """

        self._profile_changes = profile_changes

    @property
    def condition_event(self) -> ConditionEventType:
        """Gets the condition_event of this NotificationData.


        :return: The condition_event of this NotificationData.
        :rtype: ConditionEventType
        """
        return self._condition_event

    @condition_event.setter
    def condition_event(self, condition_event: ConditionEventType):
        """Sets the condition_event of this NotificationData.


        :param condition_event: The condition_event of this NotificationData.
        :type condition_event: ConditionEventType
        """

        self._condition_event = condition_event
