# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_info import AmfInfo  # noqa: F401,E501
from models.ausf_info import AusfInfo  # noqa: F401,E501
from models.bsf_info import BsfInfo  # noqa: F401,E501
from models.chf_info import ChfInfo  # noqa: F401,E501
from models.gmlc_info import GmlcInfo  # noqa: F401,E501
from models.hss_info import HssInfo  # noqa: F401,E501
from models.lmf_info import LmfInfo  # noqa: F401,E501
from models.nef_info import NefInfo  # noqa: F401,E501
from models.nf_info import NfInfo  # noqa: F401,E501
from models.nwdaf_info import NwdafInfo  # noqa: F401,E501
from models.pcf_info import PcfInfo  # noqa: F401,E501
from models.pcscf_info import PcscfInfo  # noqa: F401,E501
from models.scp_info import ScpInfo  # noqa: F401,E501
from models.smf_info import SmfInfo  # noqa: F401,E501
from models.udm_info import UdmInfo  # noqa: F401,E501
from models.udr_info import UdrInfo  # noqa: F401,E501
from models.udsf_info import UdsfInfo  # noqa: F401,E501
from models.upf_info import UpfInfo  # noqa: F401,E501
import util


class NrfInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, served_udr_info: Dict[str, UdrInfo]=None, served_udr_info_list: Dict[str, Dict[str, UdrInfo]]=None, served_udm_info: Dict[str, UdmInfo]=None, served_udm_info_list: Dict[str, Dict[str, UdmInfo]]=None, served_ausf_info: Dict[str, AusfInfo]=None, served_ausf_info_list: Dict[str, Dict[str, AusfInfo]]=None, served_amf_info: Dict[str, AmfInfo]=None, served_amf_info_list: Dict[str, Dict[str, AmfInfo]]=None, served_smf_info: Dict[str, SmfInfo]=None, served_smf_info_list: Dict[str, Dict[str, SmfInfo]]=None, served_upf_info: Dict[str, UpfInfo]=None, served_upf_info_list: Dict[str, Dict[str, UpfInfo]]=None, served_pcf_info: Dict[str, PcfInfo]=None, served_pcf_info_list: Dict[str, Dict[str, PcfInfo]]=None, served_bsf_info: Dict[str, BsfInfo]=None, served_bsf_info_list: Dict[str, Dict[str, BsfInfo]]=None, served_chf_info: Dict[str, ChfInfo]=None, served_chf_info_list: Dict[str, Dict[str, ChfInfo]]=None, served_nef_info: Dict[str, NefInfo]=None, served_nwdaf_info: Dict[str, NwdafInfo]=None, served_pcscf_info_list: Dict[str, Dict[str, PcscfInfo]]=None, served_gmlc_info: Dict[str, GmlcInfo]=None, served_lmf_info: Dict[str, LmfInfo]=None, served_nf_info: Dict[str, NfInfo]=None, served_hss_info_list: Dict[str, Dict[str, HssInfo]]=None, served_udsf_info: Dict[str, UdsfInfo]=None, served_udsf_info_list: Dict[str, Dict[str, UdsfInfo]]=None, served_scp_info_list: Dict[str, ScpInfo]=None):  # noqa: E501
        """NrfInfo - a model defined in Swagger

        :param served_udr_info: The served_udr_info of this NrfInfo.  # noqa: E501
        :type served_udr_info: Dict[str, UdrInfo]
        :param served_udr_info_list: The served_udr_info_list of this NrfInfo.  # noqa: E501
        :type served_udr_info_list: Dict[str, Dict[str, UdrInfo]]
        :param served_udm_info: The served_udm_info of this NrfInfo.  # noqa: E501
        :type served_udm_info: Dict[str, UdmInfo]
        :param served_udm_info_list: The served_udm_info_list of this NrfInfo.  # noqa: E501
        :type served_udm_info_list: Dict[str, Dict[str, UdmInfo]]
        :param served_ausf_info: The served_ausf_info of this NrfInfo.  # noqa: E501
        :type served_ausf_info: Dict[str, AusfInfo]
        :param served_ausf_info_list: The served_ausf_info_list of this NrfInfo.  # noqa: E501
        :type served_ausf_info_list: Dict[str, Dict[str, AusfInfo]]
        :param served_amf_info: The served_amf_info of this NrfInfo.  # noqa: E501
        :type served_amf_info: Dict[str, AmfInfo]
        :param served_amf_info_list: The served_amf_info_list of this NrfInfo.  # noqa: E501
        :type served_amf_info_list: Dict[str, Dict[str, AmfInfo]]
        :param served_smf_info: The served_smf_info of this NrfInfo.  # noqa: E501
        :type served_smf_info: Dict[str, SmfInfo]
        :param served_smf_info_list: The served_smf_info_list of this NrfInfo.  # noqa: E501
        :type served_smf_info_list: Dict[str, Dict[str, SmfInfo]]
        :param served_upf_info: The served_upf_info of this NrfInfo.  # noqa: E501
        :type served_upf_info: Dict[str, UpfInfo]
        :param served_upf_info_list: The served_upf_info_list of this NrfInfo.  # noqa: E501
        :type served_upf_info_list: Dict[str, Dict[str, UpfInfo]]
        :param served_pcf_info: The served_pcf_info of this NrfInfo.  # noqa: E501
        :type served_pcf_info: Dict[str, PcfInfo]
        :param served_pcf_info_list: The served_pcf_info_list of this NrfInfo.  # noqa: E501
        :type served_pcf_info_list: Dict[str, Dict[str, PcfInfo]]
        :param served_bsf_info: The served_bsf_info of this NrfInfo.  # noqa: E501
        :type served_bsf_info: Dict[str, BsfInfo]
        :param served_bsf_info_list: The served_bsf_info_list of this NrfInfo.  # noqa: E501
        :type served_bsf_info_list: Dict[str, Dict[str, BsfInfo]]
        :param served_chf_info: The served_chf_info of this NrfInfo.  # noqa: E501
        :type served_chf_info: Dict[str, ChfInfo]
        :param served_chf_info_list: The served_chf_info_list of this NrfInfo.  # noqa: E501
        :type served_chf_info_list: Dict[str, Dict[str, ChfInfo]]
        :param served_nef_info: The served_nef_info of this NrfInfo.  # noqa: E501
        :type served_nef_info: Dict[str, NefInfo]
        :param served_nwdaf_info: The served_nwdaf_info of this NrfInfo.  # noqa: E501
        :type served_nwdaf_info: Dict[str, NwdafInfo]
        :param served_pcscf_info_list: The served_pcscf_info_list of this NrfInfo.  # noqa: E501
        :type served_pcscf_info_list: Dict[str, Dict[str, PcscfInfo]]
        :param served_gmlc_info: The served_gmlc_info of this NrfInfo.  # noqa: E501
        :type served_gmlc_info: Dict[str, GmlcInfo]
        :param served_lmf_info: The served_lmf_info of this NrfInfo.  # noqa: E501
        :type served_lmf_info: Dict[str, LmfInfo]
        :param served_nf_info: The served_nf_info of this NrfInfo.  # noqa: E501
        :type served_nf_info: Dict[str, NfInfo]
        :param served_hss_info_list: The served_hss_info_list of this NrfInfo.  # noqa: E501
        :type served_hss_info_list: Dict[str, Dict[str, HssInfo]]
        :param served_udsf_info: The served_udsf_info of this NrfInfo.  # noqa: E501
        :type served_udsf_info: Dict[str, UdsfInfo]
        :param served_udsf_info_list: The served_udsf_info_list of this NrfInfo.  # noqa: E501
        :type served_udsf_info_list: Dict[str, Dict[str, UdsfInfo]]
        :param served_scp_info_list: The served_scp_info_list of this NrfInfo.  # noqa: E501
        :type served_scp_info_list: Dict[str, ScpInfo]
        """
        self.openapi_types = {
            'served_udr_info': Dict[str, UdrInfo],
            'served_udr_info_list': Dict[str, Dict[str, UdrInfo]],
            'served_udm_info': Dict[str, UdmInfo],
            'served_udm_info_list': Dict[str, Dict[str, UdmInfo]],
            'served_ausf_info': Dict[str, AusfInfo],
            'served_ausf_info_list': Dict[str, Dict[str, AusfInfo]],
            'served_amf_info': Dict[str, AmfInfo],
            'served_amf_info_list': Dict[str, Dict[str, AmfInfo]],
            'served_smf_info': Dict[str, SmfInfo],
            'served_smf_info_list': Dict[str, Dict[str, SmfInfo]],
            'served_upf_info': Dict[str, UpfInfo],
            'served_upf_info_list': Dict[str, Dict[str, UpfInfo]],
            'served_pcf_info': Dict[str, PcfInfo],
            'served_pcf_info_list': Dict[str, Dict[str, PcfInfo]],
            'served_bsf_info': Dict[str, BsfInfo],
            'served_bsf_info_list': Dict[str, Dict[str, BsfInfo]],
            'served_chf_info': Dict[str, ChfInfo],
            'served_chf_info_list': Dict[str, Dict[str, ChfInfo]],
            'served_nef_info': Dict[str, NefInfo],
            'served_nwdaf_info': Dict[str, NwdafInfo],
            'served_pcscf_info_list': Dict[str, Dict[str, PcscfInfo]],
            'served_gmlc_info': Dict[str, GmlcInfo],
            'served_lmf_info': Dict[str, LmfInfo],
            'served_nf_info': Dict[str, NfInfo],
            'served_hss_info_list': Dict[str, Dict[str, HssInfo]],
            'served_udsf_info': Dict[str, UdsfInfo],
            'served_udsf_info_list': Dict[str, Dict[str, UdsfInfo]],
            'served_scp_info_list': Dict[str, ScpInfo]
        }

        self.attribute_map = {
            'served_udr_info': 'servedUdrInfo',
            'served_udr_info_list': 'servedUdrInfoList',
            'served_udm_info': 'servedUdmInfo',
            'served_udm_info_list': 'servedUdmInfoList',
            'served_ausf_info': 'servedAusfInfo',
            'served_ausf_info_list': 'servedAusfInfoList',
            'served_amf_info': 'servedAmfInfo',
            'served_amf_info_list': 'servedAmfInfoList',
            'served_smf_info': 'servedSmfInfo',
            'served_smf_info_list': 'servedSmfInfoList',
            'served_upf_info': 'servedUpfInfo',
            'served_upf_info_list': 'servedUpfInfoList',
            'served_pcf_info': 'servedPcfInfo',
            'served_pcf_info_list': 'servedPcfInfoList',
            'served_bsf_info': 'servedBsfInfo',
            'served_bsf_info_list': 'servedBsfInfoList',
            'served_chf_info': 'servedChfInfo',
            'served_chf_info_list': 'servedChfInfoList',
            'served_nef_info': 'servedNefInfo',
            'served_nwdaf_info': 'servedNwdafInfo',
            'served_pcscf_info_list': 'servedPcscfInfoList',
            'served_gmlc_info': 'servedGmlcInfo',
            'served_lmf_info': 'servedLmfInfo',
            'served_nf_info': 'servedNfInfo',
            'served_hss_info_list': 'servedHssInfoList',
            'served_udsf_info': 'servedUdsfInfo',
            'served_udsf_info_list': 'servedUdsfInfoList',
            'served_scp_info_list': 'servedScpInfoList'
        }
        self._served_udr_info = served_udr_info
        self._served_udr_info_list = served_udr_info_list
        self._served_udm_info = served_udm_info
        self._served_udm_info_list = served_udm_info_list
        self._served_ausf_info = served_ausf_info
        self._served_ausf_info_list = served_ausf_info_list
        self._served_amf_info = served_amf_info
        self._served_amf_info_list = served_amf_info_list
        self._served_smf_info = served_smf_info
        self._served_smf_info_list = served_smf_info_list
        self._served_upf_info = served_upf_info
        self._served_upf_info_list = served_upf_info_list
        self._served_pcf_info = served_pcf_info
        self._served_pcf_info_list = served_pcf_info_list
        self._served_bsf_info = served_bsf_info
        self._served_bsf_info_list = served_bsf_info_list
        self._served_chf_info = served_chf_info
        self._served_chf_info_list = served_chf_info_list
        self._served_nef_info = served_nef_info
        self._served_nwdaf_info = served_nwdaf_info
        self._served_pcscf_info_list = served_pcscf_info_list
        self._served_gmlc_info = served_gmlc_info
        self._served_lmf_info = served_lmf_info
        self._served_nf_info = served_nf_info
        self._served_hss_info_list = served_hss_info_list
        self._served_udsf_info = served_udsf_info
        self._served_udsf_info_list = served_udsf_info_list
        self._served_scp_info_list = served_scp_info_list

    @classmethod
    def from_dict(cls, dikt) -> 'NrfInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NrfInfo of this NrfInfo.  # noqa: E501
        :rtype: NrfInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def served_udr_info(self) -> Dict[str, UdrInfo]:
        """Gets the served_udr_info of this NrfInfo.


        :return: The served_udr_info of this NrfInfo.
        :rtype: Dict[str, UdrInfo]
        """
        return self._served_udr_info

    @served_udr_info.setter
    def served_udr_info(self, served_udr_info: Dict[str, UdrInfo]):
        """Sets the served_udr_info of this NrfInfo.


        :param served_udr_info: The served_udr_info of this NrfInfo.
        :type served_udr_info: Dict[str, UdrInfo]
        """

        self._served_udr_info = served_udr_info

    @property
    def served_udr_info_list(self) -> Dict[str, Dict[str, UdrInfo]]:
        """Gets the served_udr_info_list of this NrfInfo.


        :return: The served_udr_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, UdrInfo]]
        """
        return self._served_udr_info_list

    @served_udr_info_list.setter
    def served_udr_info_list(self, served_udr_info_list: Dict[str, Dict[str, UdrInfo]]):
        """Sets the served_udr_info_list of this NrfInfo.


        :param served_udr_info_list: The served_udr_info_list of this NrfInfo.
        :type served_udr_info_list: Dict[str, Dict[str, UdrInfo]]
        """

        self._served_udr_info_list = served_udr_info_list

    @property
    def served_udm_info(self) -> Dict[str, UdmInfo]:
        """Gets the served_udm_info of this NrfInfo.


        :return: The served_udm_info of this NrfInfo.
        :rtype: Dict[str, UdmInfo]
        """
        return self._served_udm_info

    @served_udm_info.setter
    def served_udm_info(self, served_udm_info: Dict[str, UdmInfo]):
        """Sets the served_udm_info of this NrfInfo.


        :param served_udm_info: The served_udm_info of this NrfInfo.
        :type served_udm_info: Dict[str, UdmInfo]
        """

        self._served_udm_info = served_udm_info

    @property
    def served_udm_info_list(self) -> Dict[str, Dict[str, UdmInfo]]:
        """Gets the served_udm_info_list of this NrfInfo.


        :return: The served_udm_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, UdmInfo]]
        """
        return self._served_udm_info_list

    @served_udm_info_list.setter
    def served_udm_info_list(self, served_udm_info_list: Dict[str, Dict[str, UdmInfo]]):
        """Sets the served_udm_info_list of this NrfInfo.


        :param served_udm_info_list: The served_udm_info_list of this NrfInfo.
        :type served_udm_info_list: Dict[str, Dict[str, UdmInfo]]
        """

        self._served_udm_info_list = served_udm_info_list

    @property
    def served_ausf_info(self) -> Dict[str, AusfInfo]:
        """Gets the served_ausf_info of this NrfInfo.


        :return: The served_ausf_info of this NrfInfo.
        :rtype: Dict[str, AusfInfo]
        """
        return self._served_ausf_info

    @served_ausf_info.setter
    def served_ausf_info(self, served_ausf_info: Dict[str, AusfInfo]):
        """Sets the served_ausf_info of this NrfInfo.


        :param served_ausf_info: The served_ausf_info of this NrfInfo.
        :type served_ausf_info: Dict[str, AusfInfo]
        """

        self._served_ausf_info = served_ausf_info

    @property
    def served_ausf_info_list(self) -> Dict[str, Dict[str, AusfInfo]]:
        """Gets the served_ausf_info_list of this NrfInfo.


        :return: The served_ausf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, AusfInfo]]
        """
        return self._served_ausf_info_list

    @served_ausf_info_list.setter
    def served_ausf_info_list(self, served_ausf_info_list: Dict[str, Dict[str, AusfInfo]]):
        """Sets the served_ausf_info_list of this NrfInfo.


        :param served_ausf_info_list: The served_ausf_info_list of this NrfInfo.
        :type served_ausf_info_list: Dict[str, Dict[str, AusfInfo]]
        """

        self._served_ausf_info_list = served_ausf_info_list

    @property
    def served_amf_info(self) -> Dict[str, AmfInfo]:
        """Gets the served_amf_info of this NrfInfo.


        :return: The served_amf_info of this NrfInfo.
        :rtype: Dict[str, AmfInfo]
        """
        return self._served_amf_info

    @served_amf_info.setter
    def served_amf_info(self, served_amf_info: Dict[str, AmfInfo]):
        """Sets the served_amf_info of this NrfInfo.


        :param served_amf_info: The served_amf_info of this NrfInfo.
        :type served_amf_info: Dict[str, AmfInfo]
        """

        self._served_amf_info = served_amf_info

    @property
    def served_amf_info_list(self) -> Dict[str, Dict[str, AmfInfo]]:
        """Gets the served_amf_info_list of this NrfInfo.


        :return: The served_amf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, AmfInfo]]
        """
        return self._served_amf_info_list

    @served_amf_info_list.setter
    def served_amf_info_list(self, served_amf_info_list: Dict[str, Dict[str, AmfInfo]]):
        """Sets the served_amf_info_list of this NrfInfo.


        :param served_amf_info_list: The served_amf_info_list of this NrfInfo.
        :type served_amf_info_list: Dict[str, Dict[str, AmfInfo]]
        """

        self._served_amf_info_list = served_amf_info_list

    @property
    def served_smf_info(self) -> Dict[str, SmfInfo]:
        """Gets the served_smf_info of this NrfInfo.


        :return: The served_smf_info of this NrfInfo.
        :rtype: Dict[str, SmfInfo]
        """
        return self._served_smf_info

    @served_smf_info.setter
    def served_smf_info(self, served_smf_info: Dict[str, SmfInfo]):
        """Sets the served_smf_info of this NrfInfo.


        :param served_smf_info: The served_smf_info of this NrfInfo.
        :type served_smf_info: Dict[str, SmfInfo]
        """

        self._served_smf_info = served_smf_info

    @property
    def served_smf_info_list(self) -> Dict[str, Dict[str, SmfInfo]]:
        """Gets the served_smf_info_list of this NrfInfo.


        :return: The served_smf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, SmfInfo]]
        """
        return self._served_smf_info_list

    @served_smf_info_list.setter
    def served_smf_info_list(self, served_smf_info_list: Dict[str, Dict[str, SmfInfo]]):
        """Sets the served_smf_info_list of this NrfInfo.


        :param served_smf_info_list: The served_smf_info_list of this NrfInfo.
        :type served_smf_info_list: Dict[str, Dict[str, SmfInfo]]
        """

        self._served_smf_info_list = served_smf_info_list

    @property
    def served_upf_info(self) -> Dict[str, UpfInfo]:
        """Gets the served_upf_info of this NrfInfo.


        :return: The served_upf_info of this NrfInfo.
        :rtype: Dict[str, UpfInfo]
        """
        return self._served_upf_info

    @served_upf_info.setter
    def served_upf_info(self, served_upf_info: Dict[str, UpfInfo]):
        """Sets the served_upf_info of this NrfInfo.


        :param served_upf_info: The served_upf_info of this NrfInfo.
        :type served_upf_info: Dict[str, UpfInfo]
        """

        self._served_upf_info = served_upf_info

    @property
    def served_upf_info_list(self) -> Dict[str, Dict[str, UpfInfo]]:
        """Gets the served_upf_info_list of this NrfInfo.


        :return: The served_upf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, UpfInfo]]
        """
        return self._served_upf_info_list

    @served_upf_info_list.setter
    def served_upf_info_list(self, served_upf_info_list: Dict[str, Dict[str, UpfInfo]]):
        """Sets the served_upf_info_list of this NrfInfo.


        :param served_upf_info_list: The served_upf_info_list of this NrfInfo.
        :type served_upf_info_list: Dict[str, Dict[str, UpfInfo]]
        """

        self._served_upf_info_list = served_upf_info_list

    @property
    def served_pcf_info(self) -> Dict[str, PcfInfo]:
        """Gets the served_pcf_info of this NrfInfo.


        :return: The served_pcf_info of this NrfInfo.
        :rtype: Dict[str, PcfInfo]
        """
        return self._served_pcf_info

    @served_pcf_info.setter
    def served_pcf_info(self, served_pcf_info: Dict[str, PcfInfo]):
        """Sets the served_pcf_info of this NrfInfo.


        :param served_pcf_info: The served_pcf_info of this NrfInfo.
        :type served_pcf_info: Dict[str, PcfInfo]
        """

        self._served_pcf_info = served_pcf_info

    @property
    def served_pcf_info_list(self) -> Dict[str, Dict[str, PcfInfo]]:
        """Gets the served_pcf_info_list of this NrfInfo.


        :return: The served_pcf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, PcfInfo]]
        """
        return self._served_pcf_info_list

    @served_pcf_info_list.setter
    def served_pcf_info_list(self, served_pcf_info_list: Dict[str, Dict[str, PcfInfo]]):
        """Sets the served_pcf_info_list of this NrfInfo.


        :param served_pcf_info_list: The served_pcf_info_list of this NrfInfo.
        :type served_pcf_info_list: Dict[str, Dict[str, PcfInfo]]
        """

        self._served_pcf_info_list = served_pcf_info_list

    @property
    def served_bsf_info(self) -> Dict[str, BsfInfo]:
        """Gets the served_bsf_info of this NrfInfo.


        :return: The served_bsf_info of this NrfInfo.
        :rtype: Dict[str, BsfInfo]
        """
        return self._served_bsf_info

    @served_bsf_info.setter
    def served_bsf_info(self, served_bsf_info: Dict[str, BsfInfo]):
        """Sets the served_bsf_info of this NrfInfo.


        :param served_bsf_info: The served_bsf_info of this NrfInfo.
        :type served_bsf_info: Dict[str, BsfInfo]
        """

        self._served_bsf_info = served_bsf_info

    @property
    def served_bsf_info_list(self) -> Dict[str, Dict[str, BsfInfo]]:
        """Gets the served_bsf_info_list of this NrfInfo.


        :return: The served_bsf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, BsfInfo]]
        """
        return self._served_bsf_info_list

    @served_bsf_info_list.setter
    def served_bsf_info_list(self, served_bsf_info_list: Dict[str, Dict[str, BsfInfo]]):
        """Sets the served_bsf_info_list of this NrfInfo.


        :param served_bsf_info_list: The served_bsf_info_list of this NrfInfo.
        :type served_bsf_info_list: Dict[str, Dict[str, BsfInfo]]
        """

        self._served_bsf_info_list = served_bsf_info_list

    @property
    def served_chf_info(self) -> Dict[str, ChfInfo]:
        """Gets the served_chf_info of this NrfInfo.


        :return: The served_chf_info of this NrfInfo.
        :rtype: Dict[str, ChfInfo]
        """
        return self._served_chf_info

    @served_chf_info.setter
    def served_chf_info(self, served_chf_info: Dict[str, ChfInfo]):
        """Sets the served_chf_info of this NrfInfo.


        :param served_chf_info: The served_chf_info of this NrfInfo.
        :type served_chf_info: Dict[str, ChfInfo]
        """

        self._served_chf_info = served_chf_info

    @property
    def served_chf_info_list(self) -> Dict[str, Dict[str, ChfInfo]]:
        """Gets the served_chf_info_list of this NrfInfo.


        :return: The served_chf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, ChfInfo]]
        """
        return self._served_chf_info_list

    @served_chf_info_list.setter
    def served_chf_info_list(self, served_chf_info_list: Dict[str, Dict[str, ChfInfo]]):
        """Sets the served_chf_info_list of this NrfInfo.


        :param served_chf_info_list: The served_chf_info_list of this NrfInfo.
        :type served_chf_info_list: Dict[str, Dict[str, ChfInfo]]
        """

        self._served_chf_info_list = served_chf_info_list

    @property
    def served_nef_info(self) -> Dict[str, NefInfo]:
        """Gets the served_nef_info of this NrfInfo.


        :return: The served_nef_info of this NrfInfo.
        :rtype: Dict[str, NefInfo]
        """
        return self._served_nef_info

    @served_nef_info.setter
    def served_nef_info(self, served_nef_info: Dict[str, NefInfo]):
        """Sets the served_nef_info of this NrfInfo.


        :param served_nef_info: The served_nef_info of this NrfInfo.
        :type served_nef_info: Dict[str, NefInfo]
        """

        self._served_nef_info = served_nef_info

    @property
    def served_nwdaf_info(self) -> Dict[str, NwdafInfo]:
        """Gets the served_nwdaf_info of this NrfInfo.


        :return: The served_nwdaf_info of this NrfInfo.
        :rtype: Dict[str, NwdafInfo]
        """
        return self._served_nwdaf_info

    @served_nwdaf_info.setter
    def served_nwdaf_info(self, served_nwdaf_info: Dict[str, NwdafInfo]):
        """Sets the served_nwdaf_info of this NrfInfo.


        :param served_nwdaf_info: The served_nwdaf_info of this NrfInfo.
        :type served_nwdaf_info: Dict[str, NwdafInfo]
        """

        self._served_nwdaf_info = served_nwdaf_info

    @property
    def served_pcscf_info_list(self) -> Dict[str, Dict[str, PcscfInfo]]:
        """Gets the served_pcscf_info_list of this NrfInfo.


        :return: The served_pcscf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, PcscfInfo]]
        """
        return self._served_pcscf_info_list

    @served_pcscf_info_list.setter
    def served_pcscf_info_list(self, served_pcscf_info_list: Dict[str, Dict[str, PcscfInfo]]):
        """Sets the served_pcscf_info_list of this NrfInfo.


        :param served_pcscf_info_list: The served_pcscf_info_list of this NrfInfo.
        :type served_pcscf_info_list: Dict[str, Dict[str, PcscfInfo]]
        """

        self._served_pcscf_info_list = served_pcscf_info_list

    @property
    def served_gmlc_info(self) -> Dict[str, GmlcInfo]:
        """Gets the served_gmlc_info of this NrfInfo.


        :return: The served_gmlc_info of this NrfInfo.
        :rtype: Dict[str, GmlcInfo]
        """
        return self._served_gmlc_info

    @served_gmlc_info.setter
    def served_gmlc_info(self, served_gmlc_info: Dict[str, GmlcInfo]):
        """Sets the served_gmlc_info of this NrfInfo.


        :param served_gmlc_info: The served_gmlc_info of this NrfInfo.
        :type served_gmlc_info: Dict[str, GmlcInfo]
        """

        self._served_gmlc_info = served_gmlc_info

    @property
    def served_lmf_info(self) -> Dict[str, LmfInfo]:
        """Gets the served_lmf_info of this NrfInfo.


        :return: The served_lmf_info of this NrfInfo.
        :rtype: Dict[str, LmfInfo]
        """
        return self._served_lmf_info

    @served_lmf_info.setter
    def served_lmf_info(self, served_lmf_info: Dict[str, LmfInfo]):
        """Sets the served_lmf_info of this NrfInfo.


        :param served_lmf_info: The served_lmf_info of this NrfInfo.
        :type served_lmf_info: Dict[str, LmfInfo]
        """

        self._served_lmf_info = served_lmf_info

    @property
    def served_nf_info(self) -> Dict[str, NfInfo]:
        """Gets the served_nf_info of this NrfInfo.


        :return: The served_nf_info of this NrfInfo.
        :rtype: Dict[str, NfInfo]
        """
        return self._served_nf_info

    @served_nf_info.setter
    def served_nf_info(self, served_nf_info: Dict[str, NfInfo]):
        """Sets the served_nf_info of this NrfInfo.


        :param served_nf_info: The served_nf_info of this NrfInfo.
        :type served_nf_info: Dict[str, NfInfo]
        """

        self._served_nf_info = served_nf_info

    @property
    def served_hss_info_list(self) -> Dict[str, Dict[str, HssInfo]]:
        """Gets the served_hss_info_list of this NrfInfo.


        :return: The served_hss_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, HssInfo]]
        """
        return self._served_hss_info_list

    @served_hss_info_list.setter
    def served_hss_info_list(self, served_hss_info_list: Dict[str, Dict[str, HssInfo]]):
        """Sets the served_hss_info_list of this NrfInfo.


        :param served_hss_info_list: The served_hss_info_list of this NrfInfo.
        :type served_hss_info_list: Dict[str, Dict[str, HssInfo]]
        """

        self._served_hss_info_list = served_hss_info_list

    @property
    def served_udsf_info(self) -> Dict[str, UdsfInfo]:
        """Gets the served_udsf_info of this NrfInfo.


        :return: The served_udsf_info of this NrfInfo.
        :rtype: Dict[str, UdsfInfo]
        """
        return self._served_udsf_info

    @served_udsf_info.setter
    def served_udsf_info(self, served_udsf_info: Dict[str, UdsfInfo]):
        """Sets the served_udsf_info of this NrfInfo.


        :param served_udsf_info: The served_udsf_info of this NrfInfo.
        :type served_udsf_info: Dict[str, UdsfInfo]
        """

        self._served_udsf_info = served_udsf_info

    @property
    def served_udsf_info_list(self) -> Dict[str, Dict[str, UdsfInfo]]:
        """Gets the served_udsf_info_list of this NrfInfo.


        :return: The served_udsf_info_list of this NrfInfo.
        :rtype: Dict[str, Dict[str, UdsfInfo]]
        """
        return self._served_udsf_info_list

    @served_udsf_info_list.setter
    def served_udsf_info_list(self, served_udsf_info_list: Dict[str, Dict[str, UdsfInfo]]):
        """Sets the served_udsf_info_list of this NrfInfo.


        :param served_udsf_info_list: The served_udsf_info_list of this NrfInfo.
        :type served_udsf_info_list: Dict[str, Dict[str, UdsfInfo]]
        """

        self._served_udsf_info_list = served_udsf_info_list

    @property
    def served_scp_info_list(self) -> Dict[str, ScpInfo]:
        """Gets the served_scp_info_list of this NrfInfo.


        :return: The served_scp_info_list of this NrfInfo.
        :rtype: Dict[str, ScpInfo]
        """
        return self._served_scp_info_list

    @served_scp_info_list.setter
    def served_scp_info_list(self, served_scp_info_list: Dict[str, ScpInfo]):
        """Sets the served_scp_info_list of this NrfInfo.


        :param served_scp_info_list: The served_scp_info_list of this NrfInfo.
        :type served_scp_info_list: Dict[str, ScpInfo]
        """

        self._served_scp_info_list = served_scp_info_list
