# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_info_tai_list import AmfInfoTaiList  # noqa: F401,E501
from models.tai_range import TaiRange  # noqa: F401,E501
from models.any_of_nwdaf_info_event_ids_items import AnyOfNwdafInfoEventIdsItems  # noqa: F401,E501
from models.any_of_nwdaf_info_nwdaf_events_items import AnyOfNwdafInfoNwdafEventsItems  # noqa: F401,E501
import util


class NwdafInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event_ids: List[AnyOfNwdafInfoEventIdsItems]=None, nwdaf_events: List[AnyOfNwdafInfoNwdafEventsItems]=None, tai_list: List[AmfInfoTaiList]=None, tai_range_list: List[TaiRange]=None):  # noqa: E501
        """NwdafInfo - a model defined in Swagger

        :param event_ids: The event_ids of this NwdafInfo.  # noqa: E501
        :type event_ids: List[AnyOfNwdafInfoEventIdsItems]
        :param nwdaf_events: The nwdaf_events of this NwdafInfo.  # noqa: E501
        :type nwdaf_events: List[AnyOfNwdafInfoNwdafEventsItems]
        :param tai_list: The tai_list of this NwdafInfo.  # noqa: E501
        :type tai_list: List[AmfInfoTaiList]
        :param tai_range_list: The tai_range_list of this NwdafInfo.  # noqa: E501
        :type tai_range_list: List[TaiRange]
        """
        self.openapi_types = {
            'event_ids': List[AnyOfNwdafInfoEventIdsItems],
            'nwdaf_events': List[AnyOfNwdafInfoNwdafEventsItems],
            'tai_list': List[AmfInfoTaiList],
            'tai_range_list': List[TaiRange]
        }

        self.attribute_map = {
            'event_ids': 'eventIds',
            'nwdaf_events': 'nwdafEvents',
            'tai_list': 'taiList',
            'tai_range_list': 'taiRangeList'
        }
        self._event_ids = event_ids
        self._nwdaf_events = nwdaf_events
        self._tai_list = tai_list
        self._tai_range_list = tai_range_list

    @classmethod
    def from_dict(cls, dikt) -> 'NwdafInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NwdafInfo of this NwdafInfo.  # noqa: E501
        :rtype: NwdafInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_ids(self) -> List[AnyOfNwdafInfoEventIdsItems]:
        """Gets the event_ids of this NwdafInfo.


        :return: The event_ids of this NwdafInfo.
        :rtype: List[AnyOfNwdafInfoEventIdsItems]
        """
        return self._event_ids

    @event_ids.setter
    def event_ids(self, event_ids: List[AnyOfNwdafInfoEventIdsItems]):
        """Sets the event_ids of this NwdafInfo.


        :param event_ids: The event_ids of this NwdafInfo.
        :type event_ids: List[AnyOfNwdafInfoEventIdsItems]
        """

        self._event_ids = event_ids

    @property
    def nwdaf_events(self) -> List[AnyOfNwdafInfoNwdafEventsItems]:
        """Gets the nwdaf_events of this NwdafInfo.


        :return: The nwdaf_events of this NwdafInfo.
        :rtype: List[AnyOfNwdafInfoNwdafEventsItems]
        """
        return self._nwdaf_events

    @nwdaf_events.setter
    def nwdaf_events(self, nwdaf_events: List[AnyOfNwdafInfoNwdafEventsItems]):
        """Sets the nwdaf_events of this NwdafInfo.


        :param nwdaf_events: The nwdaf_events of this NwdafInfo.
        :type nwdaf_events: List[AnyOfNwdafInfoNwdafEventsItems]
        """

        self._nwdaf_events = nwdaf_events

    @property
    def tai_list(self) -> List[AmfInfoTaiList]:
        """Gets the tai_list of this NwdafInfo.


        :return: The tai_list of this NwdafInfo.
        :rtype: List[AmfInfoTaiList]
        """
        return self._tai_list

    @tai_list.setter
    def tai_list(self, tai_list: List[AmfInfoTaiList]):
        """Sets the tai_list of this NwdafInfo.


        :param tai_list: The tai_list of this NwdafInfo.
        :type tai_list: List[AmfInfoTaiList]
        """

        self._tai_list = tai_list

    @property
    def tai_range_list(self) -> List[TaiRange]:
        """Gets the tai_range_list of this NwdafInfo.


        :return: The tai_range_list of this NwdafInfo.
        :rtype: List[TaiRange]
        """
        return self._tai_range_list

    @tai_range_list.setter
    def tai_range_list(self, tai_range_list: List[TaiRange]):
        """Sets the tai_range_list of this NwdafInfo.


        :param tai_range_list: The tai_range_list of this NwdafInfo.
        :type tai_range_list: List[TaiRange]
        """

        self._tai_range_list = tai_range_list
