# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import re  # noqa: F401,E501
import util


class OptionsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, supported_features: str=None):  # noqa: E501
        """OptionsResponse - a model defined in Swagger

        :param supported_features: The supported_features of this OptionsResponse.  # noqa: E501
        :type supported_features: str
        """
        self.swagger_types = {
            'supported_features': str
        }

        self.attribute_map = {
            'supported_features': 'supportedFeatures'
        }
        self._supported_features = supported_features

    @classmethod
    def from_dict(cls, dikt) -> 'OptionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OptionsResponse of this OptionsResponse.  # noqa: E501
        :rtype: OptionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def supported_features(self) -> str:
        """Gets the supported_features of this OptionsResponse.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supported_features of this OptionsResponse.
        :rtype: str
        """
        return self._supported_features

    @supported_features.setter
    def supported_features(self, supported_features: str):
        """Sets the supported_features of this OptionsResponse.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supported_features: The supported_features of this OptionsResponse.
        :type supported_features: str
        """

        self._supported_features = supported_features
