# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
#from models.binding_level import BindingLevel  # noqa: F401,E501
from models.parameter_combination import ParameterCombination  # noqa: F401,E501
from models.ip_end_point import IpEndPoint  # noqa: F401,E501
#from models.date_time import DateTime  # noqa: F401,E501
#from models.diameter_identity import DiameterIdentity  # noqa: F401,E501
from models.dnn import Dnn  # noqa: F401,E501
from models.fqdn import Fqdn  # noqa: F401,E501
from models.gpsi import Gpsi  # noqa: F401,E501
from models.ipv4_addr import Ipv4Addr  # noqa: F401,E501
from models.ipv4_addr_mask import Ipv4AddrMask  # noqa: F401,E501
from models.ipv6_prefix import Ipv6Prefix  # noqa: F401,E501
from models.mac_addr48 import MacAddr48  # noqa: F401,E501
#from models.nf_instance_id import NfInstanceId  # noqa: F401,E501
from models.nf_set_id import NfSetId  # noqa: F401,E501
from models.snssai import Snssai  # noqa: F401,E501
from models.supi import Supi  # noqa: F401,E501
from models.supported_features import SupportedFeatures  # noqa: F401,E501
import util


class PcfBinding(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, supi: Supi=None, gpsi: Gpsi=None, ipv4_addr: Ipv4Addr=None, ipv6_prefix: Ipv6Prefix=None, add_ipv6_prefixes: List[Ipv6Prefix]=None, ip_domain: str=None, mac_addr48: MacAddr48=None, add_mac_addrs: List[MacAddr48]=None, dnn: Dnn=None, pcf_fqdn: Fqdn=None, pcf_ip_end_points: List[IpEndPoint]=None, pcf_diam_host: str=None, pcf_diam_realm: str=None, pcf_sm_fqdn: Fqdn=None, pcf_sm_ip_end_points: List[IpEndPoint]=None, snssai: Snssai=None, supp_feat: SupportedFeatures=None, pcf_id: str=None, pcf_set_id: NfSetId=None, recovery_time: datetime=None, para_com: ParameterCombination=None, bind_level: str=None, ipv4_frame_route_list: List[Ipv4AddrMask]=None, ipv6_frame_route_list: List[Ipv6Prefix]=None):  # noqa: E501
        """PcfBinding - a model defined in Swagger

        :param supi: The supi of this PcfBinding.  # noqa: E501
        :type supi: Supi
        :param gpsi: The gpsi of this PcfBinding.  # noqa: E501
        :type gpsi: Gpsi
        :param ipv4_addr: The ipv4_addr of this PcfBinding.  # noqa: E501
        :type ipv4_addr: Ipv4Addr
        :param ipv6_prefix: The ipv6_prefix of this PcfBinding.  # noqa: E501
        :type ipv6_prefix: Ipv6Prefix
        :param add_ipv6_prefixes: The add_ipv6_prefixes of this PcfBinding.  # noqa: E501
        :type add_ipv6_prefixes: List[Ipv6Prefix]
        :param ip_domain: The ip_domain of this PcfBinding.  # noqa: E501
        :type ip_domain: str
        :param mac_addr48: The mac_addr48 of this PcfBinding.  # noqa: E501
        :type mac_addr48: MacAddr48
        :param add_mac_addrs: The add_mac_addrs of this PcfBinding.  # noqa: E501
        :type add_mac_addrs: List[MacAddr48]
        :param dnn: The dnn of this PcfBinding.  # noqa: E501
        :type dnn: Dnn
        :param pcf_fqdn: The pcf_fqdn of this PcfBinding.  # noqa: E501
        :type pcf_fqdn: Fqdn
        :param pcf_ip_end_points: The pcf_ip_end_points of this PcfBinding.  # noqa: E501
        :type pcf_ip_end_points: List[IpEndPoint]
        :param pcf_diam_host: The pcf_diam_host of this PcfBinding.  # noqa: E501
        :type pcf_diam_host: DiameterIdentity
        :param pcf_diam_realm: The pcf_diam_realm of this PcfBinding.  # noqa: E501
        :type pcf_diam_realm: DiameterIdentity
        :param pcf_sm_fqdn: The pcf_sm_fqdn of this PcfBinding.  # noqa: E501
        :type pcf_sm_fqdn: Fqdn
        :param pcf_sm_ip_end_points: The pcf_sm_ip_end_points of this PcfBinding.  # noqa: E501
        :type pcf_sm_ip_end_points: List[IpEndPoint]
        :param snssai: The snssai of this PcfBinding.  # noqa: E501
        :type snssai: Snssai
        :param supp_feat: The supp_feat of this PcfBinding.  # noqa: E501
        :type supp_feat: SupportedFeatures
        :param pcf_id: The pcf_id of this PcfBinding.  # noqa: E501
        :type pcf_id: NfInstanceId
        :param pcf_set_id: The pcf_set_id of this PcfBinding.  # noqa: E501
        :type pcf_set_id: NfSetId
        :param recovery_time: The recovery_time of this PcfBinding.  # noqa: E501
        :type recovery_time: DateTime
        :param para_com: The para_com of this PcfBinding.  # noqa: E501
        :type para_com: ParameterCombination
        :param bind_level: The bind_level of this PcfBinding.  # noqa: E501
        :type bind_level: BindingLevel
        :param ipv4_frame_route_list: The ipv4_frame_route_list of this PcfBinding.  # noqa: E501
        :type ipv4_frame_route_list: List[Ipv4AddrMask]
        :param ipv6_frame_route_list: The ipv6_frame_route_list of this PcfBinding.  # noqa: E501
        :type ipv6_frame_route_list: List[Ipv6Prefix]
        """
        self.swagger_types = {
            'supi': Supi,
            'gpsi': Gpsi,
            'ipv4_addr': Ipv4Addr,
            'ipv6_prefix': Ipv6Prefix,
            'add_ipv6_prefixes': List[Ipv6Prefix],
            'ip_domain': str,
            'mac_addr48': MacAddr48,
            'add_mac_addrs': List[MacAddr48],
            'dnn': Dnn,
            'pcf_fqdn': Fqdn,
            'pcf_ip_end_points': List[IpEndPoint],
            'pcf_diam_host': str,
            'pcf_diam_realm': str,
            'pcf_sm_fqdn': Fqdn,
            'pcf_sm_ip_end_points': List[IpEndPoint],
            'snssai': Snssai,
            'supp_feat': SupportedFeatures,
            'pcf_id': str,
            'pcf_set_id': NfSetId,
            'recovery_time': datetime,
            'para_com': ParameterCombination,
            'bind_level': str,
            'ipv4_frame_route_list': List[Ipv4AddrMask],
            'ipv6_frame_route_list': List[Ipv6Prefix]
        }

        self.attribute_map = {
            'supi': 'supi',
            'gpsi': 'gpsi',
            'ipv4_addr': 'ipv4Addr',
            'ipv6_prefix': 'ipv6Prefix',
            'add_ipv6_prefixes': 'addIpv6Prefixes',
            'ip_domain': 'ipDomain',
            'mac_addr48': 'macAddr48',
            'add_mac_addrs': 'addMacAddrs',
            'dnn': 'dnn',
            'pcf_fqdn': 'pcfFqdn',
            'pcf_ip_end_points': 'pcfIpEndPoints',
            'pcf_diam_host': 'pcfDiamHost',
            'pcf_diam_realm': 'pcfDiamRealm',
            'pcf_sm_fqdn': 'pcfSmFqdn',
            'pcf_sm_ip_end_points': 'pcfSmIpEndPoints',
            'snssai': 'snssai',
            'supp_feat': 'suppFeat',
            'pcf_id': 'pcfId',
            'pcf_set_id': 'pcfSetId',
            'recovery_time': 'recoveryTime',
            'para_com': 'paraCom',
            'bind_level': 'bindLevel',
            'ipv4_frame_route_list': 'ipv4FrameRouteList',
            'ipv6_frame_route_list': 'ipv6FrameRouteList'
        }
        self._supi = supi
        self._gpsi = gpsi
        self._ipv4_addr = ipv4_addr
        self._ipv6_prefix = ipv6_prefix
        self._add_ipv6_prefixes = add_ipv6_prefixes
        self._ip_domain = ip_domain
        self._mac_addr48 = mac_addr48
        self._add_mac_addrs = add_mac_addrs
        self._dnn = dnn
        self._pcf_fqdn = pcf_fqdn
        self._pcf_ip_end_points = pcf_ip_end_points
        self._pcf_diam_host = pcf_diam_host
        self._pcf_diam_realm = pcf_diam_realm
        self._pcf_sm_fqdn = pcf_sm_fqdn
        self._pcf_sm_ip_end_points = pcf_sm_ip_end_points
        self._snssai = snssai
        self._supp_feat = supp_feat
        self._pcf_id = pcf_id
        self._pcf_set_id = pcf_set_id
        self._recovery_time = recovery_time
        self._para_com = para_com
        self._bind_level = bind_level
        self._ipv4_frame_route_list = ipv4_frame_route_list
        self._ipv6_frame_route_list = ipv6_frame_route_list

    @classmethod
    def from_dict(cls, dikt) -> 'PcfBinding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PcfBinding of this PcfBinding.  # noqa: E501
        :rtype: PcfBinding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def supi(self) -> Supi:
        """Gets the supi of this PcfBinding.


        :return: The supi of this PcfBinding.
        :rtype: Supi
        """
        return self._supi

    @supi.setter
    def supi(self, supi: Supi):
        """Sets the supi of this PcfBinding.


        :param supi: The supi of this PcfBinding.
        :type supi: Supi
        """

        self._supi = supi

    @property
    def gpsi(self) -> Gpsi:
        """Gets the gpsi of this PcfBinding.


        :return: The gpsi of this PcfBinding.
        :rtype: Gpsi
        """
        return self._gpsi

    @gpsi.setter
    def gpsi(self, gpsi: Gpsi):
        """Sets the gpsi of this PcfBinding.


        :param gpsi: The gpsi of this PcfBinding.
        :type gpsi: Gpsi
        """

        self._gpsi = gpsi

    @property
    def ipv4_addr(self) -> Ipv4Addr:
        """Gets the ipv4_addr of this PcfBinding.


        :return: The ipv4_addr of this PcfBinding.
        :rtype: Ipv4Addr
        """
        return self._ipv4_addr

    @ipv4_addr.setter
    def ipv4_addr(self, ipv4_addr: Ipv4Addr):
        """Sets the ipv4_addr of this PcfBinding.


        :param ipv4_addr: The ipv4_addr of this PcfBinding.
        :type ipv4_addr: Ipv4Addr
        """

        self._ipv4_addr = ipv4_addr

    @property
    def ipv6_prefix(self) -> Ipv6Prefix:
        """Gets the ipv6_prefix of this PcfBinding.


        :return: The ipv6_prefix of this PcfBinding.
        :rtype: Ipv6Prefix
        """
        return self._ipv6_prefix

    @ipv6_prefix.setter
    def ipv6_prefix(self, ipv6_prefix: Ipv6Prefix):
        """Sets the ipv6_prefix of this PcfBinding.


        :param ipv6_prefix: The ipv6_prefix of this PcfBinding.
        :type ipv6_prefix: Ipv6Prefix
        """

        self._ipv6_prefix = ipv6_prefix

    @property
    def add_ipv6_prefixes(self) -> List[Ipv6Prefix]:
        """Gets the add_ipv6_prefixes of this PcfBinding.

        The additional IPv6 Address Prefixes of the served UE.  # noqa: E501

        :return: The add_ipv6_prefixes of this PcfBinding.
        :rtype: List[Ipv6Prefix]
        """
        return self._add_ipv6_prefixes

    @add_ipv6_prefixes.setter
    def add_ipv6_prefixes(self, add_ipv6_prefixes: List[Ipv6Prefix]):
        """Sets the add_ipv6_prefixes of this PcfBinding.

        The additional IPv6 Address Prefixes of the served UE.  # noqa: E501

        :param add_ipv6_prefixes: The add_ipv6_prefixes of this PcfBinding.
        :type add_ipv6_prefixes: List[Ipv6Prefix]
        """

        self._add_ipv6_prefixes = add_ipv6_prefixes

    @property
    def ip_domain(self) -> str:
        """Gets the ip_domain of this PcfBinding.


        :return: The ip_domain of this PcfBinding.
        :rtype: str
        """
        return self._ip_domain

    @ip_domain.setter
    def ip_domain(self, ip_domain: str):
        """Sets the ip_domain of this PcfBinding.


        :param ip_domain: The ip_domain of this PcfBinding.
        :type ip_domain: str
        """

        self._ip_domain = ip_domain

    @property
    def mac_addr48(self) -> MacAddr48:
        """Gets the mac_addr48 of this PcfBinding.


        :return: The mac_addr48 of this PcfBinding.
        :rtype: MacAddr48
        """
        return self._mac_addr48

    @mac_addr48.setter
    def mac_addr48(self, mac_addr48: MacAddr48):
        """Sets the mac_addr48 of this PcfBinding.


        :param mac_addr48: The mac_addr48 of this PcfBinding.
        :type mac_addr48: MacAddr48
        """

        self._mac_addr48 = mac_addr48

    @property
    def add_mac_addrs(self) -> List[MacAddr48]:
        """Gets the add_mac_addrs of this PcfBinding.

        The additional MAC Addresses of the served UE.  # noqa: E501

        :return: The add_mac_addrs of this PcfBinding.
        :rtype: List[MacAddr48]
        """
        return self._add_mac_addrs

    @add_mac_addrs.setter
    def add_mac_addrs(self, add_mac_addrs: List[MacAddr48]):
        """Sets the add_mac_addrs of this PcfBinding.

        The additional MAC Addresses of the served UE.  # noqa: E501

        :param add_mac_addrs: The add_mac_addrs of this PcfBinding.
        :type add_mac_addrs: List[MacAddr48]
        """

        self._add_mac_addrs = add_mac_addrs

    @property
    def dnn(self) -> Dnn:
        """Gets the dnn of this PcfBinding.


        :return: The dnn of this PcfBinding.
        :rtype: Dnn
        """
        return self._dnn

    @dnn.setter
    def dnn(self, dnn: Dnn):
        """Sets the dnn of this PcfBinding.


        :param dnn: The dnn of this PcfBinding.
        :type dnn: Dnn
        """
        if dnn is None:
            raise ValueError("Invalid value for `dnn`, must not be `None`")  # noqa: E501

        self._dnn = dnn

    @property
    def pcf_fqdn(self) -> Fqdn:
        """Gets the pcf_fqdn of this PcfBinding.


        :return: The pcf_fqdn of this PcfBinding.
        :rtype: Fqdn
        """
        return self._pcf_fqdn

    @pcf_fqdn.setter
    def pcf_fqdn(self, pcf_fqdn: Fqdn):
        """Sets the pcf_fqdn of this PcfBinding.


        :param pcf_fqdn: The pcf_fqdn of this PcfBinding.
        :type pcf_fqdn: Fqdn
        """

        self._pcf_fqdn = pcf_fqdn

    @property
    def pcf_ip_end_points(self) -> List[IpEndPoint]:
        """Gets the pcf_ip_end_points of this PcfBinding.

        IP end points of the PCF hosting the Npcf_PolicyAuthorization service  # noqa: E501

        :return: The pcf_ip_end_points of this PcfBinding.
        :rtype: List[IpEndPoint]
        """
        return self._pcf_ip_end_points

    @pcf_ip_end_points.setter
    def pcf_ip_end_points(self, pcf_ip_end_points: List[IpEndPoint]):
        """Sets the pcf_ip_end_points of this PcfBinding.

        IP end points of the PCF hosting the Npcf_PolicyAuthorization service  # noqa: E501

        :param pcf_ip_end_points: The pcf_ip_end_points of this PcfBinding.
        :type pcf_ip_end_points: List[IpEndPoint]
        """

        self._pcf_ip_end_points = pcf_ip_end_points

    @property
    def pcf_diam_host(self) -> str:
        """Gets the pcf_diam_host of this PcfBinding.


        :return: The pcf_diam_host of this PcfBinding.
        :rtype: DiameterIdentity
        """
        return self._pcf_diam_host

    @pcf_diam_host.setter
    def pcf_diam_host(self, pcf_diam_host: str):
        """Sets the pcf_diam_host of this PcfBinding.


        :param pcf_diam_host: The pcf_diam_host of this PcfBinding.
        :type pcf_diam_host: DiameterIdentity
        """

        self._pcf_diam_host = pcf_diam_host

    @property
    def pcf_diam_realm(self) -> str:
        """Gets the pcf_diam_realm of this PcfBinding.


        :return: The pcf_diam_realm of this PcfBinding.
        :rtype: DiameterIdentity
        """
        return self._pcf_diam_realm

    @pcf_diam_realm.setter
    def pcf_diam_realm(self, pcf_diam_realm: str):
        """Sets the pcf_diam_realm of this PcfBinding.


        :param pcf_diam_realm: The pcf_diam_realm of this PcfBinding.
        :type pcf_diam_realm: DiameterIdentity
        """

        self._pcf_diam_realm = pcf_diam_realm

    @property
    def pcf_sm_fqdn(self) -> Fqdn:
        """Gets the pcf_sm_fqdn of this PcfBinding.


        :return: The pcf_sm_fqdn of this PcfBinding.
        :rtype: Fqdn
        """
        return self._pcf_sm_fqdn

    @pcf_sm_fqdn.setter
    def pcf_sm_fqdn(self, pcf_sm_fqdn: Fqdn):
        """Sets the pcf_sm_fqdn of this PcfBinding.


        :param pcf_sm_fqdn: The pcf_sm_fqdn of this PcfBinding.
        :type pcf_sm_fqdn: Fqdn
        """

        self._pcf_sm_fqdn = pcf_sm_fqdn

    @property
    def pcf_sm_ip_end_points(self) -> List[IpEndPoint]:
        """Gets the pcf_sm_ip_end_points of this PcfBinding.

        IP end points of the PCF hosting the Npcf_SMPolicyControl service.  # noqa: E501

        :return: The pcf_sm_ip_end_points of this PcfBinding.
        :rtype: List[IpEndPoint]
        """
        return self._pcf_sm_ip_end_points

    @pcf_sm_ip_end_points.setter
    def pcf_sm_ip_end_points(self, pcf_sm_ip_end_points: List[IpEndPoint]):
        """Sets the pcf_sm_ip_end_points of this PcfBinding.

        IP end points of the PCF hosting the Npcf_SMPolicyControl service.  # noqa: E501

        :param pcf_sm_ip_end_points: The pcf_sm_ip_end_points of this PcfBinding.
        :type pcf_sm_ip_end_points: List[IpEndPoint]
        """

        self._pcf_sm_ip_end_points = pcf_sm_ip_end_points

    @property
    def snssai(self) -> Snssai:
        """Gets the snssai of this PcfBinding.


        :return: The snssai of this PcfBinding.
        :rtype: Snssai
        """
        return self._snssai

    @snssai.setter
    def snssai(self, snssai: Snssai):
        """Sets the snssai of this PcfBinding.


        :param snssai: The snssai of this PcfBinding.
        :type snssai: Snssai
        """
        if snssai is None:
            raise ValueError("Invalid value for `snssai`, must not be `None`")  # noqa: E501

        self._snssai = snssai

    @property
    def supp_feat(self) -> SupportedFeatures:
        """Gets the supp_feat of this PcfBinding.


        :return: The supp_feat of this PcfBinding.
        :rtype: SupportedFeatures
        """
        return self._supp_feat

    @supp_feat.setter
    def supp_feat(self, supp_feat: SupportedFeatures):
        """Sets the supp_feat of this PcfBinding.


        :param supp_feat: The supp_feat of this PcfBinding.
        :type supp_feat: SupportedFeatures
        """

        self._supp_feat = supp_feat

    @property
    def pcf_id(self) -> str:
        """Gets the pcf_id of this PcfBinding.


        :return: The pcf_id of this PcfBinding.
        :rtype: NfInstanceId
        """
        return self._pcf_id

    @pcf_id.setter
    def pcf_id(self, pcf_id: str):
        """Sets the pcf_id of this PcfBinding.


        :param pcf_id: The pcf_id of this PcfBinding.
        :type pcf_id: NfInstanceId
        """

        self._pcf_id = pcf_id

    @property
    def pcf_set_id(self) -> NfSetId:
        """Gets the pcf_set_id of this PcfBinding.


        :return: The pcf_set_id of this PcfBinding.
        :rtype: NfSetId
        """
        return self._pcf_set_id

    @pcf_set_id.setter
    def pcf_set_id(self, pcf_set_id: NfSetId):
        """Sets the pcf_set_id of this PcfBinding.


        :param pcf_set_id: The pcf_set_id of this PcfBinding.
        :type pcf_set_id: NfSetId
        """

        self._pcf_set_id = pcf_set_id

    @property
    def recovery_time(self) -> datetime:
        """Gets the recovery_time of this PcfBinding.


        :return: The recovery_time of this PcfBinding.
        :rtype: DateTime
        """
        return self._recovery_time

    @recovery_time.setter
    def recovery_time(self, recovery_time: datetime):
        """Sets the recovery_time of this PcfBinding.


        :param recovery_time: The recovery_time of this PcfBinding.
        :type recovery_time: DateTime
        """

        self._recovery_time = recovery_time

    @property
    def para_com(self) -> ParameterCombination:
        """Gets the para_com of this PcfBinding.


        :return: The para_com of this PcfBinding.
        :rtype: ParameterCombination
        """
        return self._para_com

    @para_com.setter
    def para_com(self, para_com: ParameterCombination):
        """Sets the para_com of this PcfBinding.


        :param para_com: The para_com of this PcfBinding.
        :type para_com: ParameterCombination
        """

        self._para_com = para_com

    @property
    def bind_level(self) -> str:
        """Gets the bind_level of this PcfBinding.


        :return: The bind_level of this PcfBinding.
        :rtype: BindingLevel
        """
        return self._bind_level

    @bind_level.setter
    def bind_level(self, bind_level: str):
        """Sets the bind_level of this PcfBinding.


        :param bind_level: The bind_level of this PcfBinding.
        :type bind_level: BindingLevel
        """

        self._bind_level = bind_level

    @property
    def ipv4_frame_route_list(self) -> List[Ipv4AddrMask]:
        """Gets the ipv4_frame_route_list of this PcfBinding.


        :return: The ipv4_frame_route_list of this PcfBinding.
        :rtype: List[Ipv4AddrMask]
        """
        return self._ipv4_frame_route_list

    @ipv4_frame_route_list.setter
    def ipv4_frame_route_list(self, ipv4_frame_route_list: List[Ipv4AddrMask]):
        """Sets the ipv4_frame_route_list of this PcfBinding.


        :param ipv4_frame_route_list: The ipv4_frame_route_list of this PcfBinding.
        :type ipv4_frame_route_list: List[Ipv4AddrMask]
        """

        self._ipv4_frame_route_list = ipv4_frame_route_list

    @property
    def ipv6_frame_route_list(self) -> List[Ipv6Prefix]:
        """Gets the ipv6_frame_route_list of this PcfBinding.


        :return: The ipv6_frame_route_list of this PcfBinding.
        :rtype: List[Ipv6Prefix]
        """
        return self._ipv6_frame_route_list

    @ipv6_frame_route_list.setter
    def ipv6_frame_route_list(self, ipv6_frame_route_list: List[Ipv6Prefix]):
        """Sets the ipv6_frame_route_list of this PcfBinding.


        :param ipv6_frame_route_list: The ipv6_frame_route_list of this PcfBinding.
        :type ipv6_frame_route_list: List[Ipv6Prefix]
        """

        self._ipv6_frame_route_list = ipv6_frame_route_list
