# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.notification_method import NotificationMethod  # noqa: F401,E501
from models.date_time import DateTime  # noqa: F401,E501
from models.duration_sec import DurationSec  # noqa: F401,E501
from models.notification_flag import NotificationFlag  # noqa: F401,E501
from models.partitioning_criteria import PartitioningCriteria  # noqa: F401,E501
from models.sampling_ratio import SamplingRatio  # noqa: F401,E501
from models.uinteger import Uinteger  # noqa: F401,E501
import util


class ReportingInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, imm_rep: bool=None, notif_method: NotificationMethod=None, max_report_nbr: Uinteger=None, mon_dur: DateTime=None, rep_period: DurationSec=None, samp_ratio: SamplingRatio=None, partition_criteria: List[PartitioningCriteria]=None, grp_rep_time: DurationSec=None, notif_flag: NotificationFlag=None):  # noqa: E501
        """ReportingInformation - a model defined in Swagger

        :param imm_rep: The imm_rep of this ReportingInformation.  # noqa: E501
        :type imm_rep: bool
        :param notif_method: The notif_method of this ReportingInformation.  # noqa: E501
        :type notif_method: NotificationMethod
        :param max_report_nbr: The max_report_nbr of this ReportingInformation.  # noqa: E501
        :type max_report_nbr: Uinteger
        :param mon_dur: The mon_dur of this ReportingInformation.  # noqa: E501
        :type mon_dur: DateTime
        :param rep_period: The rep_period of this ReportingInformation.  # noqa: E501
        :type rep_period: DurationSec
        :param samp_ratio: The samp_ratio of this ReportingInformation.  # noqa: E501
        :type samp_ratio: SamplingRatio
        :param partition_criteria: The partition_criteria of this ReportingInformation.  # noqa: E501
        :type partition_criteria: List[PartitioningCriteria]
        :param grp_rep_time: The grp_rep_time of this ReportingInformation.  # noqa: E501
        :type grp_rep_time: DurationSec
        :param notif_flag: The notif_flag of this ReportingInformation.  # noqa: E501
        :type notif_flag: NotificationFlag
        """
        self.swagger_types = {
            'imm_rep': bool,
            'notif_method': NotificationMethod,
            'max_report_nbr': Uinteger,
            'mon_dur': DateTime,
            'rep_period': DurationSec,
            'samp_ratio': SamplingRatio,
            'partition_criteria': List[PartitioningCriteria],
            'grp_rep_time': DurationSec,
            'notif_flag': NotificationFlag
        }

        self.attribute_map = {
            'imm_rep': 'immRep',
            'notif_method': 'notifMethod',
            'max_report_nbr': 'maxReportNbr',
            'mon_dur': 'monDur',
            'rep_period': 'repPeriod',
            'samp_ratio': 'sampRatio',
            'partition_criteria': 'partitionCriteria',
            'grp_rep_time': 'grpRepTime',
            'notif_flag': 'notifFlag'
        }
        self._imm_rep = imm_rep
        self._notif_method = notif_method
        self._max_report_nbr = max_report_nbr
        self._mon_dur = mon_dur
        self._rep_period = rep_period
        self._samp_ratio = samp_ratio
        self._partition_criteria = partition_criteria
        self._grp_rep_time = grp_rep_time
        self._notif_flag = notif_flag

    @classmethod
    def from_dict(cls, dikt) -> 'ReportingInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportingInformation of this ReportingInformation.  # noqa: E501
        :rtype: ReportingInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imm_rep(self) -> bool:
        """Gets the imm_rep of this ReportingInformation.


        :return: The imm_rep of this ReportingInformation.
        :rtype: bool
        """
        return self._imm_rep

    @imm_rep.setter
    def imm_rep(self, imm_rep: bool):
        """Sets the imm_rep of this ReportingInformation.


        :param imm_rep: The imm_rep of this ReportingInformation.
        :type imm_rep: bool
        """

        self._imm_rep = imm_rep

    @property
    def notif_method(self) -> NotificationMethod:
        """Gets the notif_method of this ReportingInformation.


        :return: The notif_method of this ReportingInformation.
        :rtype: NotificationMethod
        """
        return self._notif_method

    @notif_method.setter
    def notif_method(self, notif_method: NotificationMethod):
        """Sets the notif_method of this ReportingInformation.


        :param notif_method: The notif_method of this ReportingInformation.
        :type notif_method: NotificationMethod
        """

        self._notif_method = notif_method

    @property
    def max_report_nbr(self) -> Uinteger:
        """Gets the max_report_nbr of this ReportingInformation.


        :return: The max_report_nbr of this ReportingInformation.
        :rtype: Uinteger
        """
        return self._max_report_nbr

    @max_report_nbr.setter
    def max_report_nbr(self, max_report_nbr: Uinteger):
        """Sets the max_report_nbr of this ReportingInformation.


        :param max_report_nbr: The max_report_nbr of this ReportingInformation.
        :type max_report_nbr: Uinteger
        """

        self._max_report_nbr = max_report_nbr

    @property
    def mon_dur(self) -> DateTime:
        """Gets the mon_dur of this ReportingInformation.


        :return: The mon_dur of this ReportingInformation.
        :rtype: DateTime
        """
        return self._mon_dur

    @mon_dur.setter
    def mon_dur(self, mon_dur: DateTime):
        """Sets the mon_dur of this ReportingInformation.


        :param mon_dur: The mon_dur of this ReportingInformation.
        :type mon_dur: DateTime
        """

        self._mon_dur = mon_dur

    @property
    def rep_period(self) -> DurationSec:
        """Gets the rep_period of this ReportingInformation.


        :return: The rep_period of this ReportingInformation.
        :rtype: DurationSec
        """
        return self._rep_period

    @rep_period.setter
    def rep_period(self, rep_period: DurationSec):
        """Sets the rep_period of this ReportingInformation.


        :param rep_period: The rep_period of this ReportingInformation.
        :type rep_period: DurationSec
        """

        self._rep_period = rep_period

    @property
    def samp_ratio(self) -> SamplingRatio:
        """Gets the samp_ratio of this ReportingInformation.


        :return: The samp_ratio of this ReportingInformation.
        :rtype: SamplingRatio
        """
        return self._samp_ratio

    @samp_ratio.setter
    def samp_ratio(self, samp_ratio: SamplingRatio):
        """Sets the samp_ratio of this ReportingInformation.


        :param samp_ratio: The samp_ratio of this ReportingInformation.
        :type samp_ratio: SamplingRatio
        """

        self._samp_ratio = samp_ratio

    @property
    def partition_criteria(self) -> List[PartitioningCriteria]:
        """Gets the partition_criteria of this ReportingInformation.

        Criteria for partitioning the UEs before applying the sampling ratio.  # noqa: E501

        :return: The partition_criteria of this ReportingInformation.
        :rtype: List[PartitioningCriteria]
        """
        return self._partition_criteria

    @partition_criteria.setter
    def partition_criteria(self, partition_criteria: List[PartitioningCriteria]):
        """Sets the partition_criteria of this ReportingInformation.

        Criteria for partitioning the UEs before applying the sampling ratio.  # noqa: E501

        :param partition_criteria: The partition_criteria of this ReportingInformation.
        :type partition_criteria: List[PartitioningCriteria]
        """

        self._partition_criteria = partition_criteria

    @property
    def grp_rep_time(self) -> DurationSec:
        """Gets the grp_rep_time of this ReportingInformation.


        :return: The grp_rep_time of this ReportingInformation.
        :rtype: DurationSec
        """
        return self._grp_rep_time

    @grp_rep_time.setter
    def grp_rep_time(self, grp_rep_time: DurationSec):
        """Sets the grp_rep_time of this ReportingInformation.


        :param grp_rep_time: The grp_rep_time of this ReportingInformation.
        :type grp_rep_time: DurationSec
        """

        self._grp_rep_time = grp_rep_time

    @property
    def notif_flag(self) -> NotificationFlag:
        """Gets the notif_flag of this ReportingInformation.


        :return: The notif_flag of this ReportingInformation.
        :rtype: NotificationFlag
        """
        return self._notif_flag

    @notif_flag.setter
    def notif_flag(self, notif_flag: NotificationFlag):
        """Sets the notif_flag of this ReportingInformation.


        :param notif_flag: The notif_flag of this ReportingInformation.
        :type notif_flag: NotificationFlag
        """

        self._notif_flag = notif_flag
