# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class ScpDomainCond(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, scp_domains: List[str]=None):  # noqa: E501
        """ScpDomainCond - a model defined in Swagger

        :param scp_domains: The scp_domains of this ScpDomainCond.  # noqa: E501
        :type scp_domains: List[str]
        """
        self.swagger_types = {
            'scp_domains': List[str]
        }

        self.attribute_map = {
            'scp_domains': 'scpDomains'
        }
        self._scp_domains = scp_domains

    @classmethod
    def from_dict(cls, dikt) -> 'ScpDomainCond':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScpDomainCond of this ScpDomainCond.  # noqa: E501
        :rtype: ScpDomainCond
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scp_domains(self) -> List[str]:
        """Gets the scp_domains of this ScpDomainCond.


        :return: The scp_domains of this ScpDomainCond.
        :rtype: List[str]
        """
        return self._scp_domains

    @scp_domains.setter
    def scp_domains(self, scp_domains: List[str]):
        """Sets the scp_domains of this ScpDomainCond.


        :param scp_domains: The scp_domains of this ScpDomainCond.
        :type scp_domains: List[str]
        """

        self._scp_domains = scp_domains
