# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.dnn_smf_info_item import DnnSmfInfoItem  # noqa: F401,E501
from models.subscription_data_req_snssais import SubscriptionDataReqSnssais  # noqa: F401,E501
import util


class SnssaiSmfInfoItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, s_nssai: SubscriptionDataReqSnssais=None, dnn_smf_info_list: List[DnnSmfInfoItem]=None):  # noqa: E501
        """SnssaiSmfInfoItem - a model defined in Swagger

        :param s_nssai: The s_nssai of this SnssaiSmfInfoItem.  # noqa: E501
        :type s_nssai: SubscriptionDataReqSnssais
        :param dnn_smf_info_list: The dnn_smf_info_list of this SnssaiSmfInfoItem.  # noqa: E501
        :type dnn_smf_info_list: List[DnnSmfInfoItem]
        """
        self.swagger_types = {
            's_nssai': SubscriptionDataReqSnssais,
            'dnn_smf_info_list': List[DnnSmfInfoItem]
        }

        self.attribute_map = {
            's_nssai': 'sNssai',
            'dnn_smf_info_list': 'dnnSmfInfoList'
        }
        self._s_nssai = s_nssai
        self._dnn_smf_info_list = dnn_smf_info_list

    @classmethod
    def from_dict(cls, dikt) -> 'SnssaiSmfInfoItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SnssaiSmfInfoItem of this SnssaiSmfInfoItem.  # noqa: E501
        :rtype: SnssaiSmfInfoItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def s_nssai(self) -> SubscriptionDataReqSnssais:
        """Gets the s_nssai of this SnssaiSmfInfoItem.


        :return: The s_nssai of this SnssaiSmfInfoItem.
        :rtype: SubscriptionDataReqSnssais
        """
        return self._s_nssai

    @s_nssai.setter
    def s_nssai(self, s_nssai: SubscriptionDataReqSnssais):
        """Sets the s_nssai of this SnssaiSmfInfoItem.


        :param s_nssai: The s_nssai of this SnssaiSmfInfoItem.
        :type s_nssai: SubscriptionDataReqSnssais
        """
        if s_nssai is None:
            raise ValueError("Invalid value for `s_nssai`, must not be `None`")  # noqa: E501

        self._s_nssai = s_nssai

    @property
    def dnn_smf_info_list(self) -> List[DnnSmfInfoItem]:
        """Gets the dnn_smf_info_list of this SnssaiSmfInfoItem.


        :return: The dnn_smf_info_list of this SnssaiSmfInfoItem.
        :rtype: List[DnnSmfInfoItem]
        """
        return self._dnn_smf_info_list

    @dnn_smf_info_list.setter
    def dnn_smf_info_list(self, dnn_smf_info_list: List[DnnSmfInfoItem]):
        """Sets the dnn_smf_info_list of this SnssaiSmfInfoItem.


        :param dnn_smf_info_list: The dnn_smf_info_list of this SnssaiSmfInfoItem.
        :type dnn_smf_info_list: List[DnnSmfInfoItem]
        """
        if dnn_smf_info_list is None:
            raise ValueError("Invalid value for `dnn_smf_info_list`, must not be `None`")  # noqa: E501

        self._dnn_smf_info_list = dnn_smf_info_list
