# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.nf_profile_plmn_list import NFProfilePlmnList  # noqa: F401,E501
from models.tac_range import TacRange  # noqa: F401,E501
import re  # noqa: F401,E501
import util


class TaiRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plmn_id: NFProfilePlmnList=None, tac_range_list: List[TacRange]=None, nid: str=None):  # noqa: E501
        """TaiRange - a model defined in Swagger

        :param plmn_id: The plmn_id of this TaiRange.  # noqa: E501
        :type plmn_id: NFProfilePlmnList
        :param tac_range_list: The tac_range_list of this TaiRange.  # noqa: E501
        :type tac_range_list: List[TacRange]
        :param nid: The nid of this TaiRange.  # noqa: E501
        :type nid: str
        """
        self.openapi_types = {
            'plmn_id': NFProfilePlmnList,
            'tac_range_list': List[TacRange],
            'nid': str
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            'tac_range_list': 'tacRangeList',
            'nid': 'nid'
        }
        self._plmn_id = plmn_id
        self._tac_range_list = tac_range_list
        self._nid = nid

    @classmethod
    def from_dict(cls, dikt) -> 'TaiRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaiRange of this TaiRange.  # noqa: E501
        :rtype: TaiRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self) -> NFProfilePlmnList:
        """Gets the plmn_id of this TaiRange.


        :return: The plmn_id of this TaiRange.
        :rtype: NFProfilePlmnList
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id: NFProfilePlmnList):
        """Sets the plmn_id of this TaiRange.


        :param plmn_id: The plmn_id of this TaiRange.
        :type plmn_id: NFProfilePlmnList
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id

    @property
    def tac_range_list(self) -> List[TacRange]:
        """Gets the tac_range_list of this TaiRange.


        :return: The tac_range_list of this TaiRange.
        :rtype: List[TacRange]
        """
        return self._tac_range_list

    @tac_range_list.setter
    def tac_range_list(self, tac_range_list: List[TacRange]):
        """Sets the tac_range_list of this TaiRange.


        :param tac_range_list: The tac_range_list of this TaiRange.
        :type tac_range_list: List[TacRange]
        """
        if tac_range_list is None:
            raise ValueError("Invalid value for `tac_range_list`, must not be `None`")  # noqa: E501

        self._tac_range_list = tac_range_list

    @property
    def nid(self) -> str:
        """Gets the nid of this TaiRange.

        This represents the Network Identifier, which together with a PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS 23.501 clause 5.30.2.1).    # noqa: E501

        :return: The nid of this TaiRange.
        :rtype: str
        """
        return self._nid

    @nid.setter
    def nid(self, nid: str):
        """Sets the nid of this TaiRange.

        This represents the Network Identifier, which together with a PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS 23.501 clause 5.30.2.1).    # noqa: E501

        :param nid: The nid of this TaiRange.
        :type nid: str
        """

        self._nid = nid
