# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
#from models.date_time import DateTime
import util


class TemporalValidity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_time: datetime=None, stop_time: datetime=None):  # noqa: E501
        """EventNotification - a model defined in Swagger
        """
        self.swagger_types = {
            'start_time': datetime,
            'stop_time': datetime,
        }

        self.attribute_map = {
            'start_time': 'startTime',
            'stop_time': 'stopTime'
        }
        self._start_time = start_time
        self._stop_time = stop_time
    @classmethod
    def from_dict(cls, dikt) -> 'TemporalValidity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventNotification of this EventNotification.  # noqa: E501
        :rtype: EventNotification
        """
        return util.deserialize_model(dikt, cls)
