# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.dnai_change_type import DnaiChangeType
from models.eas_ip_replacement_info import EasIpReplacementInfo
from models.eth_flow_description import EthFlowDescription
from models.event_notification import EventNotification
from models.flow_info import FlowInfo
from models.geographical_area import GeographicalArea
from models.reporting_information import ReportingInformation
from models.route_to_location import RouteToLocation
from models.snssai import Snssai
from models.subscribed_event import SubscribedEvent
#from models.temporal_validity import TemporalValidity
from models.websock_notif_config import WebsockNotifConfig
import util
import re  # noqa: E501

class TrafficInfluSub(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, af_service_id=None, af_app_id=None, af_trans_id=None, app_relo_ind=None, dnn=None, snssai=None, external_group_id=None, any_ue_ind=None, subscribed_events=None, gpsi=None, ipv4_addr=None, ip_domain=None, ipv6_addr=None, mac_addr=None, dnai_chg_type=None, notification_destination=None, request_test_notification=None, websock_notif_config=None, _self=None, traffic_filters=None, eth_traffic_filters=None, traffic_routes=None, tfc_corr_ind=None, temp_validities=None, valid_geo_zone_ids=None, geo_areas=None, af_ack_ind=None, addr_preser_ind=None, sim_conn_ind=None, sim_conn_term=None, max_allowed_up_lat=None, eas_ip_replace_infos=None, eas_redis_ind=None, event_req=None, event_reports=None, supp_feat=None):  # noqa: E501
        """TrafficInfluSub - a model defined in OpenAPI

        :param af_service_id: The af_service_id of this TrafficInfluSub.  # noqa: E501
        :type af_service_id: str
        :param af_app_id: The af_app_id of this TrafficInfluSub.  # noqa: E501
        :type af_app_id: str
        :param af_trans_id: The af_trans_id of this TrafficInfluSub.  # noqa: E501
        :type af_trans_id: str
        :param app_relo_ind: The app_relo_ind of this TrafficInfluSub.  # noqa: E501
        :type app_relo_ind: bool
        :param dnn: The dnn of this TrafficInfluSub.  # noqa: E501
        :type dnn: str
        :param snssai: The snssai of this TrafficInfluSub.  # noqa: E501
        :type snssai: Snssai
        :param external_group_id: The external_group_id of this TrafficInfluSub.  # noqa: E501
        :type external_group_id: str
        :param any_ue_ind: The any_ue_ind of this TrafficInfluSub.  # noqa: E501
        :type any_ue_ind: bool
        :param subscribed_events: The subscribed_events of this TrafficInfluSub.  # noqa: E501
        :type subscribed_events: List[SubscribedEvent]
        :param gpsi: The gpsi of this TrafficInfluSub.  # noqa: E501
        :type gpsi: str
        :param ipv4_addr: The ipv4_addr of this TrafficInfluSub.  # noqa: E501
        :type ipv4_addr: str
        :param ip_domain: The ip_domain of this TrafficInfluSub.  # noqa: E501
        :type ip_domain: str
        :param ipv6_addr: The ipv6_addr of this TrafficInfluSub.  # noqa: E501
        :type ipv6_addr: str
        :param mac_addr: The mac_addr of this TrafficInfluSub.  # noqa: E501
        :type mac_addr: str
        :param dnai_chg_type: The dnai_chg_type of this TrafficInfluSub.  # noqa: E501
        :type dnai_chg_type: DnaiChangeType
        :param notification_destination: The notification_destination of this TrafficInfluSub.  # noqa: E501
        :type notification_destination: str
        :param request_test_notification: The request_test_notification of this TrafficInfluSub.  # noqa: E501
        :type request_test_notification: bool
        :param websock_notif_config: The websock_notif_config of this TrafficInfluSub.  # noqa: E501
        :type websock_notif_config: WebsockNotifConfig
        :param _self: The _self of this TrafficInfluSub.  # noqa: E501
        :type _self: str
        :param traffic_filters: The traffic_filters of this TrafficInfluSub.  # noqa: E501
        :type traffic_filters: List[FlowInfo]
        :param eth_traffic_filters: The eth_traffic_filters of this TrafficInfluSub.  # noqa: E501
        :type eth_traffic_filters: List[EthFlowDescription]
        :param traffic_routes: The traffic_routes of this TrafficInfluSub.  # noqa: E501
        :type traffic_routes: List[RouteToLocation]
        :param tfc_corr_ind: The tfc_corr_ind of this TrafficInfluSub.  # noqa: E501
        :type tfc_corr_ind: bool
        :param temp_validities: The temp_validities of this TrafficInfluSub.  # noqa: E501
        :type temp_validities: List[TemporalValidity]
        :param valid_geo_zone_ids: The valid_geo_zone_ids of this TrafficInfluSub.  # noqa: E501
        :type valid_geo_zone_ids: List[str]
        :param geo_areas: The geo_areas of this TrafficInfluSub.  # noqa: E501
        :type geo_areas: List[GeographicalArea]
        :param af_ack_ind: The af_ack_ind of this TrafficInfluSub.  # noqa: E501
        :type af_ack_ind: bool
        :param addr_preser_ind: The addr_preser_ind of this TrafficInfluSub.  # noqa: E501
        :type addr_preser_ind: bool
        :param sim_conn_ind: The sim_conn_ind of this TrafficInfluSub.  # noqa: E501
        :type sim_conn_ind: bool
        :param sim_conn_term: The sim_conn_term of this TrafficInfluSub.  # noqa: E501
        :type sim_conn_term: int
        :param max_allowed_up_lat: The max_allowed_up_lat of this TrafficInfluSub.  # noqa: E501
        :type max_allowed_up_lat: int
        :param eas_ip_replace_infos: The eas_ip_replace_infos of this TrafficInfluSub.  # noqa: E501
        :type eas_ip_replace_infos: List[EasIpReplacementInfo]
        :param eas_redis_ind: The eas_redis_ind of this TrafficInfluSub.  # noqa: E501
        :type eas_redis_ind: bool
        :param event_req: The event_req of this TrafficInfluSub.  # noqa: E501
        :type event_req: ReportingInformation
        :param event_reports: The event_reports of this TrafficInfluSub.  # noqa: E501
        :type event_reports: List[EventNotification]
        :param supp_feat: The supp_feat of this TrafficInfluSub.  # noqa: E501
        :type supp_feat: str
        """
        self.openapi_types = {
            'af_service_id': str,
            'af_app_id': str,
            'af_trans_id': str,
            'app_relo_ind': bool,
            'dnn': str,
            'snssai': Snssai,
            'external_group_id': str,
            'any_ue_ind': bool,
            'subscribed_events': List[SubscribedEvent],
            'gpsi': str,
            'ipv4_addr': str,
            'ip_domain': str,
            'ipv6_addr': str,
            'mac_addr': str,
            'dnai_chg_type': DnaiChangeType,
            'notification_destination': str,
            'request_test_notification': bool,
            'websock_notif_config': WebsockNotifConfig,
            '_self': str,
            'traffic_filters': List[FlowInfo],
            'eth_traffic_filters': List[EthFlowDescription],
            'traffic_routes': List[RouteToLocation],
            'tfc_corr_ind': bool,
            'temp_validities': List[str],
            'valid_geo_zone_ids': List[str],
            'geo_areas': List[GeographicalArea],
            'af_ack_ind': bool,
            'addr_preser_ind': bool,
            'sim_conn_ind': bool,
            'sim_conn_term': int,
            'max_allowed_up_lat': int,
            'eas_ip_replace_infos': List[EasIpReplacementInfo],
            'eas_redis_ind': bool,
            'event_req': ReportingInformation,
            'event_reports': List[EventNotification],
            'supp_feat': str
        }

        self.attribute_map = {
            'af_service_id': 'afServiceId',
            'af_app_id': 'afAppId',
            'af_trans_id': 'afTransId',
            'app_relo_ind': 'appReloInd',
            'dnn': 'dnn',
            'snssai': 'snssai',
            'external_group_id': 'externalGroupId',
            'any_ue_ind': 'anyUeInd',
            'subscribed_events': 'subscribedEvents',
            'gpsi': 'gpsi',
            'ipv4_addr': 'ipv4Addr',
            'ip_domain': 'ipDomain',
            'ipv6_addr': 'ipv6Addr',
            'mac_addr': 'macAddr',
            'dnai_chg_type': 'dnaiChgType',
            'notification_destination': 'notificationDestination',
            'request_test_notification': 'requestTestNotification',
            'websock_notif_config': 'websockNotifConfig',
            '_self': 'self',
            'traffic_filters': 'trafficFilters',
            'eth_traffic_filters': 'ethTrafficFilters',
            'traffic_routes': 'trafficRoutes',
            'tfc_corr_ind': 'tfcCorrInd',
            'temp_validities': 'tempValidities',
            'valid_geo_zone_ids': 'validGeoZoneIds',
            'geo_areas': 'geoAreas',
            'af_ack_ind': 'afAckInd',
            'addr_preser_ind': 'addrPreserInd',
            'sim_conn_ind': 'simConnInd',
            'sim_conn_term': 'simConnTerm',
            'max_allowed_up_lat': 'maxAllowedUpLat',
            'eas_ip_replace_infos': 'easIpReplaceInfos',
            'eas_redis_ind': 'easRedisInd',
            'event_req': 'eventReq',
            'event_reports': 'eventReports',
            'supp_feat': 'suppFeat'
        }

        self._af_service_id = af_service_id
        self._af_app_id = af_app_id
        self._af_trans_id = af_trans_id
        self._app_relo_ind = app_relo_ind
        self._dnn = dnn
        self._snssai = snssai
        self._external_group_id = external_group_id
        self._any_ue_ind = any_ue_ind
        self._subscribed_events = subscribed_events
        self._gpsi = gpsi
        self._ipv4_addr = ipv4_addr
        self._ip_domain = ip_domain
        self._ipv6_addr = ipv6_addr
        self._mac_addr = mac_addr
        self._dnai_chg_type = dnai_chg_type
        self._notification_destination = notification_destination
        self._request_test_notification = request_test_notification
        self._websock_notif_config = websock_notif_config
        self.__self = _self
        self._traffic_filters = traffic_filters
        self._eth_traffic_filters = eth_traffic_filters
        self._traffic_routes = traffic_routes
        self._tfc_corr_ind = tfc_corr_ind
        self._temp_validities = temp_validities
        self._valid_geo_zone_ids = valid_geo_zone_ids
        self._geo_areas = geo_areas
        self._af_ack_ind = af_ack_ind
        self._addr_preser_ind = addr_preser_ind
        self._sim_conn_ind = sim_conn_ind
        self._sim_conn_term = sim_conn_term
        self._max_allowed_up_lat = max_allowed_up_lat
        self._eas_ip_replace_infos = eas_ip_replace_infos
        self._eas_redis_ind = eas_redis_ind
        self._event_req = event_req
        self._event_reports = event_reports
        self._supp_feat = supp_feat

    @classmethod
    def from_dict(cls, dikt) -> 'TrafficInfluSub':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrafficInfluSub of this TrafficInfluSub.  # noqa: E501
        :rtype: TrafficInfluSub
        """
        return util.deserialize_model(dikt, cls)

    @property
    def af_service_id(self):
        """Gets the af_service_id of this TrafficInfluSub.

        Identifies a service on behalf of which the AF is issuing the request.  # noqa: E501

        :return: The af_service_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._af_service_id

    @af_service_id.setter
    def af_service_id(self, af_service_id):
        """Sets the af_service_id of this TrafficInfluSub.

        Identifies a service on behalf of which the AF is issuing the request.  # noqa: E501

        :param af_service_id: The af_service_id of this TrafficInfluSub.
        :type af_service_id: str
        """

        self._af_service_id = af_service_id

    @property
    def af_app_id(self):
        """Gets the af_app_id of this TrafficInfluSub.

        Identifies an application.  # noqa: E501

        :return: The af_app_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._af_app_id

    @af_app_id.setter
    def af_app_id(self, af_app_id):
        """Sets the af_app_id of this TrafficInfluSub.

        Identifies an application.  # noqa: E501

        :param af_app_id: The af_app_id of this TrafficInfluSub.
        :type af_app_id: str
        """

        self._af_app_id = af_app_id

    @property
    def af_trans_id(self):
        """Gets the af_trans_id of this TrafficInfluSub.

        Identifies an NEF Northbound interface transaction, generated by the AF.  # noqa: E501

        :return: The af_trans_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._af_trans_id

    @af_trans_id.setter
    def af_trans_id(self, af_trans_id):
        """Sets the af_trans_id of this TrafficInfluSub.

        Identifies an NEF Northbound interface transaction, generated by the AF.  # noqa: E501

        :param af_trans_id: The af_trans_id of this TrafficInfluSub.
        :type af_trans_id: str
        """

        self._af_trans_id = af_trans_id

    @property
    def app_relo_ind(self):
        """Gets the app_relo_ind of this TrafficInfluSub.

        Identifies whether an application can be relocated once a location of the application has been selected.   # noqa: E501

        :return: The app_relo_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._app_relo_ind

    @app_relo_ind.setter
    def app_relo_ind(self, app_relo_ind):
        """Sets the app_relo_ind of this TrafficInfluSub.

        Identifies whether an application can be relocated once a location of the application has been selected.   # noqa: E501

        :param app_relo_ind: The app_relo_ind of this TrafficInfluSub.
        :type app_relo_ind: bool
        """

        self._app_relo_ind = app_relo_ind

    @property
    def dnn(self):
        """Gets the dnn of this TrafficInfluSub.

        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").   # noqa: E501

        :return: The dnn of this TrafficInfluSub.
        :rtype: str
        """
        return self._dnn

    @dnn.setter
    def dnn(self, dnn):
        """Sets the dnn of this TrafficInfluSub.

        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").   # noqa: E501

        :param dnn: The dnn of this TrafficInfluSub.
        :type dnn: str
        """

        self._dnn = dnn

    @property
    def snssai(self):
        """Gets the snssai of this TrafficInfluSub.


        :return: The snssai of this TrafficInfluSub.
        :rtype: Snssai
        """
        return self._snssai

    @snssai.setter
    def snssai(self, snssai):
        """Sets the snssai of this TrafficInfluSub.


        :param snssai: The snssai of this TrafficInfluSub.
        :type snssai: Snssai
        """

        self._snssai = snssai

    @property
    def external_group_id(self):
        """Gets the external_group_id of this TrafficInfluSub.

        string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clauses 4.6.2 and 4.6.3 of 3GPP TS 23.682 for more information.  # noqa: E501

        :return: The external_group_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._external_group_id

    @external_group_id.setter
    def external_group_id(self, external_group_id):
        """Sets the external_group_id of this TrafficInfluSub.

        string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clauses 4.6.2 and 4.6.3 of 3GPP TS 23.682 for more information.  # noqa: E501

        :param external_group_id: The external_group_id of this TrafficInfluSub.
        :type external_group_id: str
        """

        self._external_group_id = external_group_id

    @property
    def any_ue_ind(self):
        """Gets the any_ue_ind of this TrafficInfluSub.

        Identifies whether the AF request applies to any UE. This attribute shall set to \"true\" if applicable for any UE, otherwise, set to \"false\".   # noqa: E501

        :return: The any_ue_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._any_ue_ind

    @any_ue_ind.setter
    def any_ue_ind(self, any_ue_ind):
        """Sets the any_ue_ind of this TrafficInfluSub.

        Identifies whether the AF request applies to any UE. This attribute shall set to \"true\" if applicable for any UE, otherwise, set to \"false\".   # noqa: E501

        :param any_ue_ind: The any_ue_ind of this TrafficInfluSub.
        :type any_ue_ind: bool
        """

        self._any_ue_ind = any_ue_ind

    @property
    def subscribed_events(self):
        """Gets the subscribed_events of this TrafficInfluSub.

        Identifies the requirement to be notified of the event(s).  # noqa: E501

        :return: The subscribed_events of this TrafficInfluSub.
        :rtype: List[SubscribedEvent]
        """
        return self._subscribed_events

    @subscribed_events.setter
    def subscribed_events(self, subscribed_events):
        """Sets the subscribed_events of this TrafficInfluSub.

        Identifies the requirement to be notified of the event(s).  # noqa: E501

        :param subscribed_events: The subscribed_events of this TrafficInfluSub.
        :type subscribed_events: List[SubscribedEvent]
        """
        if subscribed_events is not None and len(subscribed_events) < 1:
            raise ValueError("Invalid value for `subscribed_events`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._subscribed_events = subscribed_events

    @property
    def gpsi(self):
        """Gets the gpsi of this TrafficInfluSub.

        String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.    # noqa: E501

        :return: The gpsi of this TrafficInfluSub.
        :rtype: str
        """
        return self._gpsi

    @gpsi.setter
    def gpsi(self, gpsi):
        """Sets the gpsi of this TrafficInfluSub.

        String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.    # noqa: E501

        :param gpsi: The gpsi of this TrafficInfluSub.
        :type gpsi: str
        """
        if gpsi is not None and not re.search(r'^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$', gpsi):  # noqa: E501
            raise ValueError("Invalid value for `gpsi`, must be a follow pattern or equal to `/^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$/`")  # noqa: E501

        self._gpsi = gpsi

    @property
    def ipv4_addr(self):
        """Gets the ipv4_addr of this TrafficInfluSub.

        string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166.  # noqa: E501

        :return: The ipv4_addr of this TrafficInfluSub.
        :rtype: str
        """
        return self._ipv4_addr

    @ipv4_addr.setter
    def ipv4_addr(self, ipv4_addr):
        """Sets the ipv4_addr of this TrafficInfluSub.

        string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166.  # noqa: E501

        :param ipv4_addr: The ipv4_addr of this TrafficInfluSub.
        :type ipv4_addr: str
        """

        self._ipv4_addr = ipv4_addr

    @property
    def ip_domain(self):
        """Gets the ip_domain of this TrafficInfluSub.


        :return: The ip_domain of this TrafficInfluSub.
        :rtype: str
        """
        return self._ip_domain

    @ip_domain.setter
    def ip_domain(self, ip_domain):
        """Sets the ip_domain of this TrafficInfluSub.


        :param ip_domain: The ip_domain of this TrafficInfluSub.
        :type ip_domain: str
        """

        self._ip_domain = ip_domain

    @property
    def ipv6_addr(self):
        """Gets the ipv6_addr of this TrafficInfluSub.

        string identifying a Ipv6 address formatted according to clause 4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of IETF RFC 5952 shall not be used.  # noqa: E501

        :return: The ipv6_addr of this TrafficInfluSub.
        :rtype: str
        """
        return self._ipv6_addr

    @ipv6_addr.setter
    def ipv6_addr(self, ipv6_addr):
        """Sets the ipv6_addr of this TrafficInfluSub.

        string identifying a Ipv6 address formatted according to clause 4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of IETF RFC 5952 shall not be used.  # noqa: E501

        :param ipv6_addr: The ipv6_addr of this TrafficInfluSub.
        :type ipv6_addr: str
        """

        self._ipv6_addr = ipv6_addr

    @property
    def mac_addr(self):
        """Gets the mac_addr of this TrafficInfluSub.

        String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.   # noqa: E501

        :return: The mac_addr of this TrafficInfluSub.
        :rtype: str
        """
        return self._mac_addr

    @mac_addr.setter
    def mac_addr(self, mac_addr):
        """Sets the mac_addr of this TrafficInfluSub.

        String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.   # noqa: E501

        :param mac_addr: The mac_addr of this TrafficInfluSub.
        :type mac_addr: str
        """
        if mac_addr is not None and not re.search(r'^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$', mac_addr):  # noqa: E501
            raise ValueError("Invalid value for `mac_addr`, must be a follow pattern or equal to `/^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$/`")  # noqa: E501

        self._mac_addr = mac_addr

    @property
    def dnai_chg_type(self):
        """Gets the dnai_chg_type of this TrafficInfluSub.


        :return: The dnai_chg_type of this TrafficInfluSub.
        :rtype: DnaiChangeType
        """
        return self._dnai_chg_type

    @dnai_chg_type.setter
    def dnai_chg_type(self, dnai_chg_type):
        """Sets the dnai_chg_type of this TrafficInfluSub.


        :param dnai_chg_type: The dnai_chg_type of this TrafficInfluSub.
        :type dnai_chg_type: DnaiChangeType
        """

        self._dnai_chg_type = dnai_chg_type

    @property
    def notification_destination(self):
        """Gets the notification_destination of this TrafficInfluSub.

        string formatted according to IETF RFC 3986 identifying a referenced resource.  # noqa: E501

        :return: The notification_destination of this TrafficInfluSub.
        :rtype: str
        """
        return self._notification_destination

    @notification_destination.setter
    def notification_destination(self, notification_destination):
        """Sets the notification_destination of this TrafficInfluSub.

        string formatted according to IETF RFC 3986 identifying a referenced resource.  # noqa: E501

        :param notification_destination: The notification_destination of this TrafficInfluSub.
        :type notification_destination: str
        """

        self._notification_destination = notification_destination

    @property
    def request_test_notification(self):
        """Gets the request_test_notification of this TrafficInfluSub.

        Set to true by the SCS/AS to request the NEF to send a test notification as defined in clause 5.2.5.3. Set to false or omitted otherwise.   # noqa: E501

        :return: The request_test_notification of this TrafficInfluSub.
        :rtype: bool
        """
        return self._request_test_notification

    @request_test_notification.setter
    def request_test_notification(self, request_test_notification):
        """Sets the request_test_notification of this TrafficInfluSub.

        Set to true by the SCS/AS to request the NEF to send a test notification as defined in clause 5.2.5.3. Set to false or omitted otherwise.   # noqa: E501

        :param request_test_notification: The request_test_notification of this TrafficInfluSub.
        :type request_test_notification: bool
        """

        self._request_test_notification = request_test_notification

    @property
    def websock_notif_config(self):
        """Gets the websock_notif_config of this TrafficInfluSub.


        :return: The websock_notif_config of this TrafficInfluSub.
        :rtype: WebsockNotifConfig
        """
        return self._websock_notif_config

    @websock_notif_config.setter
    def websock_notif_config(self, websock_notif_config):
        """Sets the websock_notif_config of this TrafficInfluSub.


        :param websock_notif_config: The websock_notif_config of this TrafficInfluSub.
        :type websock_notif_config: WebsockNotifConfig
        """

        self._websock_notif_config = websock_notif_config

    @property
    def _self(self):
        """Gets the _self of this TrafficInfluSub.

        string formatted according to IETF RFC 3986 identifying a referenced resource.  # noqa: E501

        :return: The _self of this TrafficInfluSub.
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this TrafficInfluSub.

        string formatted according to IETF RFC 3986 identifying a referenced resource.  # noqa: E501

        :param _self: The _self of this TrafficInfluSub.
        :type _self: str
        """

        self.__self = _self

    @property
    def traffic_filters(self):
        """Gets the traffic_filters of this TrafficInfluSub.

        Identifies IP packet filters.  # noqa: E501

        :return: The traffic_filters of this TrafficInfluSub.
        :rtype: List[FlowInfo]
        """
        return self._traffic_filters

    @traffic_filters.setter
    def traffic_filters(self, traffic_filters):
        """Sets the traffic_filters of this TrafficInfluSub.

        Identifies IP packet filters.  # noqa: E501

        :param traffic_filters: The traffic_filters of this TrafficInfluSub.
        :type traffic_filters: List[FlowInfo]
        """
        if traffic_filters is not None and len(traffic_filters) < 1:
            raise ValueError("Invalid value for `traffic_filters`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._traffic_filters = traffic_filters

    @property
    def eth_traffic_filters(self):
        """Gets the eth_traffic_filters of this TrafficInfluSub.

        Identifies Ethernet packet filters.  # noqa: E501

        :return: The eth_traffic_filters of this TrafficInfluSub.
        :rtype: List[EthFlowDescription]
        """
        return self._eth_traffic_filters

    @eth_traffic_filters.setter
    def eth_traffic_filters(self, eth_traffic_filters):
        """Sets the eth_traffic_filters of this TrafficInfluSub.

        Identifies Ethernet packet filters.  # noqa: E501

        :param eth_traffic_filters: The eth_traffic_filters of this TrafficInfluSub.
        :type eth_traffic_filters: List[EthFlowDescription]
        """
        if eth_traffic_filters is not None and len(eth_traffic_filters) < 1:
            raise ValueError("Invalid value for `eth_traffic_filters`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._eth_traffic_filters = eth_traffic_filters

    @property
    def traffic_routes(self):
        """Gets the traffic_routes of this TrafficInfluSub.

        Identifies the N6 traffic routing requirement.  # noqa: E501

        :return: The traffic_routes of this TrafficInfluSub.
        :rtype: List[RouteToLocation]
        """
        return self._traffic_routes

    @traffic_routes.setter
    def traffic_routes(self, traffic_routes):
        """Sets the traffic_routes of this TrafficInfluSub.

        Identifies the N6 traffic routing requirement.  # noqa: E501

        :param traffic_routes: The traffic_routes of this TrafficInfluSub.
        :type traffic_routes: List[RouteToLocation]
        """
        if traffic_routes is not None and len(traffic_routes) < 1:
            raise ValueError("Invalid value for `traffic_routes`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._traffic_routes = traffic_routes

    @property
    def tfc_corr_ind(self):
        """Gets the tfc_corr_ind of this TrafficInfluSub.


        :return: The tfc_corr_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._tfc_corr_ind

    @tfc_corr_ind.setter
    def tfc_corr_ind(self, tfc_corr_ind):
        """Sets the tfc_corr_ind of this TrafficInfluSub.


        :param tfc_corr_ind: The tfc_corr_ind of this TrafficInfluSub.
        :type tfc_corr_ind: bool
        """

        self._tfc_corr_ind = tfc_corr_ind

    @property
    def temp_validities(self):
        """Gets the temp_validities of this TrafficInfluSub.


        :return: The temp_validities of this TrafficInfluSub.
        :rtype: List[TemporalValidity]
        """
        return self._temp_validities

    @temp_validities.setter
    def temp_validities(self, temp_validities):
        """Sets the temp_validities of this TrafficInfluSub.


        :param temp_validities: The temp_validities of this TrafficInfluSub.
        :type temp_validities: List[TemporalValidity]
        """

        self._temp_validities = temp_validities

    @property
    def valid_geo_zone_ids(self):
        """Gets the valid_geo_zone_ids of this TrafficInfluSub.

        Identifies a geographic zone that the AF request applies only to the traffic of UE(s) located in this specific zone.   # noqa: E501

        :return: The valid_geo_zone_ids of this TrafficInfluSub.
        :rtype: List[str]
        """
        return self._valid_geo_zone_ids

    @valid_geo_zone_ids.setter
    def valid_geo_zone_ids(self, valid_geo_zone_ids):
        """Sets the valid_geo_zone_ids of this TrafficInfluSub.

        Identifies a geographic zone that the AF request applies only to the traffic of UE(s) located in this specific zone.   # noqa: E501

        :param valid_geo_zone_ids: The valid_geo_zone_ids of this TrafficInfluSub.
        :type valid_geo_zone_ids: List[str]
        """
        if valid_geo_zone_ids is not None and len(valid_geo_zone_ids) < 1:
            raise ValueError("Invalid value for `valid_geo_zone_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._valid_geo_zone_ids = valid_geo_zone_ids

    @property
    def geo_areas(self):
        """Gets the geo_areas of this TrafficInfluSub.

        Identifies geographical areas within which the AF request applies.  # noqa: E501

        :return: The geo_areas of this TrafficInfluSub.
        :rtype: List[GeographicalArea]
        """
        return self._geo_areas

    @geo_areas.setter
    def geo_areas(self, geo_areas):
        """Sets the geo_areas of this TrafficInfluSub.

        Identifies geographical areas within which the AF request applies.  # noqa: E501

        :param geo_areas: The geo_areas of this TrafficInfluSub.
        :type geo_areas: List[GeographicalArea]
        """
        if geo_areas is not None and len(geo_areas) < 1:
            raise ValueError("Invalid value for `geo_areas`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._geo_areas = geo_areas

    @property
    def af_ack_ind(self):
        """Gets the af_ack_ind of this TrafficInfluSub.


        :return: The af_ack_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._af_ack_ind

    @af_ack_ind.setter
    def af_ack_ind(self, af_ack_ind):
        """Sets the af_ack_ind of this TrafficInfluSub.


        :param af_ack_ind: The af_ack_ind of this TrafficInfluSub.
        :type af_ack_ind: bool
        """

        self._af_ack_ind = af_ack_ind

    @property
    def addr_preser_ind(self):
        """Gets the addr_preser_ind of this TrafficInfluSub.


        :return: The addr_preser_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._addr_preser_ind

    @addr_preser_ind.setter
    def addr_preser_ind(self, addr_preser_ind):
        """Sets the addr_preser_ind of this TrafficInfluSub.


        :param addr_preser_ind: The addr_preser_ind of this TrafficInfluSub.
        :type addr_preser_ind: bool
        """

        self._addr_preser_ind = addr_preser_ind

    @property
    def sim_conn_ind(self):
        """Gets the sim_conn_ind of this TrafficInfluSub.

        Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.   # noqa: E501

        :return: The sim_conn_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._sim_conn_ind

    @sim_conn_ind.setter
    def sim_conn_ind(self, sim_conn_ind):
        """Sets the sim_conn_ind of this TrafficInfluSub.

        Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.   # noqa: E501

        :param sim_conn_ind: The sim_conn_ind of this TrafficInfluSub.
        :type sim_conn_ind: bool
        """

        self._sim_conn_ind = sim_conn_ind

    @property
    def sim_conn_term(self):
        """Gets the sim_conn_term of this TrafficInfluSub.

        indicating a time in seconds.  # noqa: E501

        :return: The sim_conn_term of this TrafficInfluSub.
        :rtype: int
        """
        return self._sim_conn_term

    @sim_conn_term.setter
    def sim_conn_term(self, sim_conn_term):
        """Sets the sim_conn_term of this TrafficInfluSub.

        indicating a time in seconds.  # noqa: E501

        :param sim_conn_term: The sim_conn_term of this TrafficInfluSub.
        :type sim_conn_term: int
        """

        self._sim_conn_term = sim_conn_term

    @property
    def max_allowed_up_lat(self):
        """Gets the max_allowed_up_lat of this TrafficInfluSub.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :return: The max_allowed_up_lat of this TrafficInfluSub.
        :rtype: int
        """
        return self._max_allowed_up_lat

    @max_allowed_up_lat.setter
    def max_allowed_up_lat(self, max_allowed_up_lat):
        """Sets the max_allowed_up_lat of this TrafficInfluSub.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :param max_allowed_up_lat: The max_allowed_up_lat of this TrafficInfluSub.
        :type max_allowed_up_lat: int
        """
        if max_allowed_up_lat is not None and max_allowed_up_lat < 0:  # noqa: E501
            raise ValueError("Invalid value for `max_allowed_up_lat`, must be a value greater than or equal to `0`")  # noqa: E501

        self._max_allowed_up_lat = max_allowed_up_lat

    @property
    def eas_ip_replace_infos(self):
        """Gets the eas_ip_replace_infos of this TrafficInfluSub.

        Contains EAS IP replacement information.  # noqa: E501

        :return: The eas_ip_replace_infos of this TrafficInfluSub.
        :rtype: List[EasIpReplacementInfo]
        """
        return self._eas_ip_replace_infos

    @eas_ip_replace_infos.setter
    def eas_ip_replace_infos(self, eas_ip_replace_infos):
        """Sets the eas_ip_replace_infos of this TrafficInfluSub.

        Contains EAS IP replacement information.  # noqa: E501

        :param eas_ip_replace_infos: The eas_ip_replace_infos of this TrafficInfluSub.
        :type eas_ip_replace_infos: List[EasIpReplacementInfo]
        """
        if eas_ip_replace_infos is not None and len(eas_ip_replace_infos) < 1:
            raise ValueError("Invalid value for `eas_ip_replace_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._eas_ip_replace_infos = eas_ip_replace_infos

    @property
    def eas_redis_ind(self):
        """Gets the eas_redis_ind of this TrafficInfluSub.

        Indicates the EAS rediscovery is required for the application if it is included and set to \"true\".  # noqa: E501

        :return: The eas_redis_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._eas_redis_ind

    @eas_redis_ind.setter
    def eas_redis_ind(self, eas_redis_ind):
        """Sets the eas_redis_ind of this TrafficInfluSub.

        Indicates the EAS rediscovery is required for the application if it is included and set to \"true\".  # noqa: E501

        :param eas_redis_ind: The eas_redis_ind of this TrafficInfluSub.
        :type eas_redis_ind: bool
        """

        self._eas_redis_ind = eas_redis_ind

    @property
    def event_req(self):
        """Gets the event_req of this TrafficInfluSub.


        :return: The event_req of this TrafficInfluSub.
        :rtype: ReportingInformation
        """
        return self._event_req

    @event_req.setter
    def event_req(self, event_req):
        """Sets the event_req of this TrafficInfluSub.


        :param event_req: The event_req of this TrafficInfluSub.
        :type event_req: ReportingInformation
        """

        self._event_req = event_req

    @property
    def event_reports(self):
        """Gets the event_reports of this TrafficInfluSub.


        :return: The event_reports of this TrafficInfluSub.
        :rtype: List[EventNotification]
        """
        return self._event_reports

    @event_reports.setter
    def event_reports(self, event_reports):
        """Sets the event_reports of this TrafficInfluSub.


        :param event_reports: The event_reports of this TrafficInfluSub.
        :type event_reports: List[EventNotification]
        """
        if event_reports is not None and len(event_reports) < 1:
            raise ValueError("Invalid value for `event_reports`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._event_reports = event_reports

    @property
    def supp_feat(self):
        """Gets the supp_feat of this TrafficInfluSub.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supp_feat of this TrafficInfluSub.
        :rtype: str
        """
        return self._supp_feat

    @supp_feat.setter
    def supp_feat(self, supp_feat):
        """Sets the supp_feat of this TrafficInfluSub.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supp_feat: The supp_feat of this TrafficInfluSub.
        :type supp_feat: str
        """
        if supp_feat is not None and not re.search(r'^[A-Fa-f0-9]*$', supp_feat):  # noqa: E501
            raise ValueError("Invalid value for `supp_feat`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._supp_feat = supp_feat
