# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.event_notification import EventNotification  # noqa: F401,E501
from models.subscribed_event import SubscribedEvent  # noqa: F401,E501
from models.traffic_correlation_info import TrafficCorrelationInfo  # noqa: F401,E501
from models.external_group_id import ExternalGroupId  # noqa: F401,E501
from models.flow_info import FlowInfo  # noqa: F401,E501
from models.ipv4_addr import Ipv4Addr  # noqa: F401,E501
from models.ipv6_addr import Ipv6Addr  # noqa: F401,E501
from models.link import Link  # noqa: F401,E501
from models.websock_notif_config import WebsockNotifConfig  # noqa: F401,E501
from models.eth_flow_description import EthFlowDescription  # noqa: F401,E501
from models.temporal_validity import TemporalValidity  # noqa: F401,E501
from models.reporting_information import ReportingInformation  # noqa: F401,E501
from models.dnai_change_type import DnaiChangeType  # noqa: F401,E501
from models.dnn import Dnn  # noqa: F401,E501
from models.duration_sec import DurationSec  # noqa: F401,E501
from models.eas_ip_replacement_info import EasIpReplacementInfo  # noqa: F401,E501
from models.gpsi import Gpsi  # noqa: F401,E501
from models.mac_addr48 import MacAddr48  # noqa: F401,E501
from models.route_to_location import RouteToLocation  # noqa: F401,E501
from models.snssai import Snssai  # noqa: F401,E501
from models.supported_features import SupportedFeatures  # noqa: F401,E501
from models.uinteger import Uinteger  # noqa: F401,E501
import util


class TrafficInfluSub(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, af_service_id: str=None, af_app_id: str=None, af_trans_id: str=None, app_relo_ind: bool=None, dnn: Dnn=None, snssai: Snssai=None, external_group_id: ExternalGroupId=None, external_group_ids: List[ExternalGroupId]=None, ext_subsc_cats: List[str]=None, any_ue_ind: bool=None, subscribed_events: List[SubscribedEvent]=None, gpsi: Gpsi=None, ipv4_addr: Ipv4Addr=None, ip_domain: str=None, ipv6_addr: Ipv6Addr=None, mac_addr: MacAddr48=None, dnai_chg_type: DnaiChangeType=None, notification_destination: Link=None, request_test_notification: bool=None, websock_notif_config: WebsockNotifConfig=None, _self: Link=None, traffic_filters: List[FlowInfo]=None, eth_traffic_filters: List[EthFlowDescription]=None, traffic_routes: List[RouteToLocation]=None, sfc_id_dl: str=None, sfc_id_ul: str=None, tfc_corr_ind: bool=None, temp_validities: List[TemporalValidity]=None, valid_geo_zone_ids: List[str]=None, af_ack_ind: bool=None, addr_preser_ind: bool=None, sim_conn_ind: bool=None, sim_conn_term: DurationSec=None, max_allowed_up_lat: Uinteger=None, eas_ip_replace_infos: List[EasIpReplacementInfo]=None, eas_redis_ind: bool=None, event_req: ReportingInformation=None, event_reports: List[EventNotification]=None, cand_dnai_ind: bool=None, tfc_corre_info: TrafficCorrelationInfo=None, supp_feat: SupportedFeatures=None):  # noqa: E501
        """TrafficInfluSub - a model defined in Swagger

        :param af_service_id: The af_service_id of this TrafficInfluSub.  # noqa: E501
        :type af_service_id: str
        :param af_app_id: The af_app_id of this TrafficInfluSub.  # noqa: E501
        :type af_app_id: str
        :param af_trans_id: The af_trans_id of this TrafficInfluSub.  # noqa: E501
        :type af_trans_id: str
        :param app_relo_ind: The app_relo_ind of this TrafficInfluSub.  # noqa: E501
        :type app_relo_ind: bool
        :param dnn: The dnn of this TrafficInfluSub.  # noqa: E501
        :type dnn: TS29571CommonDataYamlcomponentsschemasDnn
        :param snssai: The snssai of this TrafficInfluSub.  # noqa: E501
        :type snssai: TS29571CommonDataYamlcomponentsschemasSnssai
        :param external_group_id: The external_group_id of this TrafficInfluSub.  # noqa: E501
        :type external_group_id: TS29122CommonDataYamlcomponentsschemasExternalGroupId
        :param external_group_ids: The external_group_ids of this TrafficInfluSub.  # noqa: E501
        :type external_group_ids: List[TS29122CommonDataYamlcomponentsschemasExternalGroupId]
        :param ext_subsc_cats: The ext_subsc_cats of this TrafficInfluSub.  # noqa: E501
        :type ext_subsc_cats: List[str]
        :param any_ue_ind: The any_ue_ind of this TrafficInfluSub.  # noqa: E501
        :type any_ue_ind: bool
        :param subscribed_events: The subscribed_events of this TrafficInfluSub.  # noqa: E501
        :type subscribed_events: List[SubscribedEvent]
        :param gpsi: The gpsi of this TrafficInfluSub.  # noqa: E501
        :type gpsi: TS29571CommonDataYamlcomponentsschemasGpsi
        :param ipv4_addr: The ipv4_addr of this TrafficInfluSub.  # noqa: E501
        :type ipv4_addr: TS29122CommonDataYamlcomponentsschemasIpv4Addr
        :param ip_domain: The ip_domain of this TrafficInfluSub.  # noqa: E501
        :type ip_domain: str
        :param ipv6_addr: The ipv6_addr of this TrafficInfluSub.  # noqa: E501
        :type ipv6_addr: TS29122CommonDataYamlcomponentsschemasIpv6Addr
        :param mac_addr: The mac_addr of this TrafficInfluSub.  # noqa: E501
        :type mac_addr: TS29571CommonDataYamlcomponentsschemasMacAddr48
        :param dnai_chg_type: The dnai_chg_type of this TrafficInfluSub.  # noqa: E501
        :type dnai_chg_type: TS29571CommonDataYamlcomponentsschemasDnaiChangeType
        :param notification_destination: The notification_destination of this TrafficInfluSub.  # noqa: E501
        :type notification_destination: TS29122CommonDataYamlcomponentsschemasLink
        :param request_test_notification: The request_test_notification of this TrafficInfluSub.  # noqa: E501
        :type request_test_notification: bool
        :param websock_notif_config: The websock_notif_config of this TrafficInfluSub.  # noqa: E501
        :type websock_notif_config: TS29122CommonDataYamlcomponentsschemasWebsockNotifConfig
        :param _self: The _self of this TrafficInfluSub.  # noqa: E501
        :type _self: TS29122CommonDataYamlcomponentsschemasLink
        :param traffic_filters: The traffic_filters of this TrafficInfluSub.  # noqa: E501
        :type traffic_filters: List[TS29122CommonDataYamlcomponentsschemasFlowInfo]
        :param eth_traffic_filters: The eth_traffic_filters of this TrafficInfluSub.  # noqa: E501
        :type eth_traffic_filters: List[TS29514NpcfPolicyAuthorizationYamlcomponentsschemasEthFlowDescription]
        :param traffic_routes: The traffic_routes of this TrafficInfluSub.  # noqa: E501
        :type traffic_routes: List[TS29571CommonDataYamlcomponentsschemasRouteToLocation]
        :param sfc_id_dl: The sfc_id_dl of this TrafficInfluSub.  # noqa: E501
        :type sfc_id_dl: str
        :param sfc_id_ul: The sfc_id_ul of this TrafficInfluSub.  # noqa: E501
        :type sfc_id_ul: str
        :param metadata: The metadata of this TrafficInfluSub.  # noqa: E501
        :type metadata: TS29571CommonDataYamlcomponentsschemasMetadata
        :param tfc_corr_ind: The tfc_corr_ind of this TrafficInfluSub.  # noqa: E501
        :type tfc_corr_ind: bool
        :param temp_validities: The temp_validities of this TrafficInfluSub.  # noqa: E501
        :type temp_validities: List[TS29514NpcfPolicyAuthorizationYamlcomponentsschemasTemporalValidity]
        :param valid_geo_zone_ids: The valid_geo_zone_ids of this TrafficInfluSub.  # noqa: E501
        :type valid_geo_zone_ids: List[str]
        :param geo_areas: The geo_areas of this TrafficInfluSub.  # noqa: E501
        :type geo_areas: List[TS29522AMPolicyAuthorizationYamlcomponentsschemasGeographicalArea]
        :param af_ack_ind: The af_ack_ind of this TrafficInfluSub.  # noqa: E501
        :type af_ack_ind: bool
        :param addr_preser_ind: The addr_preser_ind of this TrafficInfluSub.  # noqa: E501
        :type addr_preser_ind: bool
        :param sim_conn_ind: The sim_conn_ind of this TrafficInfluSub.  # noqa: E501
        :type sim_conn_ind: bool
        :param sim_conn_term: The sim_conn_term of this TrafficInfluSub.  # noqa: E501
        :type sim_conn_term: DurationSec
        :param max_allowed_up_lat: The max_allowed_up_lat of this TrafficInfluSub.  # noqa: E501
        :type max_allowed_up_lat: Uinteger
        :param eas_ip_replace_infos: The eas_ip_replace_infos of this TrafficInfluSub.  # noqa: E501
        :type eas_ip_replace_infos: List[TS29571CommonDataYamlcomponentsschemasEasIpReplacementInfo]
        :param eas_redis_ind: The eas_redis_ind of this TrafficInfluSub.  # noqa: E501
        :type eas_redis_ind: bool
        :param event_req: The event_req of this TrafficInfluSub.  # noqa: E501
        :type event_req: TS29523NpcfEventExposureYamlcomponentsschemasReportingInformation
        :param event_reports: The event_reports of this TrafficInfluSub.  # noqa: E501
        :type event_reports: List[EventNotification]
        :param cand_dnai_ind: The cand_dnai_ind of this TrafficInfluSub.  # noqa: E501
        :type cand_dnai_ind: bool
        :param tfc_corre_info: The tfc_corre_info of this TrafficInfluSub.  # noqa: E501
        :type tfc_corre_info: TrafficCorrelationInfo
        :param supp_feat: The supp_feat of this TrafficInfluSub.  # noqa: E501
        :type supp_feat: TS29571CommonDataYamlcomponentsschemasSupportedFeatures
        """
        self.swagger_types = {
            'af_service_id': str,
            'af_app_id': str,
            'af_trans_id': str,
            'app_relo_ind': bool,
            'dnn': Dnn,
            'snssai': Snssai,
            'external_group_id': ExternalGroupId,
            'external_group_ids': List[ExternalGroupId],
            'ext_subsc_cats': List[str],
            'any_ue_ind': bool,
            'subscribed_events': List[SubscribedEvent],
            'gpsi': Gpsi,
            'ipv4_addr': Ipv4Addr,
            'ip_domain': str,
            'ipv6_addr': Ipv6Addr,
            'mac_addr': MacAddr48,
            'dnai_chg_type': DnaiChangeType,
            'notification_destination': Link,
            'request_test_notification': bool,
            'websock_notif_config': WebsockNotifConfig,
            '_self': Link,
            'traffic_filters': List[FlowInfo],
            'eth_traffic_filters': List[EthFlowDescription],
            'traffic_routes': List[RouteToLocation],
            'sfc_id_dl': str,
            'sfc_id_ul': str,
            'tfc_corr_ind': bool,
            'temp_validities': List[TemporalValidity],
            'valid_geo_zone_ids': List[str],
            'af_ack_ind': bool,
            'addr_preser_ind': bool,
            'sim_conn_ind': bool,
            'sim_conn_term': DurationSec,
            'max_allowed_up_lat': Uinteger,
            'eas_ip_replace_infos': List[EasIpReplacementInfo],
            'eas_redis_ind': bool,
            'event_req': ReportingInformation,
            'event_reports': List[EventNotification],
            'cand_dnai_ind': bool,
            'tfc_corre_info': TrafficCorrelationInfo,
            'supp_feat': SupportedFeatures
        }

        self.attribute_map = {
            'af_service_id': 'afServiceId',
            'af_app_id': 'afAppId',
            'af_trans_id': 'afTransId',
            'app_relo_ind': 'appReloInd',
            'dnn': 'dnn',
            'snssai': 'snssai',
            'external_group_id': 'externalGroupId',
            'external_group_ids': 'externalGroupIds',
            'ext_subsc_cats': 'extSubscCats',
            'any_ue_ind': 'anyUeInd',
            'subscribed_events': 'subscribedEvents',
            'gpsi': 'gpsi',
            'ipv4_addr': 'ipv4Addr',
            'ip_domain': 'ipDomain',
            'ipv6_addr': 'ipv6Addr',
            'mac_addr': 'macAddr',
            'dnai_chg_type': 'dnaiChgType',
            'notification_destination': 'notificationDestination',
            'request_test_notification': 'requestTestNotification',
            'websock_notif_config': 'websockNotifConfig',
            '_self': 'self',
            'traffic_filters': 'trafficFilters',
            'eth_traffic_filters': 'ethTrafficFilters',
            'traffic_routes': 'trafficRoutes',
            'sfc_id_dl': 'sfcIdDl',
            'sfc_id_ul': 'sfcIdUl',
            'tfc_corr_ind': 'tfcCorrInd',
            'temp_validities': 'tempValidities',
            'valid_geo_zone_ids': 'validGeoZoneIds',
            'af_ack_ind': 'afAckInd',
            'addr_preser_ind': 'addrPreserInd',
            'sim_conn_ind': 'simConnInd',
            'sim_conn_term': 'simConnTerm',
            'max_allowed_up_lat': 'maxAllowedUpLat',
            'eas_ip_replace_infos': 'easIpReplaceInfos',
            'eas_redis_ind': 'easRedisInd',
            'event_req': 'eventReq',
            'event_reports': 'eventReports',
            'cand_dnai_ind': 'candDnaiInd',
            'tfc_corre_info': 'tfcCorreInfo',
            'supp_feat': 'suppFeat'
        }
        self._af_service_id = af_service_id
        self._af_app_id = af_app_id
        self._af_trans_id = af_trans_id
        self._app_relo_ind = app_relo_ind
        self._dnn = dnn
        self._snssai = snssai
        self._external_group_id = external_group_id
        self._external_group_ids = external_group_ids
        self._ext_subsc_cats = ext_subsc_cats
        self._any_ue_ind = any_ue_ind
        self._subscribed_events = subscribed_events
        self._gpsi = gpsi
        self._ipv4_addr = ipv4_addr
        self._ip_domain = ip_domain
        self._ipv6_addr = ipv6_addr
        self._mac_addr = mac_addr
        self._dnai_chg_type = dnai_chg_type
        self._notification_destination = notification_destination
        self._request_test_notification = request_test_notification
        self._websock_notif_config = websock_notif_config
        self.__self = _self
        self._traffic_filters = traffic_filters
        self._eth_traffic_filters = eth_traffic_filters
        self._traffic_routes = traffic_routes
        self._sfc_id_dl = sfc_id_dl
        self._sfc_id_ul = sfc_id_ul
        self._tfc_corr_ind = tfc_corr_ind
        self._temp_validities = temp_validities
        self._valid_geo_zone_ids = valid_geo_zone_ids
        self._af_ack_ind = af_ack_ind
        self._addr_preser_ind = addr_preser_ind
        self._sim_conn_ind = sim_conn_ind
        self._sim_conn_term = sim_conn_term
        self._max_allowed_up_lat = max_allowed_up_lat
        self._eas_ip_replace_infos = eas_ip_replace_infos
        self._eas_redis_ind = eas_redis_ind
        self._event_req = event_req
        self._event_reports = event_reports
        self._cand_dnai_ind = cand_dnai_ind
        self._tfc_corre_info = tfc_corre_info
        self._supp_feat = supp_feat

    @classmethod
    def from_dict(cls, dikt) -> 'TrafficInfluSub':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrafficInfluSub of this TrafficInfluSub.  # noqa: E501
        :rtype: TrafficInfluSub
        """
        return util.deserialize_model(dikt, cls)

    @property
    def af_service_id(self) -> str:
        """Gets the af_service_id of this TrafficInfluSub.

        Identifies a service on behalf of which the AF is issuing the request.  # noqa: E501

        :return: The af_service_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._af_service_id

    @af_service_id.setter
    def af_service_id(self, af_service_id: str):
        """Sets the af_service_id of this TrafficInfluSub.

        Identifies a service on behalf of which the AF is issuing the request.  # noqa: E501

        :param af_service_id: The af_service_id of this TrafficInfluSub.
        :type af_service_id: str
        """

        self._af_service_id = af_service_id

    @property
    def af_app_id(self) -> str:
        """Gets the af_app_id of this TrafficInfluSub.

        Identifies an application.  # noqa: E501

        :return: The af_app_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._af_app_id

    @af_app_id.setter
    def af_app_id(self, af_app_id: str):
        """Sets the af_app_id of this TrafficInfluSub.

        Identifies an application.  # noqa: E501

        :param af_app_id: The af_app_id of this TrafficInfluSub.
        :type af_app_id: str
        """

        self._af_app_id = af_app_id

    @property
    def af_trans_id(self) -> str:
        """Gets the af_trans_id of this TrafficInfluSub.

        Identifies an NEF Northbound interface transaction, generated by the AF.  # noqa: E501

        :return: The af_trans_id of this TrafficInfluSub.
        :rtype: str
        """
        return self._af_trans_id

    @af_trans_id.setter
    def af_trans_id(self, af_trans_id: str):
        """Sets the af_trans_id of this TrafficInfluSub.

        Identifies an NEF Northbound interface transaction, generated by the AF.  # noqa: E501

        :param af_trans_id: The af_trans_id of this TrafficInfluSub.
        :type af_trans_id: str
        """

        self._af_trans_id = af_trans_id

    @property
    def app_relo_ind(self) -> bool:
        """Gets the app_relo_ind of this TrafficInfluSub.

        Identifies whether an application can be relocated once a location of the application has been selected.   # noqa: E501

        :return: The app_relo_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._app_relo_ind

    @app_relo_ind.setter
    def app_relo_ind(self, app_relo_ind: bool):
        """Sets the app_relo_ind of this TrafficInfluSub.

        Identifies whether an application can be relocated once a location of the application has been selected.   # noqa: E501

        :param app_relo_ind: The app_relo_ind of this TrafficInfluSub.
        :type app_relo_ind: bool
        """

        self._app_relo_ind = app_relo_ind

    @property
    def dnn(self) -> Dnn:
        """Gets the dnn of this TrafficInfluSub.


        :return: The dnn of this TrafficInfluSub.
        :rtype: TS29571CommonDataYamlcomponentsschemasDnn
        """
        return self._dnn

    @dnn.setter
    def dnn(self, dnn: Dnn):
        """Sets the dnn of this TrafficInfluSub.


        :param dnn: The dnn of this TrafficInfluSub.
        :type dnn: TS29571CommonDataYamlcomponentsschemasDnn
        """

        self._dnn = dnn

    @property
    def snssai(self) -> Snssai:
        """Gets the snssai of this TrafficInfluSub.


        :return: The snssai of this TrafficInfluSub.
        :rtype: TS29571CommonDataYamlcomponentsschemasSnssai
        """
        return self._snssai

    @snssai.setter
    def snssai(self, snssai: Snssai):
        """Sets the snssai of this TrafficInfluSub.


        :param snssai: The snssai of this TrafficInfluSub.
        :type snssai: TS29571CommonDataYamlcomponentsschemasSnssai
        """

        self._snssai = snssai

    @property
    def external_group_id(self) -> ExternalGroupId:
        """Gets the external_group_id of this TrafficInfluSub.


        :return: The external_group_id of this TrafficInfluSub.
        :rtype: TS29122CommonDataYamlcomponentsschemasExternalGroupId
        """
        return self._external_group_id

    @external_group_id.setter
    def external_group_id(self, external_group_id: ExternalGroupId):
        """Sets the external_group_id of this TrafficInfluSub.


        :param external_group_id: The external_group_id of this TrafficInfluSub.
        :type external_group_id: TS29122CommonDataYamlcomponentsschemasExternalGroupId
        """

        self._external_group_id = external_group_id

    @property
    def external_group_ids(self) -> List[ExternalGroupId]:
        """Gets the external_group_ids of this TrafficInfluSub.

        Each element identifies a group of users.  # noqa: E501

        :return: The external_group_ids of this TrafficInfluSub.
        :rtype: List[TS29122CommonDataYamlcomponentsschemasExternalGroupId]
        """
        return self._external_group_ids

    @external_group_ids.setter
    def external_group_ids(self, external_group_ids: List[ExternalGroupId]):
        """Sets the external_group_ids of this TrafficInfluSub.

        Each element identifies a group of users.  # noqa: E501

        :param external_group_ids: The external_group_ids of this TrafficInfluSub.
        :type external_group_ids: List[TS29122CommonDataYamlcomponentsschemasExternalGroupId]
        """

        self._external_group_ids = external_group_ids

    @property
    def ext_subsc_cats(self) -> List[str]:
        """Gets the ext_subsc_cats of this TrafficInfluSub.


        :return: The ext_subsc_cats of this TrafficInfluSub.
        :rtype: List[str]
        """
        return self._ext_subsc_cats

    @ext_subsc_cats.setter
    def ext_subsc_cats(self, ext_subsc_cats: List[str]):
        """Sets the ext_subsc_cats of this TrafficInfluSub.


        :param ext_subsc_cats: The ext_subsc_cats of this TrafficInfluSub.
        :type ext_subsc_cats: List[str]
        """

        self._ext_subsc_cats = ext_subsc_cats

    @property
    def any_ue_ind(self) -> bool:
        """Gets the any_ue_ind of this TrafficInfluSub.

        Identifies whether the AF request applies to any UE. This attribute shall set to \"true\" if applicable for any UE, otherwise, set to \"false\".   # noqa: E501

        :return: The any_ue_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._any_ue_ind

    @any_ue_ind.setter
    def any_ue_ind(self, any_ue_ind: bool):
        """Sets the any_ue_ind of this TrafficInfluSub.

        Identifies whether the AF request applies to any UE. This attribute shall set to \"true\" if applicable for any UE, otherwise, set to \"false\".   # noqa: E501

        :param any_ue_ind: The any_ue_ind of this TrafficInfluSub.
        :type any_ue_ind: bool
        """

        self._any_ue_ind = any_ue_ind

    @property
    def subscribed_events(self) -> List[SubscribedEvent]:
        """Gets the subscribed_events of this TrafficInfluSub.

        Identifies the requirement to be notified of the event(s).  # noqa: E501

        :return: The subscribed_events of this TrafficInfluSub.
        :rtype: List[SubscribedEvent]
        """
        return self._subscribed_events

    @subscribed_events.setter
    def subscribed_events(self, subscribed_events: List[SubscribedEvent]):
        """Sets the subscribed_events of this TrafficInfluSub.

        Identifies the requirement to be notified of the event(s).  # noqa: E501

        :param subscribed_events: The subscribed_events of this TrafficInfluSub.
        :type subscribed_events: List[SubscribedEvent]
        """

        self._subscribed_events = subscribed_events

    @property
    def gpsi(self) -> Gpsi:
        """Gets the gpsi of this TrafficInfluSub.


        :return: The gpsi of this TrafficInfluSub.
        :rtype: TS29571CommonDataYamlcomponentsschemasGpsi
        """
        return self._gpsi

    @gpsi.setter
    def gpsi(self, gpsi: Gpsi):
        """Sets the gpsi of this TrafficInfluSub.


        :param gpsi: The gpsi of this TrafficInfluSub.
        :type gpsi: TS29571CommonDataYamlcomponentsschemasGpsi
        """

        self._gpsi = gpsi

    @property
    def ipv4_addr(self) -> Ipv4Addr:
        """Gets the ipv4_addr of this TrafficInfluSub.


        :return: The ipv4_addr of this TrafficInfluSub.
        :rtype: TS29122CommonDataYamlcomponentsschemasIpv4Addr
        """
        return self._ipv4_addr

    @ipv4_addr.setter
    def ipv4_addr(self, ipv4_addr: Ipv4Addr):
        """Sets the ipv4_addr of this TrafficInfluSub.


        :param ipv4_addr: The ipv4_addr of this TrafficInfluSub.
        :type ipv4_addr: TS29122CommonDataYamlcomponentsschemasIpv4Addr
        """

        self._ipv4_addr = ipv4_addr

    @property
    def ip_domain(self) -> str:
        """Gets the ip_domain of this TrafficInfluSub.


        :return: The ip_domain of this TrafficInfluSub.
        :rtype: str
        """
        return self._ip_domain

    @ip_domain.setter
    def ip_domain(self, ip_domain: str):
        """Sets the ip_domain of this TrafficInfluSub.


        :param ip_domain: The ip_domain of this TrafficInfluSub.
        :type ip_domain: str
        """

        self._ip_domain = ip_domain

    @property
    def ipv6_addr(self) -> Ipv6Addr:
        """Gets the ipv6_addr of this TrafficInfluSub.


        :return: The ipv6_addr of this TrafficInfluSub.
        :rtype: TS29122CommonDataYamlcomponentsschemasIpv6Addr
        """
        return self._ipv6_addr

    @ipv6_addr.setter
    def ipv6_addr(self, ipv6_addr: Ipv6Addr):
        """Sets the ipv6_addr of this TrafficInfluSub.


        :param ipv6_addr: The ipv6_addr of this TrafficInfluSub.
        :type ipv6_addr: TS29122CommonDataYamlcomponentsschemasIpv6Addr
        """

        self._ipv6_addr = ipv6_addr

    @property
    def mac_addr(self) -> MacAddr48:
        """Gets the mac_addr of this TrafficInfluSub.


        :return: The mac_addr of this TrafficInfluSub.
        :rtype: TS29571CommonDataYamlcomponentsschemasMacAddr48
        """
        return self._mac_addr

    @mac_addr.setter
    def mac_addr(self, mac_addr: MacAddr48):
        """Sets the mac_addr of this TrafficInfluSub.


        :param mac_addr: The mac_addr of this TrafficInfluSub.
        :type mac_addr: TS29571CommonDataYamlcomponentsschemasMacAddr48
        """

        self._mac_addr = mac_addr

    @property
    def dnai_chg_type(self) -> DnaiChangeType:
        """Gets the dnai_chg_type of this TrafficInfluSub.


        :return: The dnai_chg_type of this TrafficInfluSub.
        :rtype: TS29571CommonDataYamlcomponentsschemasDnaiChangeType
        """
        return self._dnai_chg_type

    @dnai_chg_type.setter
    def dnai_chg_type(self, dnai_chg_type: DnaiChangeType):
        """Sets the dnai_chg_type of this TrafficInfluSub.


        :param dnai_chg_type: The dnai_chg_type of this TrafficInfluSub.
        :type dnai_chg_type: TS29571CommonDataYamlcomponentsschemasDnaiChangeType
        """

        self._dnai_chg_type = dnai_chg_type

    @property
    def notification_destination(self) -> Link:
        """Gets the notification_destination of this TrafficInfluSub.


        :return: The notification_destination of this TrafficInfluSub.
        :rtype: TS29122CommonDataYamlcomponentsschemasLink
        """
        return self._notification_destination

    @notification_destination.setter
    def notification_destination(self, notification_destination: Link):
        """Sets the notification_destination of this TrafficInfluSub.


        :param notification_destination: The notification_destination of this TrafficInfluSub.
        :type notification_destination: TS29122CommonDataYamlcomponentsschemasLink
        """

        self._notification_destination = notification_destination

    @property
    def request_test_notification(self) -> bool:
        """Gets the request_test_notification of this TrafficInfluSub.

        Set to true by the SCS/AS to request the NEF to send a test notification as defined in clause 5.2.5.3. Set to false or omitted otherwise.   # noqa: E501

        :return: The request_test_notification of this TrafficInfluSub.
        :rtype: bool
        """
        return self._request_test_notification

    @request_test_notification.setter
    def request_test_notification(self, request_test_notification: bool):
        """Sets the request_test_notification of this TrafficInfluSub.

        Set to true by the SCS/AS to request the NEF to send a test notification as defined in clause 5.2.5.3. Set to false or omitted otherwise.   # noqa: E501

        :param request_test_notification: The request_test_notification of this TrafficInfluSub.
        :type request_test_notification: bool
        """

        self._request_test_notification = request_test_notification

    @property
    def websock_notif_config(self) -> WebsockNotifConfig:
        """Gets the websock_notif_config of this TrafficInfluSub.


        :return: The websock_notif_config of this TrafficInfluSub.
        :rtype: TS29122CommonDataYamlcomponentsschemasWebsockNotifConfig
        """
        return self._websock_notif_config

    @websock_notif_config.setter
    def websock_notif_config(self, websock_notif_config: WebsockNotifConfig):
        """Sets the websock_notif_config of this TrafficInfluSub.


        :param websock_notif_config: The websock_notif_config of this TrafficInfluSub.
        :type websock_notif_config: TS29122CommonDataYamlcomponentsschemasWebsockNotifConfig
        """

        self._websock_notif_config = websock_notif_config

    @property
    def _self(self) -> Link:
        """Gets the _self of this TrafficInfluSub.


        :return: The _self of this TrafficInfluSub.
        :rtype: TS29122CommonDataYamlcomponentsschemasLink
        """
        return self.__self

    @_self.setter
    def _self(self, _self: Link):
        """Sets the _self of this TrafficInfluSub.


        :param _self: The _self of this TrafficInfluSub.
        :type _self: TS29122CommonDataYamlcomponentsschemasLink
        """

        self.__self = _self

    @property
    def traffic_filters(self) -> List[FlowInfo]:
        """Gets the traffic_filters of this TrafficInfluSub.

        Identifies IP packet filters.  # noqa: E501

        :return: The traffic_filters of this TrafficInfluSub.
        :rtype: List[TS29122CommonDataYamlcomponentsschemasFlowInfo]
        """
        return self._traffic_filters

    @traffic_filters.setter
    def traffic_filters(self, traffic_filters: List[FlowInfo]):
        """Sets the traffic_filters of this TrafficInfluSub.

        Identifies IP packet filters.  # noqa: E501

        :param traffic_filters: The traffic_filters of this TrafficInfluSub.
        :type traffic_filters: List[TS29122CommonDataYamlcomponentsschemasFlowInfo]
        """

        self._traffic_filters = traffic_filters

    @property
    def eth_traffic_filters(self) -> List[EthFlowDescription]:
        """Gets the eth_traffic_filters of this TrafficInfluSub.

        Identifies Ethernet packet filters.  # noqa: E501

        :return: The eth_traffic_filters of this TrafficInfluSub.
        :rtype: List[TS29514NpcfPolicyAuthorizationYamlcomponentsschemasEthFlowDescription]
        """
        return self._eth_traffic_filters

    @eth_traffic_filters.setter
    def eth_traffic_filters(self, eth_traffic_filters: List[EthFlowDescription]):
        """Sets the eth_traffic_filters of this TrafficInfluSub.

        Identifies Ethernet packet filters.  # noqa: E501

        :param eth_traffic_filters: The eth_traffic_filters of this TrafficInfluSub.
        :type eth_traffic_filters: List[TS29514NpcfPolicyAuthorizationYamlcomponentsschemasEthFlowDescription]
        """

        self._eth_traffic_filters = eth_traffic_filters

    @property
    def traffic_routes(self) -> List[RouteToLocation]:
        """Gets the traffic_routes of this TrafficInfluSub.

        Identifies the N6 traffic routing requirement.  # noqa: E501

        :return: The traffic_routes of this TrafficInfluSub.
        :rtype: List[TS29571CommonDataYamlcomponentsschemasRouteToLocation]
        """
        return self._traffic_routes

    @traffic_routes.setter
    def traffic_routes(self, traffic_routes: List[RouteToLocation]):
        """Sets the traffic_routes of this TrafficInfluSub.

        Identifies the N6 traffic routing requirement.  # noqa: E501

        :param traffic_routes: The traffic_routes of this TrafficInfluSub.
        :type traffic_routes: List[TS29571CommonDataYamlcomponentsschemasRouteToLocation]
        """

        self._traffic_routes = traffic_routes

    @property
    def sfc_id_dl(self) -> str:
        """Gets the sfc_id_dl of this TrafficInfluSub.

        Reference to a pre-configured steering of user traffic to service function chain in downlink.   # noqa: E501

        :return: The sfc_id_dl of this TrafficInfluSub.
        :rtype: str
        """
        return self._sfc_id_dl

    @sfc_id_dl.setter
    def sfc_id_dl(self, sfc_id_dl: str):
        """Sets the sfc_id_dl of this TrafficInfluSub.

        Reference to a pre-configured steering of user traffic to service function chain in downlink.   # noqa: E501

        :param sfc_id_dl: The sfc_id_dl of this TrafficInfluSub.
        :type sfc_id_dl: str
        """

        self._sfc_id_dl = sfc_id_dl

    @property
    def sfc_id_ul(self) -> str:
        """Gets the sfc_id_ul of this TrafficInfluSub.

        Reference to a pre-configured steering of user traffic to service function chain in uplink.   # noqa: E501

        :return: The sfc_id_ul of this TrafficInfluSub.
        :rtype: str
        """
        return self._sfc_id_ul

    @sfc_id_ul.setter
    def sfc_id_ul(self, sfc_id_ul: str):
        """Sets the sfc_id_ul of this TrafficInfluSub.

        Reference to a pre-configured steering of user traffic to service function chain in uplink.   # noqa: E501

        :param sfc_id_ul: The sfc_id_ul of this TrafficInfluSub.
        :type sfc_id_ul: str
        """

        self._sfc_id_ul = sfc_id_ul

    @property
    def tfc_corr_ind(self) -> bool:
        """Gets the tfc_corr_ind of this TrafficInfluSub.


        :return: The tfc_corr_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._tfc_corr_ind

    @tfc_corr_ind.setter
    def tfc_corr_ind(self, tfc_corr_ind: bool):
        """Sets the tfc_corr_ind of this TrafficInfluSub.


        :param tfc_corr_ind: The tfc_corr_ind of this TrafficInfluSub.
        :type tfc_corr_ind: bool
        """

        self._tfc_corr_ind = tfc_corr_ind

    @property
    def temp_validities(self) -> List[TemporalValidity]:
        """Gets the temp_validities of this TrafficInfluSub.


        :return: The temp_validities of this TrafficInfluSub.
        :rtype: List[TS29514NpcfPolicyAuthorizationYamlcomponentsschemasTemporalValidity]
        """
        return self._temp_validities

    @temp_validities.setter
    def temp_validities(self, temp_validities: List[TemporalValidity]):
        """Sets the temp_validities of this TrafficInfluSub.


        :param temp_validities: The temp_validities of this TrafficInfluSub.
        :type temp_validities: List[TS29514NpcfPolicyAuthorizationYamlcomponentsschemasTemporalValidity]
        """

        self._temp_validities = temp_validities

    @property
    def valid_geo_zone_ids(self) -> List[str]:
        """Gets the valid_geo_zone_ids of this TrafficInfluSub.

        Identifies a geographic zone that the AF request applies only to the traffic of UE(s) located in this specific zone.   # noqa: E501

        :return: The valid_geo_zone_ids of this TrafficInfluSub.
        :rtype: List[str]
        """
        return self._valid_geo_zone_ids

    @valid_geo_zone_ids.setter
    def valid_geo_zone_ids(self, valid_geo_zone_ids: List[str]):
        """Sets the valid_geo_zone_ids of this TrafficInfluSub.

        Identifies a geographic zone that the AF request applies only to the traffic of UE(s) located in this specific zone.   # noqa: E501

        :param valid_geo_zone_ids: The valid_geo_zone_ids of this TrafficInfluSub.
        :type valid_geo_zone_ids: List[str]
        """

        self._valid_geo_zone_ids = valid_geo_zone_ids

    @property
    def af_ack_ind(self) -> bool:
        """Gets the af_ack_ind of this TrafficInfluSub.


        :return: The af_ack_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._af_ack_ind

    @af_ack_ind.setter
    def af_ack_ind(self, af_ack_ind: bool):
        """Sets the af_ack_ind of this TrafficInfluSub.


        :param af_ack_ind: The af_ack_ind of this TrafficInfluSub.
        :type af_ack_ind: bool
        """

        self._af_ack_ind = af_ack_ind

    @property
    def addr_preser_ind(self) -> bool:
        """Gets the addr_preser_ind of this TrafficInfluSub.


        :return: The addr_preser_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._addr_preser_ind

    @addr_preser_ind.setter
    def addr_preser_ind(self, addr_preser_ind: bool):
        """Sets the addr_preser_ind of this TrafficInfluSub.


        :param addr_preser_ind: The addr_preser_ind of this TrafficInfluSub.
        :type addr_preser_ind: bool
        """

        self._addr_preser_ind = addr_preser_ind

    @property
    def sim_conn_ind(self) -> bool:
        """Gets the sim_conn_ind of this TrafficInfluSub.

        Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.   # noqa: E501

        :return: The sim_conn_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._sim_conn_ind

    @sim_conn_ind.setter
    def sim_conn_ind(self, sim_conn_ind: bool):
        """Sets the sim_conn_ind of this TrafficInfluSub.

        Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.   # noqa: E501

        :param sim_conn_ind: The sim_conn_ind of this TrafficInfluSub.
        :type sim_conn_ind: bool
        """

        self._sim_conn_ind = sim_conn_ind

    @property
    def sim_conn_term(self) -> DurationSec:
        """Gets the sim_conn_term of this TrafficInfluSub.


        :return: The sim_conn_term of this TrafficInfluSub.
        :rtype: DurationSec
        """
        return self._sim_conn_term

    @sim_conn_term.setter
    def sim_conn_term(self, sim_conn_term: DurationSec):
        """Sets the sim_conn_term of this TrafficInfluSub.


        :param sim_conn_term: The sim_conn_term of this TrafficInfluSub.
        :type sim_conn_term: DurationSec
        """

        self._sim_conn_term = sim_conn_term

    @property
    def max_allowed_up_lat(self) -> Uinteger:
        """Gets the max_allowed_up_lat of this TrafficInfluSub.


        :return: The max_allowed_up_lat of this TrafficInfluSub.
        :rtype: Uinteger
        """
        return self._max_allowed_up_lat

    @max_allowed_up_lat.setter
    def max_allowed_up_lat(self, max_allowed_up_lat: Uinteger):
        """Sets the max_allowed_up_lat of this TrafficInfluSub.


        :param max_allowed_up_lat: The max_allowed_up_lat of this TrafficInfluSub.
        :type max_allowed_up_lat: Uinteger
        """

        self._max_allowed_up_lat = max_allowed_up_lat

    @property
    def eas_ip_replace_infos(self) -> List[EasIpReplacementInfo]:
        """Gets the eas_ip_replace_infos of this TrafficInfluSub.

        Contains EAS IP replacement information.  # noqa: E501

        :return: The eas_ip_replace_infos of this TrafficInfluSub.
        :rtype: List[TS29571CommonDataYamlcomponentsschemasEasIpReplacementInfo]
        """
        return self._eas_ip_replace_infos

    @eas_ip_replace_infos.setter
    def eas_ip_replace_infos(self, eas_ip_replace_infos: List[EasIpReplacementInfo]):
        """Sets the eas_ip_replace_infos of this TrafficInfluSub.

        Contains EAS IP replacement information.  # noqa: E501

        :param eas_ip_replace_infos: The eas_ip_replace_infos of this TrafficInfluSub.
        :type eas_ip_replace_infos: List[TS29571CommonDataYamlcomponentsschemasEasIpReplacementInfo]
        """

        self._eas_ip_replace_infos = eas_ip_replace_infos

    @property
    def eas_redis_ind(self) -> bool:
        """Gets the eas_redis_ind of this TrafficInfluSub.

        Indicates the EAS rediscovery is required for the application if it is included and set to \"true\".   # noqa: E501

        :return: The eas_redis_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._eas_redis_ind

    @eas_redis_ind.setter
    def eas_redis_ind(self, eas_redis_ind: bool):
        """Sets the eas_redis_ind of this TrafficInfluSub.

        Indicates the EAS rediscovery is required for the application if it is included and set to \"true\".   # noqa: E501

        :param eas_redis_ind: The eas_redis_ind of this TrafficInfluSub.
        :type eas_redis_ind: bool
        """

        self._eas_redis_ind = eas_redis_ind

    @property
    def event_req(self) -> ReportingInformation:
        """Gets the event_req of this TrafficInfluSub.


        :return: The event_req of this TrafficInfluSub.
        :rtype: TS29523NpcfEventExposureYamlcomponentsschemasReportingInformation
        """
        return self._event_req

    @event_req.setter
    def event_req(self, event_req: ReportingInformation):
        """Sets the event_req of this TrafficInfluSub.


        :param event_req: The event_req of this TrafficInfluSub.
        :type event_req: TS29523NpcfEventExposureYamlcomponentsschemasReportingInformation
        """

        self._event_req = event_req

    @property
    def event_reports(self) -> List[EventNotification]:
        """Gets the event_reports of this TrafficInfluSub.


        :return: The event_reports of this TrafficInfluSub.
        :rtype: List[EventNotification]
        """
        return self._event_reports

    @event_reports.setter
    def event_reports(self, event_reports: List[EventNotification]):
        """Sets the event_reports of this TrafficInfluSub.


        :param event_reports: The event_reports of this TrafficInfluSub.
        :type event_reports: List[EventNotification]
        """

        self._event_reports = event_reports

    @property
    def cand_dnai_ind(self) -> bool:
        """Gets the cand_dnai_ind of this TrafficInfluSub.

        Indication of reporting candidate DNAI(s). If it is included and set to \"true\", the candidate DNAI(s) for the PDU session need to be reported. Otherwise set to \"false\" or omitted.   # noqa: E501

        :return: The cand_dnai_ind of this TrafficInfluSub.
        :rtype: bool
        """
        return self._cand_dnai_ind

    @cand_dnai_ind.setter
    def cand_dnai_ind(self, cand_dnai_ind: bool):
        """Sets the cand_dnai_ind of this TrafficInfluSub.

        Indication of reporting candidate DNAI(s). If it is included and set to \"true\", the candidate DNAI(s) for the PDU session need to be reported. Otherwise set to \"false\" or omitted.   # noqa: E501

        :param cand_dnai_ind: The cand_dnai_ind of this TrafficInfluSub.
        :type cand_dnai_ind: bool
        """

        self._cand_dnai_ind = cand_dnai_ind

    @property
    def tfc_corre_info(self) -> TrafficCorrelationInfo:
        """Gets the tfc_corre_info of this TrafficInfluSub.


        :return: The tfc_corre_info of this TrafficInfluSub.
        :rtype: TrafficCorrelationInfo
        """
        return self._tfc_corre_info

    @tfc_corre_info.setter
    def tfc_corre_info(self, tfc_corre_info: TrafficCorrelationInfo):
        """Sets the tfc_corre_info of this TrafficInfluSub.


        :param tfc_corre_info: The tfc_corre_info of this TrafficInfluSub.
        :type tfc_corre_info: TrafficCorrelationInfo
        """

        self._tfc_corre_info = tfc_corre_info

    @property
    def supp_feat(self) -> SupportedFeatures:
        """Gets the supp_feat of this TrafficInfluSub.


        :return: The supp_feat of this TrafficInfluSub.
        :rtype: TS29571CommonDataYamlcomponentsschemasSupportedFeatures
        """
        return self._supp_feat

    @supp_feat.setter
    def supp_feat(self, supp_feat: SupportedFeatures):
        """Sets the supp_feat of this TrafficInfluSub.


        :param supp_feat: The supp_feat of this TrafficInfluSub.
        :type supp_feat: TS29571CommonDataYamlcomponentsschemasSupportedFeatures
        """

        self._supp_feat = supp_feat
