# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.identity_range import IdentityRange  # noqa: F401,E501
from models.supi_range import SupiRange  # noqa: F401,E501
import util


class UdsfInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, group_id: str=None, supi_ranges: List[SupiRange]=None, storage_id_ranges: Dict[str, List[IdentityRange]]=None):  # noqa: E501
        """UdsfInfo - a model defined in Swagger

        :param group_id: The group_id of this UdsfInfo.  # noqa: E501
        :type group_id: str
        :param supi_ranges: The supi_ranges of this UdsfInfo.  # noqa: E501
        :type supi_ranges: List[SupiRange]
        :param storage_id_ranges: The storage_id_ranges of this UdsfInfo.  # noqa: E501
        :type storage_id_ranges: Dict[str, List[IdentityRange]]
        """
        self.openapi_types = {
            'group_id': str,
            'supi_ranges': List[SupiRange],
            'storage_id_ranges': Dict[str, List[IdentityRange]]
        }

        self.attribute_map = {
            'group_id': 'groupId',
            'supi_ranges': 'supiRanges',
            'storage_id_ranges': 'storageIdRanges'
        }
        self._group_id = group_id
        self._supi_ranges = supi_ranges
        self._storage_id_ranges = storage_id_ranges

    @classmethod
    def from_dict(cls, dikt) -> 'UdsfInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UdsfInfo of this UdsfInfo.  # noqa: E501
        :rtype: UdsfInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_id(self) -> str:
        """Gets the group_id of this UdsfInfo.

        Identifier of a group of NFs.  # noqa: E501

        :return: The group_id of this UdsfInfo.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id: str):
        """Sets the group_id of this UdsfInfo.

        Identifier of a group of NFs.  # noqa: E501

        :param group_id: The group_id of this UdsfInfo.
        :type group_id: str
        """

        self._group_id = group_id

    @property
    def supi_ranges(self) -> List[SupiRange]:
        """Gets the supi_ranges of this UdsfInfo.


        :return: The supi_ranges of this UdsfInfo.
        :rtype: List[SupiRange]
        """
        return self._supi_ranges

    @supi_ranges.setter
    def supi_ranges(self, supi_ranges: List[SupiRange]):
        """Sets the supi_ranges of this UdsfInfo.


        :param supi_ranges: The supi_ranges of this UdsfInfo.
        :type supi_ranges: List[SupiRange]
        """

        self._supi_ranges = supi_ranges

    @property
    def storage_id_ranges(self) -> Dict[str, List[IdentityRange]]:
        """Gets the storage_id_ranges of this UdsfInfo.

        A map (list of key-value pairs) where realmId serves as key and each value in the map is an array of IdentityRanges. Each IdentityRange is a range of storageIds.  # noqa: E501

        :return: The storage_id_ranges of this UdsfInfo.
        :rtype: Dict[str, List[IdentityRange]]
        """
        return self._storage_id_ranges

    @storage_id_ranges.setter
    def storage_id_ranges(self, storage_id_ranges: Dict[str, List[IdentityRange]]):
        """Sets the storage_id_ranges of this UdsfInfo.

        A map (list of key-value pairs) where realmId serves as key and each value in the map is an array of IdentityRanges. Each IdentityRange is a range of storageIds.  # noqa: E501

        :param storage_id_ranges: The storage_id_ranges of this UdsfInfo.
        :type storage_id_ranges: Dict[str, List[IdentityRange]]
        """

        self._storage_id_ranges = storage_id_ranges
