# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.ue_communication_info_comms import UeCommunicationInfoComms  # noqa: F401,E501
import re  # noqa: F401,E501
import util


class UeCommunicationInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, supi: str=None, inter_group_id: str=None, app_id: str=None, comms: List[UeCommunicationInfoComms]=None):  # noqa: E501
        """UeCommunicationInfo - a model defined in Swagger

        :param supi: The supi of this UeCommunicationInfo.  # noqa: E501
        :type supi: str
        :param inter_group_id: The inter_group_id of this UeCommunicationInfo.  # noqa: E501
        :type inter_group_id: str
        :param app_id: The app_id of this UeCommunicationInfo.  # noqa: E501
        :type app_id: str
        :param comms: The comms of this UeCommunicationInfo.  # noqa: E501
        :type comms: List[UeCommunicationInfoComms]
        """
        self.swagger_types = {
            'supi': str,
            'inter_group_id': str,
            'app_id': str,
            'comms': List[UeCommunicationInfoComms]
        }

        self.attribute_map = {
            'supi': 'supi',
            'inter_group_id': 'interGroupId',
            'app_id': 'appId',
            'comms': 'comms'
        }
        self._supi = supi
        self._inter_group_id = inter_group_id
        self._app_id = app_id
        self._comms = comms

    @classmethod
    def from_dict(cls, dikt) -> 'UeCommunicationInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UeCommunicationInfo of this UeCommunicationInfo.  # noqa: E501
        :rtype: UeCommunicationInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def supi(self) -> str:
        """Gets the supi of this UeCommunicationInfo.


        :return: The supi of this UeCommunicationInfo.
        :rtype: str
        """
        return self._supi

    @supi.setter
    def supi(self, supi: str):
        """Sets the supi of this UeCommunicationInfo.


        :param supi: The supi of this UeCommunicationInfo.
        :type supi: str
        """

        self._supi = supi

    @property
    def inter_group_id(self) -> str:
        """Gets the inter_group_id of this UeCommunicationInfo.


        :return: The inter_group_id of this UeCommunicationInfo.
        :rtype: str
        """
        return self._inter_group_id

    @inter_group_id.setter
    def inter_group_id(self, inter_group_id: str):
        """Sets the inter_group_id of this UeCommunicationInfo.


        :param inter_group_id: The inter_group_id of this UeCommunicationInfo.
        :type inter_group_id: str
        """

        self._inter_group_id = inter_group_id

    @property
    def app_id(self) -> str:
        """Gets the app_id of this UeCommunicationInfo.


        :return: The app_id of this UeCommunicationInfo.
        :rtype: str
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id: str):
        """Sets the app_id of this UeCommunicationInfo.


        :param app_id: The app_id of this UeCommunicationInfo.
        :type app_id: str
        """

        self._app_id = app_id

    @property
    def comms(self) -> List[UeCommunicationInfoComms]:
        """Gets the comms of this UeCommunicationInfo.


        :return: The comms of this UeCommunicationInfo.
        :rtype: List[UeCommunicationInfoComms]
        """
        return self._comms

    @comms.setter
    def comms(self, comms: List[UeCommunicationInfoComms]):
        """Sets the comms of this UeCommunicationInfo.


        :param comms: The comms of this UeCommunicationInfo.
        :type comms: List[UeCommunicationInfoComms]
        """
        if comms is None:
            raise ValueError("Invalid value for `comms`, must not be `None`")  # noqa: E501

        self._comms = comms
