# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class UePerLocationReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ue_count=None, external_ids=None, msisdns=None, serv_level_dev_ids=None):  # noqa: E501
        """UePerLocationReport - a model defined in OpenAPI

        :param ue_count: The ue_count of this UePerLocationReport.  # noqa: E501
        :type ue_count: int
        :param external_ids: The external_ids of this UePerLocationReport.  # noqa: E501
        :type external_ids: List[str]
        :param msisdns: The msisdns of this UePerLocationReport.  # noqa: E501
        :type msisdns: List[str]
        :param serv_level_dev_ids: The serv_level_dev_ids of this UePerLocationReport.  # noqa: E501
        :type serv_level_dev_ids: List[str]
        """
        self.openapi_types = {
            'ue_count': int,
            'external_ids': List[str],
            'msisdns': List[str],
            'serv_level_dev_ids': List[str]
        }

        self.attribute_map = {
            'ue_count': 'ueCount',
            'external_ids': 'externalIds',
            'msisdns': 'msisdns',
            'serv_level_dev_ids': 'servLevelDevIds'
        }

        self._ue_count = ue_count
        self._external_ids = external_ids
        self._msisdns = msisdns
        self._serv_level_dev_ids = serv_level_dev_ids

    @classmethod
    def from_dict(cls, dikt) -> 'UePerLocationReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UePerLocationReport of this UePerLocationReport.  # noqa: E501
        :rtype: UePerLocationReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ue_count(self):
        """Gets the ue_count of this UePerLocationReport.

        Identifies the number of UEs.  # noqa: E501

        :return: The ue_count of this UePerLocationReport.
        :rtype: int
        """
        return self._ue_count

    @ue_count.setter
    def ue_count(self, ue_count):
        """Sets the ue_count of this UePerLocationReport.

        Identifies the number of UEs.  # noqa: E501

        :param ue_count: The ue_count of this UePerLocationReport.
        :type ue_count: int
        """
        if ue_count is None:
            raise ValueError("Invalid value for `ue_count`, must not be `None`")  # noqa: E501
        if ue_count is not None and ue_count < 0:  # noqa: E501
            raise ValueError("Invalid value for `ue_count`, must be a value greater than or equal to `0`")  # noqa: E501

        self._ue_count = ue_count

    @property
    def external_ids(self):
        """Gets the external_ids of this UePerLocationReport.

        Each element uniquely identifies a user.  # noqa: E501

        :return: The external_ids of this UePerLocationReport.
        :rtype: List[str]
        """
        return self._external_ids

    @external_ids.setter
    def external_ids(self, external_ids):
        """Sets the external_ids of this UePerLocationReport.

        Each element uniquely identifies a user.  # noqa: E501

        :param external_ids: The external_ids of this UePerLocationReport.
        :type external_ids: List[str]
        """
        if external_ids is not None and len(external_ids) < 1:
            raise ValueError("Invalid value for `external_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._external_ids = external_ids

    @property
    def msisdns(self):
        """Gets the msisdns of this UePerLocationReport.

        Each element identifies the MS internal PSTN/ISDN number allocated for a UE.  # noqa: E501

        :return: The msisdns of this UePerLocationReport.
        :rtype: List[str]
        """
        return self._msisdns

    @msisdns.setter
    def msisdns(self, msisdns):
        """Sets the msisdns of this UePerLocationReport.

        Each element identifies the MS internal PSTN/ISDN number allocated for a UE.  # noqa: E501

        :param msisdns: The msisdns of this UePerLocationReport.
        :type msisdns: List[str]
        """
        if msisdns is not None and len(msisdns) < 1:
            raise ValueError("Invalid value for `msisdns`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._msisdns = msisdns

    @property
    def serv_level_dev_ids(self):
        """Gets the serv_level_dev_ids of this UePerLocationReport.

        Each element uniquely identifies a UAV.  # noqa: E501

        :return: The serv_level_dev_ids of this UePerLocationReport.
        :rtype: List[str]
        """
        return self._serv_level_dev_ids

    @serv_level_dev_ids.setter
    def serv_level_dev_ids(self, serv_level_dev_ids):
        """Sets the serv_level_dev_ids of this UePerLocationReport.

        Each element uniquely identifies a UAV.  # noqa: E501

        :param serv_level_dev_ids: The serv_level_dev_ids of this UePerLocationReport.
        :type serv_level_dev_ids: List[str]
        """
        if serv_level_dev_ids is not None and len(serv_level_dev_ids) < 1:
            raise ValueError("Invalid value for `serv_level_dev_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._serv_level_dev_ids = serv_level_dev_ids
