# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class UpfInfoAtsssCapability(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, atsss_ll: bool=False, mptcp: bool=False, rtt_without_pmf: bool=False):  # noqa: E501
        """UpfInfoAtsssCapability - a model defined in Swagger

        :param atsss_ll: The atsss_ll of this UpfInfoAtsssCapability.  # noqa: E501
        :type atsss_ll: bool
        :param mptcp: The mptcp of this UpfInfoAtsssCapability.  # noqa: E501
        :type mptcp: bool
        :param rtt_without_pmf: The rtt_without_pmf of this UpfInfoAtsssCapability.  # noqa: E501
        :type rtt_without_pmf: bool
        """
        self.swagger_types = {
            'atsss_ll': bool,
            'mptcp': bool,
            'rtt_without_pmf': bool
        }

        self.attribute_map = {
            'atsss_ll': 'atsssLL',
            'mptcp': 'mptcp',
            'rtt_without_pmf': 'rttWithoutPmf'
        }
        self._atsss_ll = atsss_ll
        self._mptcp = mptcp
        self._rtt_without_pmf = rtt_without_pmf

    @classmethod
    def from_dict(cls, dikt) -> 'UpfInfoAtsssCapability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpfInfo_atsssCapability of this UpfInfoAtsssCapability.  # noqa: E501
        :rtype: UpfInfoAtsssCapability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def atsss_ll(self) -> bool:
        """Gets the atsss_ll of this UpfInfoAtsssCapability.

        Indicates the ATSSS-LL capability to support procedures related to Access Traffic Steering, Switching, Splitting (see clauses 4.2.10, 5.32 of 3GPP TS 23.501). true: Supported false (default): Not Supported   # noqa: E501

        :return: The atsss_ll of this UpfInfoAtsssCapability.
        :rtype: bool
        """
        return self._atsss_ll

    @atsss_ll.setter
    def atsss_ll(self, atsss_ll: bool):
        """Sets the atsss_ll of this UpfInfoAtsssCapability.

        Indicates the ATSSS-LL capability to support procedures related to Access Traffic Steering, Switching, Splitting (see clauses 4.2.10, 5.32 of 3GPP TS 23.501). true: Supported false (default): Not Supported   # noqa: E501

        :param atsss_ll: The atsss_ll of this UpfInfoAtsssCapability.
        :type atsss_ll: bool
        """

        self._atsss_ll = atsss_ll

    @property
    def mptcp(self) -> bool:
        """Gets the mptcp of this UpfInfoAtsssCapability.

        Indicates the MPTCP capability to support procedures related to Access Traffic Steering, Switching, Splitting (see clauses 4.2.10, 5.32 of 3GPP TS 23.501 true: Supported false (default): Not Supported   # noqa: E501

        :return: The mptcp of this UpfInfoAtsssCapability.
        :rtype: bool
        """
        return self._mptcp

    @mptcp.setter
    def mptcp(self, mptcp: bool):
        """Sets the mptcp of this UpfInfoAtsssCapability.

        Indicates the MPTCP capability to support procedures related to Access Traffic Steering, Switching, Splitting (see clauses 4.2.10, 5.32 of 3GPP TS 23.501 true: Supported false (default): Not Supported   # noqa: E501

        :param mptcp: The mptcp of this UpfInfoAtsssCapability.
        :type mptcp: bool
        """

        self._mptcp = mptcp

    @property
    def rtt_without_pmf(self) -> bool:
        """Gets the rtt_without_pmf of this UpfInfoAtsssCapability.

        This IE is only used by the UPF to indicate whether the UPF supports RTT measurement without PMF (see clauses 5.32.2, 6.3.3.3 of 3GPP TS 23.501 true: Supported false (default): Not Supported   # noqa: E501

        :return: The rtt_without_pmf of this UpfInfoAtsssCapability.
        :rtype: bool
        """
        return self._rtt_without_pmf

    @rtt_without_pmf.setter
    def rtt_without_pmf(self, rtt_without_pmf: bool):
        """Sets the rtt_without_pmf of this UpfInfoAtsssCapability.

        This IE is only used by the UPF to indicate whether the UPF supports RTT measurement without PMF (see clauses 5.32.2, 6.3.3.3 of 3GPP TS 23.501 true: Supported false (default): Not Supported   # noqa: E501

        :param rtt_without_pmf: The rtt_without_pmf of this UpfInfoAtsssCapability.
        :type rtt_without_pmf: bool
        """

        self._rtt_without_pmf = rtt_without_pmf
