# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class AnyOfNFServiceScheme(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """AnyOfNFServiceScheme - a model defined in Swagger

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AnyOfNFServiceScheme':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnyOfNFServiceScheme of this AnyOfNFServiceScheme.  # noqa: E501
        :rtype: AnyOfNFServiceScheme
        """
        return util.deserialize_model(dikt, cls)
