# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.alternative_service_requirements_data import AlternativeServiceRequirementsData
from models.eth_flow_description import EthFlowDescription
from models.eth_flow_info import EthFlowInfo
from models.flow_info import FlowInfo
from models.qos_monitoring_information_rm import QosMonitoringInformationRm
from models.tsc_qos_requirement_rm import TscQosRequirementRm
from models.usage_threshold_rm import UsageThresholdRm
from models.user_plane_event import UserPlaneEvent
import util

class AsSessionWithQoSSubscriptionPatch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, exter_app_id=None, flow_info=None, eth_flow_info=None, en_eth_flow_info=None, qos_reference=None, alt_qo_s_references=None, alt_qos_reqs=None, dis_ue_notif=None, usage_threshold=None, qos_mon_info=None, direct_notif_ind=None, notification_destination=None, tsc_qos_req=None, events=None):  # noqa: E501
        """AsSessionWithQoSSubscriptionPatch - a model defined in OpenAPI

        :param exter_app_id: The exter_app_id of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type exter_app_id: str
        :param flow_info: The flow_info of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type flow_info: List[FlowInfo]
        :param eth_flow_info: The eth_flow_info of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type eth_flow_info: List[EthFlowDescription]
        :param en_eth_flow_info: The en_eth_flow_info of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type en_eth_flow_info: List[EthFlowInfo]
        :param qos_reference: The qos_reference of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type qos_reference: str
        :param alt_qo_s_references: The alt_qo_s_references of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type alt_qo_s_references: List[str]
        :param alt_qos_reqs: The alt_qos_reqs of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type alt_qos_reqs: List[AlternativeServiceRequirementsData]
        :param dis_ue_notif: The dis_ue_notif of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type dis_ue_notif: bool
        :param usage_threshold: The usage_threshold of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type usage_threshold: UsageThresholdRm
        :param qos_mon_info: The qos_mon_info of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type qos_mon_info: QosMonitoringInformationRm
        :param direct_notif_ind: The direct_notif_ind of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type direct_notif_ind: bool
        :param notification_destination: The notification_destination of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type notification_destination: str
        :param tsc_qos_req: The tsc_qos_req of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type tsc_qos_req: TscQosRequirementRm
        :param events: The events of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :type events: List[UserPlaneEvent]
        """
        self.openapi_types = {
            'exter_app_id': str,
            'flow_info': List[FlowInfo],
            'eth_flow_info': List[EthFlowDescription],
            'en_eth_flow_info': List[EthFlowInfo],
            'qos_reference': str,
            'alt_qo_s_references': List[str],
            'alt_qos_reqs': List[AlternativeServiceRequirementsData],
            'dis_ue_notif': bool,
            'usage_threshold': UsageThresholdRm,
            'qos_mon_info': QosMonitoringInformationRm,
            'direct_notif_ind': bool,
            'notification_destination': str,
            'tsc_qos_req': TscQosRequirementRm,
            'events': List[UserPlaneEvent]
        }

        self.attribute_map = {
            'exter_app_id': 'exterAppId',
            'flow_info': 'flowInfo',
            'eth_flow_info': 'ethFlowInfo',
            'en_eth_flow_info': 'enEthFlowInfo',
            'qos_reference': 'qosReference',
            'alt_qo_s_references': 'altQoSReferences',
            'alt_qos_reqs': 'altQosReqs',
            'dis_ue_notif': 'disUeNotif',
            'usage_threshold': 'usageThreshold',
            'qos_mon_info': 'qosMonInfo',
            'direct_notif_ind': 'directNotifInd',
            'notification_destination': 'notificationDestination',
            'tsc_qos_req': 'tscQosReq',
            'events': 'events'
        }

        self._exter_app_id = exter_app_id
        self._flow_info = flow_info
        self._eth_flow_info = eth_flow_info
        self._en_eth_flow_info = en_eth_flow_info
        self._qos_reference = qos_reference
        self._alt_qo_s_references = alt_qo_s_references
        self._alt_qos_reqs = alt_qos_reqs
        self._dis_ue_notif = dis_ue_notif
        self._usage_threshold = usage_threshold
        self._qos_mon_info = qos_mon_info
        self._direct_notif_ind = direct_notif_ind
        self._notification_destination = notification_destination
        self._tsc_qos_req = tsc_qos_req
        self._events = events

    @classmethod
    def from_dict(cls, dikt) -> 'AsSessionWithQoSSubscriptionPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AsSessionWithQoSSubscriptionPatch of this AsSessionWithQoSSubscriptionPatch.  # noqa: E501
        :rtype: AsSessionWithQoSSubscriptionPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exter_app_id(self):
        """Gets the exter_app_id of this AsSessionWithQoSSubscriptionPatch.

        Identifies the external Application Identifier.  # noqa: E501

        :return: The exter_app_id of this AsSessionWithQoSSubscriptionPatch.
        :rtype: str
        """
        return self._exter_app_id

    @exter_app_id.setter
    def exter_app_id(self, exter_app_id):
        """Sets the exter_app_id of this AsSessionWithQoSSubscriptionPatch.

        Identifies the external Application Identifier.  # noqa: E501

        :param exter_app_id: The exter_app_id of this AsSessionWithQoSSubscriptionPatch.
        :type exter_app_id: str
        """

        self._exter_app_id = exter_app_id

    @property
    def flow_info(self):
        """Gets the flow_info of this AsSessionWithQoSSubscriptionPatch.

        Describe the IP data flow which requires QoS.  # noqa: E501

        :return: The flow_info of this AsSessionWithQoSSubscriptionPatch.
        :rtype: List[FlowInfo]
        """
        return self._flow_info

    @flow_info.setter
    def flow_info(self, flow_info):
        """Sets the flow_info of this AsSessionWithQoSSubscriptionPatch.

        Describe the IP data flow which requires QoS.  # noqa: E501

        :param flow_info: The flow_info of this AsSessionWithQoSSubscriptionPatch.
        :type flow_info: List[FlowInfo]
        """
        if flow_info is not None and len(flow_info) < 1:
            raise ValueError("Invalid value for `flow_info`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._flow_info = flow_info

    @property
    def eth_flow_info(self):
        """Gets the eth_flow_info of this AsSessionWithQoSSubscriptionPatch.

        Identifies Ethernet packet flows.  # noqa: E501

        :return: The eth_flow_info of this AsSessionWithQoSSubscriptionPatch.
        :rtype: List[EthFlowDescription]
        """
        return self._eth_flow_info

    @eth_flow_info.setter
    def eth_flow_info(self, eth_flow_info):
        """Sets the eth_flow_info of this AsSessionWithQoSSubscriptionPatch.

        Identifies Ethernet packet flows.  # noqa: E501

        :param eth_flow_info: The eth_flow_info of this AsSessionWithQoSSubscriptionPatch.
        :type eth_flow_info: List[EthFlowDescription]
        """
        if eth_flow_info is not None and len(eth_flow_info) < 1:
            raise ValueError("Invalid value for `eth_flow_info`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._eth_flow_info = eth_flow_info

    @property
    def en_eth_flow_info(self):
        """Gets the en_eth_flow_info of this AsSessionWithQoSSubscriptionPatch.

        Identifies the Ethernet flows which require QoS. Each Ethernet flow consists of a flow idenifer and the corresponding UL and/or DL flows.   # noqa: E501

        :return: The en_eth_flow_info of this AsSessionWithQoSSubscriptionPatch.
        :rtype: List[EthFlowInfo]
        """
        return self._en_eth_flow_info

    @en_eth_flow_info.setter
    def en_eth_flow_info(self, en_eth_flow_info):
        """Sets the en_eth_flow_info of this AsSessionWithQoSSubscriptionPatch.

        Identifies the Ethernet flows which require QoS. Each Ethernet flow consists of a flow idenifer and the corresponding UL and/or DL flows.   # noqa: E501

        :param en_eth_flow_info: The en_eth_flow_info of this AsSessionWithQoSSubscriptionPatch.
        :type en_eth_flow_info: List[EthFlowInfo]
        """
        if en_eth_flow_info is not None and len(en_eth_flow_info) < 1:
            raise ValueError("Invalid value for `en_eth_flow_info`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._en_eth_flow_info = en_eth_flow_info

    @property
    def qos_reference(self):
        """Gets the qos_reference of this AsSessionWithQoSSubscriptionPatch.

        Pre-defined QoS reference  # noqa: E501

        :return: The qos_reference of this AsSessionWithQoSSubscriptionPatch.
        :rtype: str
        """
        return self._qos_reference

    @qos_reference.setter
    def qos_reference(self, qos_reference):
        """Sets the qos_reference of this AsSessionWithQoSSubscriptionPatch.

        Pre-defined QoS reference  # noqa: E501

        :param qos_reference: The qos_reference of this AsSessionWithQoSSubscriptionPatch.
        :type qos_reference: str
        """

        self._qos_reference = qos_reference

    @property
    def alt_qo_s_references(self):
        """Gets the alt_qo_s_references of this AsSessionWithQoSSubscriptionPatch.

        Identifies an ordered list of pre-defined QoS information. The lower the index of the array for a given entry, the higher the priority.  # noqa: E501

        :return: The alt_qo_s_references of this AsSessionWithQoSSubscriptionPatch.
        :rtype: List[str]
        """
        return self._alt_qo_s_references

    @alt_qo_s_references.setter
    def alt_qo_s_references(self, alt_qo_s_references):
        """Sets the alt_qo_s_references of this AsSessionWithQoSSubscriptionPatch.

        Identifies an ordered list of pre-defined QoS information. The lower the index of the array for a given entry, the higher the priority.  # noqa: E501

        :param alt_qo_s_references: The alt_qo_s_references of this AsSessionWithQoSSubscriptionPatch.
        :type alt_qo_s_references: List[str]
        """
        if alt_qo_s_references is not None and len(alt_qo_s_references) < 1:
            raise ValueError("Invalid value for `alt_qo_s_references`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._alt_qo_s_references = alt_qo_s_references

    @property
    def alt_qos_reqs(self):
        """Gets the alt_qos_reqs of this AsSessionWithQoSSubscriptionPatch.

        Identifies an ordered list of alternative service requirements that include individual QoS parameter sets. The lower the index of the array for a given entry, the higher the priority.  # noqa: E501

        :return: The alt_qos_reqs of this AsSessionWithQoSSubscriptionPatch.
        :rtype: List[AlternativeServiceRequirementsData]
        """
        return self._alt_qos_reqs

    @alt_qos_reqs.setter
    def alt_qos_reqs(self, alt_qos_reqs):
        """Sets the alt_qos_reqs of this AsSessionWithQoSSubscriptionPatch.

        Identifies an ordered list of alternative service requirements that include individual QoS parameter sets. The lower the index of the array for a given entry, the higher the priority.  # noqa: E501

        :param alt_qos_reqs: The alt_qos_reqs of this AsSessionWithQoSSubscriptionPatch.
        :type alt_qos_reqs: List[AlternativeServiceRequirementsData]
        """
        if alt_qos_reqs is not None and len(alt_qos_reqs) < 1:
            raise ValueError("Invalid value for `alt_qos_reqs`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._alt_qos_reqs = alt_qos_reqs

    @property
    def dis_ue_notif(self):
        """Gets the dis_ue_notif of this AsSessionWithQoSSubscriptionPatch.

        Indicates whether the QoS flow parameters signalling to the UE when the SMF is notified by the NG-RAN of changes in the fulfilled QoS situation is disabled (true) or not (false). The fulfilled situation is either the QoS profile or an Alternative QoS Profile.   # noqa: E501

        :return: The dis_ue_notif of this AsSessionWithQoSSubscriptionPatch.
        :rtype: bool
        """
        return self._dis_ue_notif

    @dis_ue_notif.setter
    def dis_ue_notif(self, dis_ue_notif):
        """Sets the dis_ue_notif of this AsSessionWithQoSSubscriptionPatch.

        Indicates whether the QoS flow parameters signalling to the UE when the SMF is notified by the NG-RAN of changes in the fulfilled QoS situation is disabled (true) or not (false). The fulfilled situation is either the QoS profile or an Alternative QoS Profile.   # noqa: E501

        :param dis_ue_notif: The dis_ue_notif of this AsSessionWithQoSSubscriptionPatch.
        :type dis_ue_notif: bool
        """

        self._dis_ue_notif = dis_ue_notif

    @property
    def usage_threshold(self):
        """Gets the usage_threshold of this AsSessionWithQoSSubscriptionPatch.


        :return: The usage_threshold of this AsSessionWithQoSSubscriptionPatch.
        :rtype: UsageThresholdRm
        """
        return self._usage_threshold

    @usage_threshold.setter
    def usage_threshold(self, usage_threshold):
        """Sets the usage_threshold of this AsSessionWithQoSSubscriptionPatch.


        :param usage_threshold: The usage_threshold of this AsSessionWithQoSSubscriptionPatch.
        :type usage_threshold: UsageThresholdRm
        """

        self._usage_threshold = usage_threshold

    @property
    def qos_mon_info(self):
        """Gets the qos_mon_info of this AsSessionWithQoSSubscriptionPatch.


        :return: The qos_mon_info of this AsSessionWithQoSSubscriptionPatch.
        :rtype: QosMonitoringInformationRm
        """
        return self._qos_mon_info

    @qos_mon_info.setter
    def qos_mon_info(self, qos_mon_info):
        """Sets the qos_mon_info of this AsSessionWithQoSSubscriptionPatch.


        :param qos_mon_info: The qos_mon_info of this AsSessionWithQoSSubscriptionPatch.
        :type qos_mon_info: QosMonitoringInformationRm
        """

        self._qos_mon_info = qos_mon_info

    @property
    def direct_notif_ind(self):
        """Gets the direct_notif_ind of this AsSessionWithQoSSubscriptionPatch.

        Indicates whether the direct event notification is requested (true) or not (false).   # noqa: E501

        :return: The direct_notif_ind of this AsSessionWithQoSSubscriptionPatch.
        :rtype: bool
        """
        return self._direct_notif_ind

    @direct_notif_ind.setter
    def direct_notif_ind(self, direct_notif_ind):
        """Sets the direct_notif_ind of this AsSessionWithQoSSubscriptionPatch.

        Indicates whether the direct event notification is requested (true) or not (false).   # noqa: E501

        :param direct_notif_ind: The direct_notif_ind of this AsSessionWithQoSSubscriptionPatch.
        :type direct_notif_ind: bool
        """

        self._direct_notif_ind = direct_notif_ind

    @property
    def notification_destination(self):
        """Gets the notification_destination of this AsSessionWithQoSSubscriptionPatch.

        string formatted according to IETF RFC 3986 identifying a referenced resource.  # noqa: E501

        :return: The notification_destination of this AsSessionWithQoSSubscriptionPatch.
        :rtype: str
        """
        return self._notification_destination

    @notification_destination.setter
    def notification_destination(self, notification_destination):
        """Sets the notification_destination of this AsSessionWithQoSSubscriptionPatch.

        string formatted according to IETF RFC 3986 identifying a referenced resource.  # noqa: E501

        :param notification_destination: The notification_destination of this AsSessionWithQoSSubscriptionPatch.
        :type notification_destination: str
        """

        self._notification_destination = notification_destination

    @property
    def tsc_qos_req(self):
        """Gets the tsc_qos_req of this AsSessionWithQoSSubscriptionPatch.


        :return: The tsc_qos_req of this AsSessionWithQoSSubscriptionPatch.
        :rtype: TscQosRequirementRm
        """
        return self._tsc_qos_req

    @tsc_qos_req.setter
    def tsc_qos_req(self, tsc_qos_req):
        """Sets the tsc_qos_req of this AsSessionWithQoSSubscriptionPatch.


        :param tsc_qos_req: The tsc_qos_req of this AsSessionWithQoSSubscriptionPatch.
        :type tsc_qos_req: TscQosRequirementRm
        """

        self._tsc_qos_req = tsc_qos_req

    @property
    def events(self):
        """Gets the events of this AsSessionWithQoSSubscriptionPatch.

        Represents the updated list of user plane event(s) to which the SCS/AS requests to subscribe to.  # noqa: E501

        :return: The events of this AsSessionWithQoSSubscriptionPatch.
        :rtype: List[UserPlaneEvent]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this AsSessionWithQoSSubscriptionPatch.

        Represents the updated list of user plane event(s) to which the SCS/AS requests to subscribe to.  # noqa: E501

        :param events: The events of this AsSessionWithQoSSubscriptionPatch.
        :type events: List[UserPlaneEvent]
        """
        if events is not None and len(events) < 1:
            raise ValueError("Invalid value for `events`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._events = events
