# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.acceptable_service_info import AcceptableServiceInfo
import util

from models.acceptable_service_info import AcceptableServiceInfo  # noqa: E501

class ExtendedProblemDetailsAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, acceptable_serv_info=None):  # noqa: E501
        """ExtendedProblemDetailsAllOf - a model defined in OpenAPI

        :param acceptable_serv_info: The acceptable_serv_info of this ExtendedProblemDetailsAllOf.  # noqa: E501
        :type acceptable_serv_info: AcceptableServiceInfo
        """
        self.openapi_types = {
            'acceptable_serv_info': AcceptableServiceInfo
        }

        self.attribute_map = {
            'acceptable_serv_info': 'acceptableServInfo'
        }

        self._acceptable_serv_info = acceptable_serv_info

    @classmethod
    def from_dict(cls, dikt) -> 'ExtendedProblemDetailsAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExtendedProblemDetails_allOf of this ExtendedProblemDetailsAllOf.  # noqa: E501
        :rtype: ExtendedProblemDetailsAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def acceptable_serv_info(self):
        """Gets the acceptable_serv_info of this ExtendedProblemDetailsAllOf.


        :return: The acceptable_serv_info of this ExtendedProblemDetailsAllOf.
        :rtype: AcceptableServiceInfo
        """
        return self._acceptable_serv_info

    @acceptable_serv_info.setter
    def acceptable_serv_info(self, acceptable_serv_info):
        """Sets the acceptable_serv_info of this ExtendedProblemDetailsAllOf.


        :param acceptable_serv_info: The acceptable_serv_info of this ExtendedProblemDetailsAllOf.
        :type acceptable_serv_info: AcceptableServiceInfo
        """

        self._acceptable_serv_info = acceptable_serv_info
