# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.api_capability_info import ApiCapabilityInfo
from models.association_type import AssociationType
from models.ddd_traffic_descriptor import DddTrafficDescriptor
from models.dl_data_delivery_status import DlDataDeliveryStatus
from models.failure_cause import FailureCause
from models.idle_status_info import IdleStatusInfo
from models.location_failure_cause import LocationFailureCause
from models.location_info import LocationInfo
from models.monitoring_type import MonitoringType
from models.pdn_connection_information import PdnConnectionInformation
from models.plmn_id import PlmnId
from models.reachability_type import ReachabilityType
from models.sac_event_status import SACEventStatus
from models.ue_per_location_report import UePerLocationReport
import util

from models.api_capability_info import ApiCapabilityInfo  # noqa: E501
from models.association_type import AssociationType  # noqa: E501
from models.ddd_traffic_descriptor import DddTrafficDescriptor  # noqa: E501
from models.dl_data_delivery_status import DlDataDeliveryStatus  # noqa: E501
from models.failure_cause import FailureCause  # noqa: E501
from models.idle_status_info import IdleStatusInfo  # noqa: E501
from models.location_failure_cause import LocationFailureCause  # noqa: E501
from models.location_info import LocationInfo  # noqa: E501
from models.monitoring_type import MonitoringType  # noqa: E501
from models.pdn_connection_information import PdnConnectionInformation  # noqa: E501
from models.plmn_id import PlmnId  # noqa: E501
from models.reachability_type import ReachabilityType  # noqa: E501
from models.sac_event_status import SACEventStatus  # noqa: E501
from models.ue_per_location_report import UePerLocationReport  # noqa: E501

class MonitoringEventReport(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, imei_change=None, external_id=None, idle_status_info=None, location_info=None, loc_failure_cause=None, loss_of_connect_reason=None, max_ue_availability_time=None, msisdn=None, monitoring_type=None, ue_per_location_report=None, plmn_id=None, reachability_type=None, roaming_status=None, failure_cause=None, event_time=None, pdn_conn_info_list=None, ddd_status=None, ddd_traf_descriptor=None, max_wait_time=None, api_caps=None, n_s_status_info=None, af_service_id=None, serv_level_dev_id=None, uav_pres_ind=None):  # noqa: E501
        """MonitoringEventReport - a model defined in OpenAPI

        :param imei_change: The imei_change of this MonitoringEventReport.  # noqa: E501
        :type imei_change: AssociationType
        :param external_id: The external_id of this MonitoringEventReport.  # noqa: E501
        :type external_id: str
        :param idle_status_info: The idle_status_info of this MonitoringEventReport.  # noqa: E501
        :type idle_status_info: IdleStatusInfo
        :param location_info: The location_info of this MonitoringEventReport.  # noqa: E501
        :type location_info: LocationInfo
        :param loc_failure_cause: The loc_failure_cause of this MonitoringEventReport.  # noqa: E501
        :type loc_failure_cause: LocationFailureCause
        :param loss_of_connect_reason: The loss_of_connect_reason of this MonitoringEventReport.  # noqa: E501
        :type loss_of_connect_reason: int
        :param max_ue_availability_time: The max_ue_availability_time of this MonitoringEventReport.  # noqa: E501
        :type max_ue_availability_time: datetime
        :param msisdn: The msisdn of this MonitoringEventReport.  # noqa: E501
        :type msisdn: str
        :param monitoring_type: The monitoring_type of this MonitoringEventReport.  # noqa: E501
        :type monitoring_type: MonitoringType
        :param ue_per_location_report: The ue_per_location_report of this MonitoringEventReport.  # noqa: E501
        :type ue_per_location_report: UePerLocationReport
        :param plmn_id: The plmn_id of this MonitoringEventReport.  # noqa: E501
        :type plmn_id: PlmnId
        :param reachability_type: The reachability_type of this MonitoringEventReport.  # noqa: E501
        :type reachability_type: ReachabilityType
        :param roaming_status: The roaming_status of this MonitoringEventReport.  # noqa: E501
        :type roaming_status: bool
        :param failure_cause: The failure_cause of this MonitoringEventReport.  # noqa: E501
        :type failure_cause: FailureCause
        :param event_time: The event_time of this MonitoringEventReport.  # noqa: E501
        :type event_time: datetime
        :param pdn_conn_info_list: The pdn_conn_info_list of this MonitoringEventReport.  # noqa: E501
        :type pdn_conn_info_list: List[PdnConnectionInformation]
        :param ddd_status: The ddd_status of this MonitoringEventReport.  # noqa: E501
        :type ddd_status: DlDataDeliveryStatus
        :param ddd_traf_descriptor: The ddd_traf_descriptor of this MonitoringEventReport.  # noqa: E501
        :type ddd_traf_descriptor: DddTrafficDescriptor
        :param max_wait_time: The max_wait_time of this MonitoringEventReport.  # noqa: E501
        :type max_wait_time: datetime
        :param api_caps: The api_caps of this MonitoringEventReport.  # noqa: E501
        :type api_caps: List[ApiCapabilityInfo]
        :param n_s_status_info: The n_s_status_info of this MonitoringEventReport.  # noqa: E501
        :type n_s_status_info: SACEventStatus
        :param af_service_id: The af_service_id of this MonitoringEventReport.  # noqa: E501
        :type af_service_id: str
        :param serv_level_dev_id: The serv_level_dev_id of this MonitoringEventReport.  # noqa: E501
        :type serv_level_dev_id: str
        :param uav_pres_ind: The uav_pres_ind of this MonitoringEventReport.  # noqa: E501
        :type uav_pres_ind: bool
        """
        self.openapi_types = {
            'imei_change': AssociationType,
            'external_id': str,
            'idle_status_info': IdleStatusInfo,
            'location_info': LocationInfo,
            'loc_failure_cause': LocationFailureCause,
            'loss_of_connect_reason': int,
            'max_ue_availability_time': datetime,
            'msisdn': str,
            'monitoring_type': MonitoringType,
            'ue_per_location_report': UePerLocationReport,
            'plmn_id': PlmnId,
            'reachability_type': ReachabilityType,
            'roaming_status': bool,
            'failure_cause': FailureCause,
            'event_time': datetime,
            'pdn_conn_info_list': List[PdnConnectionInformation],
            'ddd_status': DlDataDeliveryStatus,
            'ddd_traf_descriptor': DddTrafficDescriptor,
            'max_wait_time': datetime,
            'api_caps': List[ApiCapabilityInfo],
            'n_s_status_info': SACEventStatus,
            'af_service_id': str,
            'serv_level_dev_id': str,
            'uav_pres_ind': bool
        }

        self.attribute_map = {
            'imei_change': 'imeiChange',
            'external_id': 'externalId',
            'idle_status_info': 'idleStatusInfo',
            'location_info': 'locationInfo',
            'loc_failure_cause': 'locFailureCause',
            'loss_of_connect_reason': 'lossOfConnectReason',
            'max_ue_availability_time': 'maxUEAvailabilityTime',
            'msisdn': 'msisdn',
            'monitoring_type': 'monitoringType',
            'ue_per_location_report': 'uePerLocationReport',
            'plmn_id': 'plmnId',
            'reachability_type': 'reachabilityType',
            'roaming_status': 'roamingStatus',
            'failure_cause': 'failureCause',
            'event_time': 'eventTime',
            'pdn_conn_info_list': 'pdnConnInfoList',
            'ddd_status': 'dddStatus',
            'ddd_traf_descriptor': 'dddTrafDescriptor',
            'max_wait_time': 'maxWaitTime',
            'api_caps': 'apiCaps',
            'n_s_status_info': 'nSStatusInfo',
            'af_service_id': 'afServiceId',
            'serv_level_dev_id': 'servLevelDevId',
            'uav_pres_ind': 'uavPresInd'
        }

        self._imei_change = imei_change
        self._external_id = external_id
        self._idle_status_info = idle_status_info
        self._location_info = location_info
        self._loc_failure_cause = loc_failure_cause
        self._loss_of_connect_reason = loss_of_connect_reason
        self._max_ue_availability_time = max_ue_availability_time
        self._msisdn = msisdn
        self._monitoring_type = monitoring_type
        self._ue_per_location_report = ue_per_location_report
        self._plmn_id = plmn_id
        self._reachability_type = reachability_type
        self._roaming_status = roaming_status
        self._failure_cause = failure_cause
        self._event_time = event_time
        self._pdn_conn_info_list = pdn_conn_info_list
        self._ddd_status = ddd_status
        self._ddd_traf_descriptor = ddd_traf_descriptor
        self._max_wait_time = max_wait_time
        self._api_caps = api_caps
        self._n_s_status_info = n_s_status_info
        self._af_service_id = af_service_id
        self._serv_level_dev_id = serv_level_dev_id
        self._uav_pres_ind = uav_pres_ind

    @classmethod
    def from_dict(cls, dikt) -> 'MonitoringEventReport':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MonitoringEventReport of this MonitoringEventReport.  # noqa: E501
        :rtype: MonitoringEventReport
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imei_change(self):
        """Gets the imei_change of this MonitoringEventReport.


        :return: The imei_change of this MonitoringEventReport.
        :rtype: AssociationType
        """
        return self._imei_change

    @imei_change.setter
    def imei_change(self, imei_change):
        """Sets the imei_change of this MonitoringEventReport.


        :param imei_change: The imei_change of this MonitoringEventReport.
        :type imei_change: AssociationType
        """

        self._imei_change = imei_change

    @property
    def external_id(self):
        """Gets the external_id of this MonitoringEventReport.

        string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clause 4.6.2 of 3GPP TS 23.682 for more information.  # noqa: E501

        :return: The external_id of this MonitoringEventReport.
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this MonitoringEventReport.

        string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clause 4.6.2 of 3GPP TS 23.682 for more information.  # noqa: E501

        :param external_id: The external_id of this MonitoringEventReport.
        :type external_id: str
        """

        self._external_id = external_id

    @property
    def idle_status_info(self):
        """Gets the idle_status_info of this MonitoringEventReport.


        :return: The idle_status_info of this MonitoringEventReport.
        :rtype: IdleStatusInfo
        """
        return self._idle_status_info

    @idle_status_info.setter
    def idle_status_info(self, idle_status_info):
        """Sets the idle_status_info of this MonitoringEventReport.


        :param idle_status_info: The idle_status_info of this MonitoringEventReport.
        :type idle_status_info: IdleStatusInfo
        """

        self._idle_status_info = idle_status_info

    @property
    def location_info(self):
        """Gets the location_info of this MonitoringEventReport.


        :return: The location_info of this MonitoringEventReport.
        :rtype: LocationInfo
        """
        return self._location_info

    @location_info.setter
    def location_info(self, location_info):
        """Sets the location_info of this MonitoringEventReport.


        :param location_info: The location_info of this MonitoringEventReport.
        :type location_info: LocationInfo
        """

        self._location_info = location_info

    @property
    def loc_failure_cause(self):
        """Gets the loc_failure_cause of this MonitoringEventReport.


        :return: The loc_failure_cause of this MonitoringEventReport.
        :rtype: LocationFailureCause
        """
        return self._loc_failure_cause

    @loc_failure_cause.setter
    def loc_failure_cause(self, loc_failure_cause):
        """Sets the loc_failure_cause of this MonitoringEventReport.


        :param loc_failure_cause: The loc_failure_cause of this MonitoringEventReport.
        :type loc_failure_cause: LocationFailureCause
        """

        self._loc_failure_cause = loc_failure_cause

    @property
    def loss_of_connect_reason(self):
        """Gets the loss_of_connect_reason of this MonitoringEventReport.

        If \"monitoringType\" is \"LOSS_OF_CONNECTIVITY\", this parameter shall be included if available to identify the reason why loss of connectivity is reported. Refer to 3GPP TS 29.336 clause 8.4.58.  # noqa: E501

        :return: The loss_of_connect_reason of this MonitoringEventReport.
        :rtype: int
        """
        return self._loss_of_connect_reason

    @loss_of_connect_reason.setter
    def loss_of_connect_reason(self, loss_of_connect_reason):
        """Sets the loss_of_connect_reason of this MonitoringEventReport.

        If \"monitoringType\" is \"LOSS_OF_CONNECTIVITY\", this parameter shall be included if available to identify the reason why loss of connectivity is reported. Refer to 3GPP TS 29.336 clause 8.4.58.  # noqa: E501

        :param loss_of_connect_reason: The loss_of_connect_reason of this MonitoringEventReport.
        :type loss_of_connect_reason: int
        """

        self._loss_of_connect_reason = loss_of_connect_reason

    @property
    def max_ue_availability_time(self):
        """Gets the max_ue_availability_time of this MonitoringEventReport.

        string with format \"date-time\" as defined in OpenAPI.  # noqa: E501

        :return: The max_ue_availability_time of this MonitoringEventReport.
        :rtype: datetime
        """
        return self._max_ue_availability_time

    @max_ue_availability_time.setter
    def max_ue_availability_time(self, max_ue_availability_time):
        """Sets the max_ue_availability_time of this MonitoringEventReport.

        string with format \"date-time\" as defined in OpenAPI.  # noqa: E501

        :param max_ue_availability_time: The max_ue_availability_time of this MonitoringEventReport.
        :type max_ue_availability_time: datetime
        """

        self._max_ue_availability_time = max_ue_availability_time

    @property
    def msisdn(self):
        """Gets the msisdn of this MonitoringEventReport.

        string formatted according to clause 3.3 of 3GPP TS 23.003 that describes an MSISDN.  # noqa: E501

        :return: The msisdn of this MonitoringEventReport.
        :rtype: str
        """
        return self._msisdn

    @msisdn.setter
    def msisdn(self, msisdn):
        """Sets the msisdn of this MonitoringEventReport.

        string formatted according to clause 3.3 of 3GPP TS 23.003 that describes an MSISDN.  # noqa: E501

        :param msisdn: The msisdn of this MonitoringEventReport.
        :type msisdn: str
        """

        self._msisdn = msisdn

    @property
    def monitoring_type(self):
        """Gets the monitoring_type of this MonitoringEventReport.


        :return: The monitoring_type of this MonitoringEventReport.
        :rtype: MonitoringType
        """
        return self._monitoring_type

    @monitoring_type.setter
    def monitoring_type(self, monitoring_type):
        """Sets the monitoring_type of this MonitoringEventReport.


        :param monitoring_type: The monitoring_type of this MonitoringEventReport.
        :type monitoring_type: MonitoringType
        """
        if monitoring_type is None:
            raise ValueError("Invalid value for `monitoring_type`, must not be `None`")  # noqa: E501

        self._monitoring_type = monitoring_type

    @property
    def ue_per_location_report(self):
        """Gets the ue_per_location_report of this MonitoringEventReport.


        :return: The ue_per_location_report of this MonitoringEventReport.
        :rtype: UePerLocationReport
        """
        return self._ue_per_location_report

    @ue_per_location_report.setter
    def ue_per_location_report(self, ue_per_location_report):
        """Sets the ue_per_location_report of this MonitoringEventReport.


        :param ue_per_location_report: The ue_per_location_report of this MonitoringEventReport.
        :type ue_per_location_report: UePerLocationReport
        """

        self._ue_per_location_report = ue_per_location_report

    @property
    def plmn_id(self):
        """Gets the plmn_id of this MonitoringEventReport.


        :return: The plmn_id of this MonitoringEventReport.
        :rtype: PlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id):
        """Sets the plmn_id of this MonitoringEventReport.


        :param plmn_id: The plmn_id of this MonitoringEventReport.
        :type plmn_id: PlmnId
        """

        self._plmn_id = plmn_id

    @property
    def reachability_type(self):
        """Gets the reachability_type of this MonitoringEventReport.


        :return: The reachability_type of this MonitoringEventReport.
        :rtype: ReachabilityType
        """
        return self._reachability_type

    @reachability_type.setter
    def reachability_type(self, reachability_type):
        """Sets the reachability_type of this MonitoringEventReport.


        :param reachability_type: The reachability_type of this MonitoringEventReport.
        :type reachability_type: ReachabilityType
        """

        self._reachability_type = reachability_type

    @property
    def roaming_status(self):
        """Gets the roaming_status of this MonitoringEventReport.

        If \"monitoringType\" is \"ROAMING_STATUS\", this parameter shall be set to \"true\" if the UE is on roaming status. Set to false or omitted otherwise.  # noqa: E501

        :return: The roaming_status of this MonitoringEventReport.
        :rtype: bool
        """
        return self._roaming_status

    @roaming_status.setter
    def roaming_status(self, roaming_status):
        """Sets the roaming_status of this MonitoringEventReport.

        If \"monitoringType\" is \"ROAMING_STATUS\", this parameter shall be set to \"true\" if the UE is on roaming status. Set to false or omitted otherwise.  # noqa: E501

        :param roaming_status: The roaming_status of this MonitoringEventReport.
        :type roaming_status: bool
        """

        self._roaming_status = roaming_status

    @property
    def failure_cause(self):
        """Gets the failure_cause of this MonitoringEventReport.


        :return: The failure_cause of this MonitoringEventReport.
        :rtype: FailureCause
        """
        return self._failure_cause

    @failure_cause.setter
    def failure_cause(self, failure_cause):
        """Sets the failure_cause of this MonitoringEventReport.


        :param failure_cause: The failure_cause of this MonitoringEventReport.
        :type failure_cause: FailureCause
        """

        self._failure_cause = failure_cause

    @property
    def event_time(self):
        """Gets the event_time of this MonitoringEventReport.

        string with format \"date-time\" as defined in OpenAPI.  # noqa: E501

        :return: The event_time of this MonitoringEventReport.
        :rtype: datetime
        """
        return self._event_time

    @event_time.setter
    def event_time(self, event_time):
        """Sets the event_time of this MonitoringEventReport.

        string with format \"date-time\" as defined in OpenAPI.  # noqa: E501

        :param event_time: The event_time of this MonitoringEventReport.
        :type event_time: datetime
        """

        self._event_time = event_time

    @property
    def pdn_conn_info_list(self):
        """Gets the pdn_conn_info_list of this MonitoringEventReport.


        :return: The pdn_conn_info_list of this MonitoringEventReport.
        :rtype: List[PdnConnectionInformation]
        """
        return self._pdn_conn_info_list

    @pdn_conn_info_list.setter
    def pdn_conn_info_list(self, pdn_conn_info_list):
        """Sets the pdn_conn_info_list of this MonitoringEventReport.


        :param pdn_conn_info_list: The pdn_conn_info_list of this MonitoringEventReport.
        :type pdn_conn_info_list: List[PdnConnectionInformation]
        """
        if pdn_conn_info_list is not None and len(pdn_conn_info_list) < 1:
            raise ValueError("Invalid value for `pdn_conn_info_list`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._pdn_conn_info_list = pdn_conn_info_list

    @property
    def ddd_status(self):
        """Gets the ddd_status of this MonitoringEventReport.


        :return: The ddd_status of this MonitoringEventReport.
        :rtype: DlDataDeliveryStatus
        """
        return self._ddd_status

    @ddd_status.setter
    def ddd_status(self, ddd_status):
        """Sets the ddd_status of this MonitoringEventReport.


        :param ddd_status: The ddd_status of this MonitoringEventReport.
        :type ddd_status: DlDataDeliveryStatus
        """

        self._ddd_status = ddd_status

    @property
    def ddd_traf_descriptor(self):
        """Gets the ddd_traf_descriptor of this MonitoringEventReport.


        :return: The ddd_traf_descriptor of this MonitoringEventReport.
        :rtype: DddTrafficDescriptor
        """
        return self._ddd_traf_descriptor

    @ddd_traf_descriptor.setter
    def ddd_traf_descriptor(self, ddd_traf_descriptor):
        """Sets the ddd_traf_descriptor of this MonitoringEventReport.


        :param ddd_traf_descriptor: The ddd_traf_descriptor of this MonitoringEventReport.
        :type ddd_traf_descriptor: DddTrafficDescriptor
        """

        self._ddd_traf_descriptor = ddd_traf_descriptor

    @property
    def max_wait_time(self):
        """Gets the max_wait_time of this MonitoringEventReport.

        string with format \"date-time\" as defined in OpenAPI.  # noqa: E501

        :return: The max_wait_time of this MonitoringEventReport.
        :rtype: datetime
        """
        return self._max_wait_time

    @max_wait_time.setter
    def max_wait_time(self, max_wait_time):
        """Sets the max_wait_time of this MonitoringEventReport.

        string with format \"date-time\" as defined in OpenAPI.  # noqa: E501

        :param max_wait_time: The max_wait_time of this MonitoringEventReport.
        :type max_wait_time: datetime
        """

        self._max_wait_time = max_wait_time

    @property
    def api_caps(self):
        """Gets the api_caps of this MonitoringEventReport.


        :return: The api_caps of this MonitoringEventReport.
        :rtype: List[ApiCapabilityInfo]
        """
        return self._api_caps

    @api_caps.setter
    def api_caps(self, api_caps):
        """Sets the api_caps of this MonitoringEventReport.


        :param api_caps: The api_caps of this MonitoringEventReport.
        :type api_caps: List[ApiCapabilityInfo]
        """
        if api_caps is not None and len(api_caps) < 0:
            raise ValueError("Invalid value for `api_caps`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_caps = api_caps

    @property
    def n_s_status_info(self):
        """Gets the n_s_status_info of this MonitoringEventReport.


        :return: The n_s_status_info of this MonitoringEventReport.
        :rtype: SACEventStatus
        """
        return self._n_s_status_info

    @n_s_status_info.setter
    def n_s_status_info(self, n_s_status_info):
        """Sets the n_s_status_info of this MonitoringEventReport.


        :param n_s_status_info: The n_s_status_info of this MonitoringEventReport.
        :type n_s_status_info: SACEventStatus
        """

        self._n_s_status_info = n_s_status_info

    @property
    def af_service_id(self):
        """Gets the af_service_id of this MonitoringEventReport.


        :return: The af_service_id of this MonitoringEventReport.
        :rtype: str
        """
        return self._af_service_id

    @af_service_id.setter
    def af_service_id(self, af_service_id):
        """Sets the af_service_id of this MonitoringEventReport.


        :param af_service_id: The af_service_id of this MonitoringEventReport.
        :type af_service_id: str
        """

        self._af_service_id = af_service_id

    @property
    def serv_level_dev_id(self):
        """Gets the serv_level_dev_id of this MonitoringEventReport.

        If \"monitoringType\" is \"AREA_OF_INTEREST\", this parameter may be included to identify the UAV.  # noqa: E501

        :return: The serv_level_dev_id of this MonitoringEventReport.
        :rtype: str
        """
        return self._serv_level_dev_id

    @serv_level_dev_id.setter
    def serv_level_dev_id(self, serv_level_dev_id):
        """Sets the serv_level_dev_id of this MonitoringEventReport.

        If \"monitoringType\" is \"AREA_OF_INTEREST\", this parameter may be included to identify the UAV.  # noqa: E501

        :param serv_level_dev_id: The serv_level_dev_id of this MonitoringEventReport.
        :type serv_level_dev_id: str
        """

        self._serv_level_dev_id = serv_level_dev_id

    @property
    def uav_pres_ind(self):
        """Gets the uav_pres_ind of this MonitoringEventReport.

        If \"monitoringType\" is \"AREA_OF_INTEREST\", this parameter shall be set to true if the specified UAV is in the monitoring area. Set to false or omitted otherwise.  # noqa: E501

        :return: The uav_pres_ind of this MonitoringEventReport.
        :rtype: bool
        """
        return self._uav_pres_ind

    @uav_pres_ind.setter
    def uav_pres_ind(self, uav_pres_ind):
        """Sets the uav_pres_ind of this MonitoringEventReport.

        If \"monitoringType\" is \"AREA_OF_INTEREST\", this parameter shall be set to true if the specified UAV is in the monitoring area. Set to false or omitted otherwise.  # noqa: E501

        :param uav_pres_ind: The uav_pres_ind of this MonitoringEventReport.
        :type uav_pres_ind: bool
        """

        self._uav_pres_ind = uav_pres_ind
