# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class NfGroupListCond(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, condition_type=None, nf_type=None, nf_group_id_list=None):  # noqa: E501
        """NfGroupListCond - a model defined in OpenAPI

        :param condition_type: The condition_type of this NfGroupListCond.  # noqa: E501
        :type condition_type: str
        :param nf_type: The nf_type of this NfGroupListCond.  # noqa: E501
        :type nf_type: str
        :param nf_group_id_list: The nf_group_id_list of this NfGroupListCond.  # noqa: E501
        :type nf_group_id_list: List[str]
        """
        self.openapi_types = {
            'condition_type': str,
            'nf_type': str,
            'nf_group_id_list': List[str]
        }

        self.attribute_map = {
            'condition_type': 'conditionType',
            'nf_type': 'nfType',
            'nf_group_id_list': 'nfGroupIdList'
        }

        self._condition_type = condition_type
        self._nf_type = nf_type
        self._nf_group_id_list = nf_group_id_list

    @classmethod
    def from_dict(cls, dikt) -> 'NfGroupListCond':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NfGroupListCond of this NfGroupListCond.  # noqa: E501
        :rtype: NfGroupListCond
        """
        return util.deserialize_model(dikt, cls)

    @property
    def condition_type(self):
        """Gets the condition_type of this NfGroupListCond.


        :return: The condition_type of this NfGroupListCond.
        :rtype: str
        """
        return self._condition_type

    @condition_type.setter
    def condition_type(self, condition_type):
        """Sets the condition_type of this NfGroupListCond.


        :param condition_type: The condition_type of this NfGroupListCond.
        :type condition_type: str
        """
        allowed_values = ["NF_GROUP_LIST_COND"]  # noqa: E501
        if condition_type not in allowed_values:
            raise ValueError(
                "Invalid value for `condition_type` ({0}), must be one of {1}"
                .format(condition_type, allowed_values)
            )

        self._condition_type = condition_type

    @property
    def nf_type(self):
        """Gets the nf_type of this NfGroupListCond.


        :return: The nf_type of this NfGroupListCond.
        :rtype: str
        """
        return self._nf_type

    @nf_type.setter
    def nf_type(self, nf_type):
        """Sets the nf_type of this NfGroupListCond.


        :param nf_type: The nf_type of this NfGroupListCond.
        :type nf_type: str
        """
        allowed_values = ["UDM", "AUSF", "UDR", "PCF", "CHF", "HSS"]  # noqa: E501
        if nf_type not in allowed_values:
            raise ValueError(
                "Invalid value for `nf_type` ({0}), must be one of {1}"
                .format(nf_type, allowed_values)
            )

        self._nf_type = nf_type

    @property
    def nf_group_id_list(self):
        """Gets the nf_group_id_list of this NfGroupListCond.


        :return: The nf_group_id_list of this NfGroupListCond.
        :rtype: List[str]
        """
        return self._nf_group_id_list

    @nf_group_id_list.setter
    def nf_group_id_list(self, nf_group_id_list):
        """Sets the nf_group_id_list of this NfGroupListCond.


        :param nf_group_id_list: The nf_group_id_list of this NfGroupListCond.
        :type nf_group_id_list: List[str]
        """
        if nf_group_id_list is None:
            raise ValueError("Invalid value for `nf_group_id_list`, must not be `None`")  # noqa: E501
        if nf_group_id_list is not None and len(nf_group_id_list) < 1:
            raise ValueError("Invalid value for `nf_group_id_list`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._nf_group_id_list = nf_group_id_list
