# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.amf_info import AmfInfo  # noqa: F401,E501
from models.ausf_info import AusfInfo  # noqa: F401,E501
from models.bsf_info import BsfInfo  # noqa: F401,E501
from models.chf_info import ChfInfo  # noqa: F401,E501
from models.default_notification_subscription import DefaultNotificationSubscription  # noqa: F401,E501
from models.fqdn import Fqdn  # noqa: F401,E501
from models.gmlc_info import GmlcInfo  # noqa: F401,E501
from models.hss_info import HssInfo  # noqa: F401,E501
from models.lmf_info import LmfInfo  # noqa: F401,E501
from models.nef_info import NefInfo  # noqa: F401,E501
from models.nf_profile_plmn_list import NFProfilePlmnList  # noqa: F401,E501
from models.nf_profile_snpn_list import NFProfileSnpnList  # noqa: F401,E501
from models.nf_service import NFService  # noqa: F401,E501
from models.nf_status import NFStatus  # noqa: F401,E501
from models.nf_type import NFType  # noqa: F401,E501
from models.nrf_info import NrfInfo  # noqa: F401,E501
from models.nwdaf_info import NwdafInfo  # noqa: F401,E501
from models.pcf_info import PcfInfo  # noqa: F401,E501
from models.pcscf_info import PcscfInfo  # noqa: F401,E501
from models.plmn_snssai import PlmnSnssai  # noqa: F401,E501
from models.scp_info import ScpInfo  # noqa: F401,E501
from models.smf_info import SmfInfo  # noqa: F401,E501
from models.udm_info import UdmInfo  # noqa: F401,E501
from models.udr_info import UdrInfo  # noqa: F401,E501
from models.udsf_info import UdsfInfo  # noqa: F401,E501
from models.upf_info import UpfInfo  # noqa: F401,E501
from models.all_of_nf_profile_s_nssais_items import AllOfNFProfileSNssaisItems  # noqa: F401,E501
from models.all_of_nf_profile_ipv6_addresses_items import AllOfNFProfileIpv6AddressesItems  # noqa: F401,E501
from models.all_of_nf_profile_allowed_nssais_items import AllOfNFProfileAllowedNssaisItems  # noqa: F401,E501
import util


class NFProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nf_instance_id: str=None, nf_instance_name: str=None, nf_type: NFType=None, nf_status: NFStatus=None, heart_beat_timer: int=None, plmn_list: List[NFProfilePlmnList]=None, snpn_list: List[NFProfileSnpnList]=None, s_nssais: List[AllOfNFProfileSNssaisItems]=None, per_plmn_snssai_list: List[PlmnSnssai]=None, nsi_list: List[str]=None, fqdn: Fqdn=None, inter_plmn_fqdn: Fqdn=None, ipv4_addresses: List[str]=None, ipv6_addresses: List[AllOfNFProfileIpv6AddressesItems]=None, allowed_plmns: List[NFProfilePlmnList]=None, allowed_snpns: List[NFProfileSnpnList]=None, allowed_nf_types: List[NFType]=None, allowed_nf_domains: List[str]=None, allowed_nssais: List[AllOfNFProfileAllowedNssaisItems]=None, priority: int=None, capacity: int=None, load: int=None, load_time_stamp: datetime=None, locality: str=None, udr_info: UdrInfo=None, udr_info_list: Dict[str, UdrInfo]=None, udm_info: UdmInfo=None, udm_info_list: Dict[str, UdmInfo]=None, ausf_info: AusfInfo=None, ausf_info_list: Dict[str, AusfInfo]=None, amf_info: AmfInfo=None, amf_info_list: Dict[str, AmfInfo]=None, smf_info: SmfInfo=None, smf_info_list: Dict[str, SmfInfo]=None, upf_info: UpfInfo=None, upf_info_list: Dict[str, UpfInfo]=None, pcf_info: PcfInfo=None, pcf_info_list: Dict[str, PcfInfo]=None, bsf_info: BsfInfo=None, bsf_info_list: Dict[str, BsfInfo]=None, chf_info: ChfInfo=None, chf_info_list: Dict[str, ChfInfo]=None, nef_info: NefInfo=None, nrf_info: NrfInfo=None, udsf_info: UdsfInfo=None, udsf_info_list: Dict[str, UdsfInfo]=None, nwdaf_info: NwdafInfo=None, pcscf_info_list: Dict[str, PcscfInfo]=None, hss_info_list: Dict[str, HssInfo]=None, custom_info: object=None, recovery_time: datetime=None, nf_service_persistence: bool=False, nf_services: List[NFService]=None, nf_service_list: Dict[str, NFService]=None, nf_profile_changes_support_ind: bool=False, nf_profile_changes_ind: bool=False, default_notification_subscriptions: List[DefaultNotificationSubscription]=None, lmf_info: LmfInfo=None, gmlc_info: GmlcInfo=None, nf_set_id_list: List[str]=None, serving_scope: List[str]=None, lc_h_support_ind: bool=False, olc_h_support_ind: bool=False, nf_set_recovery_time_list: Dict[str, datetime]=None, service_set_recovery_time_list: Dict[str, datetime]=None, scp_domains: List[str]=None, scp_info: ScpInfo=None):  # noqa: E501
        """NFProfile - a model defined in Swagger

        :param nf_instance_id: The nf_instance_id of this NFProfile.  # noqa: E501
        :type nf_instance_id: str
        :param nf_instance_name: The nf_instance_name of this NFProfile.  # noqa: E501
        :type nf_instance_name: str
        :param nf_type: The nf_type of this NFProfile.  # noqa: E501
        :type nf_type: NFType
        :param nf_status: The nf_status of this NFProfile.  # noqa: E501
        :type nf_status: NFStatus
        :param heart_beat_timer: The heart_beat_timer of this NFProfile.  # noqa: E501
        :type heart_beat_timer: int
        :param plmn_list: The plmn_list of this NFProfile.  # noqa: E501
        :type plmn_list: List[NFProfilePlmnList]
        :param snpn_list: The snpn_list of this NFProfile.  # noqa: E501
        :type snpn_list: List[NFProfileSnpnList]
        :param s_nssais: The s_nssais of this NFProfile.  # noqa: E501
        :type s_nssais: List[AllOfNFProfileSNssaisItems]
        :param per_plmn_snssai_list: The per_plmn_snssai_list of this NFProfile.  # noqa: E501
        :type per_plmn_snssai_list: List[PlmnSnssai]
        :param nsi_list: The nsi_list of this NFProfile.  # noqa: E501
        :type nsi_list: List[str]
        :param fqdn: The fqdn of this NFProfile.  # noqa: E501
        :type fqdn: Fqdn
        :param inter_plmn_fqdn: The inter_plmn_fqdn of this NFProfile.  # noqa: E501
        :type inter_plmn_fqdn: Fqdn
        :param ipv4_addresses: The ipv4_addresses of this NFProfile.  # noqa: E501
        :type ipv4_addresses: List[str]
        :param ipv6_addresses: The ipv6_addresses of this NFProfile.  # noqa: E501
        :type ipv6_addresses: List[AllOfNFProfileIpv6AddressesItems]
        :param allowed_plmns: The allowed_plmns of this NFProfile.  # noqa: E501
        :type allowed_plmns: List[NFProfilePlmnList]
        :param allowed_snpns: The allowed_snpns of this NFProfile.  # noqa: E501
        :type allowed_snpns: List[NFProfileSnpnList]
        :param allowed_nf_types: The allowed_nf_types of this NFProfile.  # noqa: E501
        :type allowed_nf_types: List[NFType]
        :param allowed_nf_domains: The allowed_nf_domains of this NFProfile.  # noqa: E501
        :type allowed_nf_domains: List[str]
        :param allowed_nssais: The allowed_nssais of this NFProfile.  # noqa: E501
        :type allowed_nssais: List[AllOfNFProfileAllowedNssaisItems]
        :param priority: The priority of this NFProfile.  # noqa: E501
        :type priority: int
        :param capacity: The capacity of this NFProfile.  # noqa: E501
        :type capacity: int
        :param load: The load of this NFProfile.  # noqa: E501
        :type load: int
        :param load_time_stamp: The load_time_stamp of this NFProfile.  # noqa: E501
        :type load_time_stamp: datetime
        :param locality: The locality of this NFProfile.  # noqa: E501
        :type locality: str
        :param udr_info: The udr_info of this NFProfile.  # noqa: E501
        :type udr_info: UdrInfo
        :param udr_info_list: The udr_info_list of this NFProfile.  # noqa: E501
        :type udr_info_list: Dict[str, UdrInfo]
        :param udm_info: The udm_info of this NFProfile.  # noqa: E501
        :type udm_info: UdmInfo
        :param udm_info_list: The udm_info_list of this NFProfile.  # noqa: E501
        :type udm_info_list: Dict[str, UdmInfo]
        :param ausf_info: The ausf_info of this NFProfile.  # noqa: E501
        :type ausf_info: AusfInfo
        :param ausf_info_list: The ausf_info_list of this NFProfile.  # noqa: E501
        :type ausf_info_list: Dict[str, AusfInfo]
        :param amf_info: The amf_info of this NFProfile.  # noqa: E501
        :type amf_info: AmfInfo
        :param amf_info_list: The amf_info_list of this NFProfile.  # noqa: E501
        :type amf_info_list: Dict[str, AmfInfo]
        :param smf_info: The smf_info of this NFProfile.  # noqa: E501
        :type smf_info: SmfInfo
        :param smf_info_list: The smf_info_list of this NFProfile.  # noqa: E501
        :type smf_info_list: Dict[str, SmfInfo]
        :param upf_info: The upf_info of this NFProfile.  # noqa: E501
        :type upf_info: UpfInfo
        :param upf_info_list: The upf_info_list of this NFProfile.  # noqa: E501
        :type upf_info_list: Dict[str, UpfInfo]
        :param pcf_info: The pcf_info of this NFProfile.  # noqa: E501
        :type pcf_info: PcfInfo
        :param pcf_info_list: The pcf_info_list of this NFProfile.  # noqa: E501
        :type pcf_info_list: Dict[str, PcfInfo]
        :param bsf_info: The bsf_info of this NFProfile.  # noqa: E501
        :type bsf_info: BsfInfo
        :param bsf_info_list: The bsf_info_list of this NFProfile.  # noqa: E501
        :type bsf_info_list: Dict[str, BsfInfo]
        :param chf_info: The chf_info of this NFProfile.  # noqa: E501
        :type chf_info: ChfInfo
        :param chf_info_list: The chf_info_list of this NFProfile.  # noqa: E501
        :type chf_info_list: Dict[str, ChfInfo]
        :param nef_info: The nef_info of this NFProfile.  # noqa: E501
        :type nef_info: NefInfo
        :param nrf_info: The nrf_info of this NFProfile.  # noqa: E501
        :type nrf_info: NrfInfo
        :param udsf_info: The udsf_info of this NFProfile.  # noqa: E501
        :type udsf_info: UdsfInfo
        :param udsf_info_list: The udsf_info_list of this NFProfile.  # noqa: E501
        :type udsf_info_list: Dict[str, UdsfInfo]
        :param nwdaf_info: The nwdaf_info of this NFProfile.  # noqa: E501
        :type nwdaf_info: NwdafInfo
        :param pcscf_info_list: The pcscf_info_list of this NFProfile.  # noqa: E501
        :type pcscf_info_list: Dict[str, PcscfInfo]
        :param hss_info_list: The hss_info_list of this NFProfile.  # noqa: E501
        :type hss_info_list: Dict[str, HssInfo]
        :param custom_info: The custom_info of this NFProfile.  # noqa: E501
        :type custom_info: object
        :param recovery_time: The recovery_time of this NFProfile.  # noqa: E501
        :type recovery_time: datetime
        :param nf_service_persistence: The nf_service_persistence of this NFProfile.  # noqa: E501
        :type nf_service_persistence: bool
        :param nf_services: The nf_services of this NFProfile.  # noqa: E501
        :type nf_services: List[NFService]
        :param nf_service_list: The nf_service_list of this NFProfile.  # noqa: E501
        :type nf_service_list: Dict[str, NFService]
        :param nf_profile_changes_support_ind: The nf_profile_changes_support_ind of this NFProfile.  # noqa: E501
        :type nf_profile_changes_support_ind: bool
        :param nf_profile_changes_ind: The nf_profile_changes_ind of this NFProfile.  # noqa: E501
        :type nf_profile_changes_ind: bool
        :param default_notification_subscriptions: The default_notification_subscriptions of this NFProfile.  # noqa: E501
        :type default_notification_subscriptions: List[DefaultNotificationSubscription]
        :param lmf_info: The lmf_info of this NFProfile.  # noqa: E501
        :type lmf_info: LmfInfo
        :param gmlc_info: The gmlc_info of this NFProfile.  # noqa: E501
        :type gmlc_info: GmlcInfo
        :param nf_set_id_list: The nf_set_id_list of this NFProfile.  # noqa: E501
        :type nf_set_id_list: List[str]
        :param serving_scope: The serving_scope of this NFProfile.  # noqa: E501
        :type serving_scope: List[str]
        :param lc_h_support_ind: The lc_h_support_ind of this NFProfile.  # noqa: E501
        :type lc_h_support_ind: bool
        :param olc_h_support_ind: The olc_h_support_ind of this NFProfile.  # noqa: E501
        :type olc_h_support_ind: bool
        :param nf_set_recovery_time_list: The nf_set_recovery_time_list of this NFProfile.  # noqa: E501
        :type nf_set_recovery_time_list: Dict[str, datetime]
        :param service_set_recovery_time_list: The service_set_recovery_time_list of this NFProfile.  # noqa: E501
        :type service_set_recovery_time_list: Dict[str, datetime]
        :param scp_domains: The scp_domains of this NFProfile.  # noqa: E501
        :type scp_domains: List[str]
        :param scp_info: The scp_info of this NFProfile.  # noqa: E501
        :type scp_info: ScpInfo
        """
        self.openapi_types = {
            'nf_instance_id': str,
            'nf_instance_name': str,
            'nf_type': NFType,
            'nf_status': NFStatus,
            'heart_beat_timer': int,
            'plmn_list': List[NFProfilePlmnList],
            'snpn_list': List[NFProfileSnpnList],
            's_nssais': List[AllOfNFProfileSNssaisItems],
            'per_plmn_snssai_list': List[PlmnSnssai],
            'nsi_list': List[str],
            'fqdn': Fqdn,
            'inter_plmn_fqdn': Fqdn,
            'ipv4_addresses': List[str],
            'ipv6_addresses': List[AllOfNFProfileIpv6AddressesItems],
            'allowed_plmns': List[NFProfilePlmnList],
            'allowed_snpns': List[NFProfileSnpnList],
            'allowed_nf_types': List[NFType],
            'allowed_nf_domains': List[str],
            'allowed_nssais': List[AllOfNFProfileAllowedNssaisItems],
            'priority': int,
            'capacity': int,
            'load': int,
            'load_time_stamp': datetime,
            'locality': str,
            'udr_info': UdrInfo,
            'udr_info_list': Dict[str, UdrInfo],
            'udm_info': UdmInfo,
            'udm_info_list': Dict[str, UdmInfo],
            'ausf_info': AusfInfo,
            'ausf_info_list': Dict[str, AusfInfo],
            'amf_info': AmfInfo,
            'amf_info_list': Dict[str, AmfInfo],
            'smf_info': SmfInfo,
            'smf_info_list': Dict[str, SmfInfo],
            'upf_info': UpfInfo,
            'upf_info_list': Dict[str, UpfInfo],
            'pcf_info': PcfInfo,
            'pcf_info_list': Dict[str, PcfInfo],
            'bsf_info': BsfInfo,
            'bsf_info_list': Dict[str, BsfInfo],
            'chf_info': ChfInfo,
            'chf_info_list': Dict[str, ChfInfo],
            'nef_info': NefInfo,
            'nrf_info': NrfInfo,
            'udsf_info': UdsfInfo,
            'udsf_info_list': Dict[str, UdsfInfo],
            'nwdaf_info': NwdafInfo,
            'pcscf_info_list': Dict[str, PcscfInfo],
            'hss_info_list': Dict[str, HssInfo],
            'custom_info': object,
            'recovery_time': datetime,
            'nf_service_persistence': bool,
            'nf_services': List[NFService],
            'nf_service_list': Dict[str, NFService],
            'nf_profile_changes_support_ind': bool,
            'nf_profile_changes_ind': bool,
            'default_notification_subscriptions': List[DefaultNotificationSubscription],
            'lmf_info': LmfInfo,
            'gmlc_info': GmlcInfo,
            'nf_set_id_list': List[str],
            'serving_scope': List[str],
            'lc_h_support_ind': bool,
            'olc_h_support_ind': bool,
            'nf_set_recovery_time_list': Dict[str, datetime],
            'service_set_recovery_time_list': Dict[str, datetime],
            'scp_domains': List[str],
            'scp_info': ScpInfo
        }

        self.attribute_map = {
            'nf_instance_id': 'nfInstanceId',
            'nf_instance_name': 'nfInstanceName',
            'nf_type': 'nfType',
            'nf_status': 'nfStatus',
            'heart_beat_timer': 'heartBeatTimer',
            'plmn_list': 'plmnList',
            'snpn_list': 'snpnList',
            's_nssais': 'sNssais',
            'per_plmn_snssai_list': 'perPlmnSnssaiList',
            'nsi_list': 'nsiList',
            'fqdn': 'fqdn',
            'inter_plmn_fqdn': 'interPlmnFqdn',
            'ipv4_addresses': 'ipv4Addresses',
            'ipv6_addresses': 'ipv6Addresses',
            'allowed_plmns': 'allowedPlmns',
            'allowed_snpns': 'allowedSnpns',
            'allowed_nf_types': 'allowedNfTypes',
            'allowed_nf_domains': 'allowedNfDomains',
            'allowed_nssais': 'allowedNssais',
            'priority': 'priority',
            'capacity': 'capacity',
            'load': 'load',
            'load_time_stamp': 'loadTimeStamp',
            'locality': 'locality',
            'udr_info': 'udrInfo',
            'udr_info_list': 'udrInfoList',
            'udm_info': 'udmInfo',
            'udm_info_list': 'udmInfoList',
            'ausf_info': 'ausfInfo',
            'ausf_info_list': 'ausfInfoList',
            'amf_info': 'amfInfo',
            'amf_info_list': 'amfInfoList',
            'smf_info': 'smfInfo',
            'smf_info_list': 'smfInfoList',
            'upf_info': 'upfInfo',
            'upf_info_list': 'upfInfoList',
            'pcf_info': 'pcfInfo',
            'pcf_info_list': 'pcfInfoList',
            'bsf_info': 'bsfInfo',
            'bsf_info_list': 'bsfInfoList',
            'chf_info': 'chfInfo',
            'chf_info_list': 'chfInfoList',
            'nef_info': 'nefInfo',
            'nrf_info': 'nrfInfo',
            'udsf_info': 'udsfInfo',
            'udsf_info_list': 'udsfInfoList',
            'nwdaf_info': 'nwdafInfo',
            'pcscf_info_list': 'pcscfInfoList',
            'hss_info_list': 'hssInfoList',
            'custom_info': 'customInfo',
            'recovery_time': 'recoveryTime',
            'nf_service_persistence': 'nfServicePersistence',
            'nf_services': 'nfServices',
            'nf_service_list': 'nfServiceList',
            'nf_profile_changes_support_ind': 'nfProfileChangesSupportInd',
            'nf_profile_changes_ind': 'nfProfileChangesInd',
            'default_notification_subscriptions': 'defaultNotificationSubscriptions',
            'lmf_info': 'lmfInfo',
            'gmlc_info': 'gmlcInfo',
            'nf_set_id_list': 'nfSetIdList',
            'serving_scope': 'servingScope',
            'lc_h_support_ind': 'lcHSupportInd',
            'olc_h_support_ind': 'olcHSupportInd',
            'nf_set_recovery_time_list': 'nfSetRecoveryTimeList',
            'service_set_recovery_time_list': 'serviceSetRecoveryTimeList',
            'scp_domains': 'scpDomains',
            'scp_info': 'scpInfo'
        }
        self._nf_instance_id = nf_instance_id
        self._nf_instance_name = nf_instance_name
        self._nf_type = nf_type
        self._nf_status = nf_status
        self._heart_beat_timer = heart_beat_timer
        self._plmn_list = plmn_list
        self._snpn_list = snpn_list
        self._s_nssais = s_nssais
        self._per_plmn_snssai_list = per_plmn_snssai_list
        self._nsi_list = nsi_list
        self._fqdn = fqdn
        self._inter_plmn_fqdn = inter_plmn_fqdn
        self._ipv4_addresses = ipv4_addresses
        self._ipv6_addresses = ipv6_addresses
        self._allowed_plmns = allowed_plmns
        self._allowed_snpns = allowed_snpns
        self._allowed_nf_types = allowed_nf_types
        self._allowed_nf_domains = allowed_nf_domains
        self._allowed_nssais = allowed_nssais
        self._priority = priority
        self._capacity = capacity
        self._load = load
        self._load_time_stamp = load_time_stamp
        self._locality = locality
        self._udr_info = udr_info
        self._udr_info_list = udr_info_list
        self._udm_info = udm_info
        self._udm_info_list = udm_info_list
        self._ausf_info = ausf_info
        self._ausf_info_list = ausf_info_list
        self._amf_info = amf_info
        self._amf_info_list = amf_info_list
        self._smf_info = smf_info
        self._smf_info_list = smf_info_list
        self._upf_info = upf_info
        self._upf_info_list = upf_info_list
        self._pcf_info = pcf_info
        self._pcf_info_list = pcf_info_list
        self._bsf_info = bsf_info
        self._bsf_info_list = bsf_info_list
        self._chf_info = chf_info
        self._chf_info_list = chf_info_list
        self._nef_info = nef_info
        self._nrf_info = nrf_info
        self._udsf_info = udsf_info
        self._udsf_info_list = udsf_info_list
        self._nwdaf_info = nwdaf_info
        self._pcscf_info_list = pcscf_info_list
        self._hss_info_list = hss_info_list
        self._custom_info = custom_info
        self._recovery_time = recovery_time
        self._nf_service_persistence = nf_service_persistence
        self._nf_services = nf_services
        self._nf_service_list = nf_service_list
        self._nf_profile_changes_support_ind = nf_profile_changes_support_ind
        self._nf_profile_changes_ind = nf_profile_changes_ind
        self._default_notification_subscriptions = default_notification_subscriptions
        self._lmf_info = lmf_info
        self._gmlc_info = gmlc_info
        self._nf_set_id_list = nf_set_id_list
        self._serving_scope = serving_scope
        self._lc_h_support_ind = lc_h_support_ind
        self._olc_h_support_ind = olc_h_support_ind
        self._nf_set_recovery_time_list = nf_set_recovery_time_list
        self._service_set_recovery_time_list = service_set_recovery_time_list
        self._scp_domains = scp_domains
        self._scp_info = scp_info

    @classmethod
    def from_dict(cls, dikt) -> 'NFProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NFProfile of this NFProfile.  # noqa: E501
        :rtype: NFProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nf_instance_id(self) -> str:
        """Gets the nf_instance_id of this NFProfile.

        String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.    # noqa: E501

        :return: The nf_instance_id of this NFProfile.
        :rtype: str
        """
        return self._nf_instance_id

    @nf_instance_id.setter
    def nf_instance_id(self, nf_instance_id: str):
        """Sets the nf_instance_id of this NFProfile.

        String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.    # noqa: E501

        :param nf_instance_id: The nf_instance_id of this NFProfile.
        :type nf_instance_id: str
        """
        if nf_instance_id is None:
            raise ValueError("Invalid value for `nf_instance_id`, must not be `None`")  # noqa: E501

        self._nf_instance_id = nf_instance_id

    @property
    def nf_instance_name(self) -> str:
        """Gets the nf_instance_name of this NFProfile.


        :return: The nf_instance_name of this NFProfile.
        :rtype: str
        """
        return self._nf_instance_name

    @nf_instance_name.setter
    def nf_instance_name(self, nf_instance_name: str):
        """Sets the nf_instance_name of this NFProfile.


        :param nf_instance_name: The nf_instance_name of this NFProfile.
        :type nf_instance_name: str
        """

        self._nf_instance_name = nf_instance_name

    @property
    def nf_type(self) -> NFType:
        """Gets the nf_type of this NFProfile.


        :return: The nf_type of this NFProfile.
        :rtype: NFType
        """
        return self._nf_type

    @nf_type.setter
    def nf_type(self, nf_type: NFType):
        """Sets the nf_type of this NFProfile.


        :param nf_type: The nf_type of this NFProfile.
        :type nf_type: NFType
        """
        if nf_type is None:
            raise ValueError("Invalid value for `nf_type`, must not be `None`")  # noqa: E501

        self._nf_type = nf_type

    @property
    def nf_status(self) -> NFStatus:
        """Gets the nf_status of this NFProfile.


        :return: The nf_status of this NFProfile.
        :rtype: NFStatus
        """
        return self._nf_status

    @nf_status.setter
    def nf_status(self, nf_status: NFStatus):
        """Sets the nf_status of this NFProfile.


        :param nf_status: The nf_status of this NFProfile.
        :type nf_status: NFStatus
        """
        if nf_status is None:
            raise ValueError("Invalid value for `nf_status`, must not be `None`")  # noqa: E501

        self._nf_status = nf_status

    @property
    def heart_beat_timer(self) -> int:
        """Gets the heart_beat_timer of this NFProfile.


        :return: The heart_beat_timer of this NFProfile.
        :rtype: int
        """
        return self._heart_beat_timer

    @heart_beat_timer.setter
    def heart_beat_timer(self, heart_beat_timer: int):
        """Sets the heart_beat_timer of this NFProfile.


        :param heart_beat_timer: The heart_beat_timer of this NFProfile.
        :type heart_beat_timer: int
        """

        self._heart_beat_timer = heart_beat_timer

    @property
    def plmn_list(self) -> List[NFProfilePlmnList]:
        """Gets the plmn_list of this NFProfile.


        :return: The plmn_list of this NFProfile.
        :rtype: List[NFProfilePlmnList]
        """
        return self._plmn_list

    @plmn_list.setter
    def plmn_list(self, plmn_list: List[NFProfilePlmnList]):
        """Sets the plmn_list of this NFProfile.


        :param plmn_list: The plmn_list of this NFProfile.
        :type plmn_list: List[NFProfilePlmnList]
        """

        self._plmn_list = plmn_list

    @property
    def snpn_list(self) -> List[NFProfileSnpnList]:
        """Gets the snpn_list of this NFProfile.


        :return: The snpn_list of this NFProfile.
        :rtype: List[NFProfileSnpnList]
        """
        return self._snpn_list

    @snpn_list.setter
    def snpn_list(self, snpn_list: List[NFProfileSnpnList]):
        """Sets the snpn_list of this NFProfile.


        :param snpn_list: The snpn_list of this NFProfile.
        :type snpn_list: List[NFProfileSnpnList]
        """

        self._snpn_list = snpn_list

    @property
    def s_nssais(self) -> List[AllOfNFProfileSNssaisItems]:
        """Gets the s_nssais of this NFProfile.


        :return: The s_nssais of this NFProfile.
        :rtype: List[AllOfNFProfileSNssaisItems]
        """
        return self._s_nssais

    @s_nssais.setter
    def s_nssais(self, s_nssais: List[AllOfNFProfileSNssaisItems]):
        """Sets the s_nssais of this NFProfile.


        :param s_nssais: The s_nssais of this NFProfile.
        :type s_nssais: List[AllOfNFProfileSNssaisItems]
        """

        self._s_nssais = s_nssais

    @property
    def per_plmn_snssai_list(self) -> List[PlmnSnssai]:
        """Gets the per_plmn_snssai_list of this NFProfile.


        :return: The per_plmn_snssai_list of this NFProfile.
        :rtype: List[PlmnSnssai]
        """
        return self._per_plmn_snssai_list

    @per_plmn_snssai_list.setter
    def per_plmn_snssai_list(self, per_plmn_snssai_list: List[PlmnSnssai]):
        """Sets the per_plmn_snssai_list of this NFProfile.


        :param per_plmn_snssai_list: The per_plmn_snssai_list of this NFProfile.
        :type per_plmn_snssai_list: List[PlmnSnssai]
        """

        self._per_plmn_snssai_list = per_plmn_snssai_list

    @property
    def nsi_list(self) -> List[str]:
        """Gets the nsi_list of this NFProfile.


        :return: The nsi_list of this NFProfile.
        :rtype: List[str]
        """
        return self._nsi_list

    @nsi_list.setter
    def nsi_list(self, nsi_list: List[str]):
        """Sets the nsi_list of this NFProfile.


        :param nsi_list: The nsi_list of this NFProfile.
        :type nsi_list: List[str]
        """

        self._nsi_list = nsi_list

    @property
    def fqdn(self) -> Fqdn:
        """Gets the fqdn of this NFProfile.


        :return: The fqdn of this NFProfile.
        :rtype: Fqdn
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn: Fqdn):
        """Sets the fqdn of this NFProfile.


        :param fqdn: The fqdn of this NFProfile.
        :type fqdn: Fqdn
        """

        self._fqdn = fqdn

    @property
    def inter_plmn_fqdn(self) -> Fqdn:
        """Gets the inter_plmn_fqdn of this NFProfile.


        :return: The inter_plmn_fqdn of this NFProfile.
        :rtype: Fqdn
        """
        return self._inter_plmn_fqdn

    @inter_plmn_fqdn.setter
    def inter_plmn_fqdn(self, inter_plmn_fqdn: Fqdn):
        """Sets the inter_plmn_fqdn of this NFProfile.


        :param inter_plmn_fqdn: The inter_plmn_fqdn of this NFProfile.
        :type inter_plmn_fqdn: Fqdn
        """

        self._inter_plmn_fqdn = inter_plmn_fqdn

    @property
    def ipv4_addresses(self) -> List[str]:
        """Gets the ipv4_addresses of this NFProfile.


        :return: The ipv4_addresses of this NFProfile.
        :rtype: List[str]
        """
        return self._ipv4_addresses

    @ipv4_addresses.setter
    def ipv4_addresses(self, ipv4_addresses: List[str]):
        """Sets the ipv4_addresses of this NFProfile.


        :param ipv4_addresses: The ipv4_addresses of this NFProfile.
        :type ipv4_addresses: List[str]
        """

        self._ipv4_addresses = ipv4_addresses

    @property
    def ipv6_addresses(self) -> List[AllOfNFProfileIpv6AddressesItems]:
        """Gets the ipv6_addresses of this NFProfile.


        :return: The ipv6_addresses of this NFProfile.
        :rtype: List[AllOfNFProfileIpv6AddressesItems]
        """
        return self._ipv6_addresses

    @ipv6_addresses.setter
    def ipv6_addresses(self, ipv6_addresses: List[AllOfNFProfileIpv6AddressesItems]):
        """Sets the ipv6_addresses of this NFProfile.


        :param ipv6_addresses: The ipv6_addresses of this NFProfile.
        :type ipv6_addresses: List[AllOfNFProfileIpv6AddressesItems]
        """

        self._ipv6_addresses = ipv6_addresses

    @property
    def allowed_plmns(self) -> List[NFProfilePlmnList]:
        """Gets the allowed_plmns of this NFProfile.


        :return: The allowed_plmns of this NFProfile.
        :rtype: List[NFProfilePlmnList]
        """
        return self._allowed_plmns

    @allowed_plmns.setter
    def allowed_plmns(self, allowed_plmns: List[NFProfilePlmnList]):
        """Sets the allowed_plmns of this NFProfile.


        :param allowed_plmns: The allowed_plmns of this NFProfile.
        :type allowed_plmns: List[NFProfilePlmnList]
        """

        self._allowed_plmns = allowed_plmns

    @property
    def allowed_snpns(self) -> List[NFProfileSnpnList]:
        """Gets the allowed_snpns of this NFProfile.


        :return: The allowed_snpns of this NFProfile.
        :rtype: List[NFProfileSnpnList]
        """
        return self._allowed_snpns

    @allowed_snpns.setter
    def allowed_snpns(self, allowed_snpns: List[NFProfileSnpnList]):
        """Sets the allowed_snpns of this NFProfile.


        :param allowed_snpns: The allowed_snpns of this NFProfile.
        :type allowed_snpns: List[NFProfileSnpnList]
        """

        self._allowed_snpns = allowed_snpns

    @property
    def allowed_nf_types(self) -> List[NFType]:
        """Gets the allowed_nf_types of this NFProfile.


        :return: The allowed_nf_types of this NFProfile.
        :rtype: List[NFType]
        """
        return self._allowed_nf_types

    @allowed_nf_types.setter
    def allowed_nf_types(self, allowed_nf_types: List[NFType]):
        """Sets the allowed_nf_types of this NFProfile.


        :param allowed_nf_types: The allowed_nf_types of this NFProfile.
        :type allowed_nf_types: List[NFType]
        """

        self._allowed_nf_types = allowed_nf_types

    @property
    def allowed_nf_domains(self) -> List[str]:
        """Gets the allowed_nf_domains of this NFProfile.


        :return: The allowed_nf_domains of this NFProfile.
        :rtype: List[str]
        """
        return self._allowed_nf_domains

    @allowed_nf_domains.setter
    def allowed_nf_domains(self, allowed_nf_domains: List[str]):
        """Sets the allowed_nf_domains of this NFProfile.


        :param allowed_nf_domains: The allowed_nf_domains of this NFProfile.
        :type allowed_nf_domains: List[str]
        """

        self._allowed_nf_domains = allowed_nf_domains

    @property
    def allowed_nssais(self) -> List[AllOfNFProfileAllowedNssaisItems]:
        """Gets the allowed_nssais of this NFProfile.


        :return: The allowed_nssais of this NFProfile.
        :rtype: List[AllOfNFProfileAllowedNssaisItems]
        """
        return self._allowed_nssais

    @allowed_nssais.setter
    def allowed_nssais(self, allowed_nssais: List[AllOfNFProfileAllowedNssaisItems]):
        """Sets the allowed_nssais of this NFProfile.


        :param allowed_nssais: The allowed_nssais of this NFProfile.
        :type allowed_nssais: List[AllOfNFProfileAllowedNssaisItems]
        """

        self._allowed_nssais = allowed_nssais

    @property
    def priority(self) -> int:
        """Gets the priority of this NFProfile.


        :return: The priority of this NFProfile.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this NFProfile.


        :param priority: The priority of this NFProfile.
        :type priority: int
        """

        self._priority = priority

    @property
    def capacity(self) -> int:
        """Gets the capacity of this NFProfile.


        :return: The capacity of this NFProfile.
        :rtype: int
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity: int):
        """Sets the capacity of this NFProfile.


        :param capacity: The capacity of this NFProfile.
        :type capacity: int
        """

        self._capacity = capacity

    @property
    def load(self) -> int:
        """Gets the load of this NFProfile.


        :return: The load of this NFProfile.
        :rtype: int
        """
        return self._load

    @load.setter
    def load(self, load: int):
        """Sets the load of this NFProfile.


        :param load: The load of this NFProfile.
        :type load: int
        """

        self._load = load

    @property
    def load_time_stamp(self) -> datetime:
        """Gets the load_time_stamp of this NFProfile.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The load_time_stamp of this NFProfile.
        :rtype: datetime
        """
        return self._load_time_stamp

    @load_time_stamp.setter
    def load_time_stamp(self, load_time_stamp: datetime):
        """Sets the load_time_stamp of this NFProfile.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param load_time_stamp: The load_time_stamp of this NFProfile.
        :type load_time_stamp: datetime
        """

        self._load_time_stamp = load_time_stamp

    @property
    def locality(self) -> str:
        """Gets the locality of this NFProfile.


        :return: The locality of this NFProfile.
        :rtype: str
        """
        return self._locality

    @locality.setter
    def locality(self, locality: str):
        """Sets the locality of this NFProfile.


        :param locality: The locality of this NFProfile.
        :type locality: str
        """

        self._locality = locality

    @property
    def udr_info(self) -> UdrInfo:
        """Gets the udr_info of this NFProfile.


        :return: The udr_info of this NFProfile.
        :rtype: UdrInfo
        """
        return self._udr_info

    @udr_info.setter
    def udr_info(self, udr_info: UdrInfo):
        """Sets the udr_info of this NFProfile.


        :param udr_info: The udr_info of this NFProfile.
        :type udr_info: UdrInfo
        """

        self._udr_info = udr_info

    @property
    def udr_info_list(self) -> Dict[str, UdrInfo]:
        """Gets the udr_info_list of this NFProfile.


        :return: The udr_info_list of this NFProfile.
        :rtype: Dict[str, UdrInfo]
        """
        return self._udr_info_list

    @udr_info_list.setter
    def udr_info_list(self, udr_info_list: Dict[str, UdrInfo]):
        """Sets the udr_info_list of this NFProfile.


        :param udr_info_list: The udr_info_list of this NFProfile.
        :type udr_info_list: Dict[str, UdrInfo]
        """

        self._udr_info_list = udr_info_list

    @property
    def udm_info(self) -> UdmInfo:
        """Gets the udm_info of this NFProfile.


        :return: The udm_info of this NFProfile.
        :rtype: UdmInfo
        """
        return self._udm_info

    @udm_info.setter
    def udm_info(self, udm_info: UdmInfo):
        """Sets the udm_info of this NFProfile.


        :param udm_info: The udm_info of this NFProfile.
        :type udm_info: UdmInfo
        """

        self._udm_info = udm_info

    @property
    def udm_info_list(self) -> Dict[str, UdmInfo]:
        """Gets the udm_info_list of this NFProfile.


        :return: The udm_info_list of this NFProfile.
        :rtype: Dict[str, UdmInfo]
        """
        return self._udm_info_list

    @udm_info_list.setter
    def udm_info_list(self, udm_info_list: Dict[str, UdmInfo]):
        """Sets the udm_info_list of this NFProfile.


        :param udm_info_list: The udm_info_list of this NFProfile.
        :type udm_info_list: Dict[str, UdmInfo]
        """

        self._udm_info_list = udm_info_list

    @property
    def ausf_info(self) -> AusfInfo:
        """Gets the ausf_info of this NFProfile.


        :return: The ausf_info of this NFProfile.
        :rtype: AusfInfo
        """
        return self._ausf_info

    @ausf_info.setter
    def ausf_info(self, ausf_info: AusfInfo):
        """Sets the ausf_info of this NFProfile.


        :param ausf_info: The ausf_info of this NFProfile.
        :type ausf_info: AusfInfo
        """

        self._ausf_info = ausf_info

    @property
    def ausf_info_list(self) -> Dict[str, AusfInfo]:
        """Gets the ausf_info_list of this NFProfile.


        :return: The ausf_info_list of this NFProfile.
        :rtype: Dict[str, AusfInfo]
        """
        return self._ausf_info_list

    @ausf_info_list.setter
    def ausf_info_list(self, ausf_info_list: Dict[str, AusfInfo]):
        """Sets the ausf_info_list of this NFProfile.


        :param ausf_info_list: The ausf_info_list of this NFProfile.
        :type ausf_info_list: Dict[str, AusfInfo]
        """

        self._ausf_info_list = ausf_info_list

    @property
    def amf_info(self) -> AmfInfo:
        """Gets the amf_info of this NFProfile.


        :return: The amf_info of this NFProfile.
        :rtype: AmfInfo
        """
        return self._amf_info

    @amf_info.setter
    def amf_info(self, amf_info: AmfInfo):
        """Sets the amf_info of this NFProfile.


        :param amf_info: The amf_info of this NFProfile.
        :type amf_info: AmfInfo
        """

        self._amf_info = amf_info

    @property
    def amf_info_list(self) -> Dict[str, AmfInfo]:
        """Gets the amf_info_list of this NFProfile.


        :return: The amf_info_list of this NFProfile.
        :rtype: Dict[str, AmfInfo]
        """
        return self._amf_info_list

    @amf_info_list.setter
    def amf_info_list(self, amf_info_list: Dict[str, AmfInfo]):
        """Sets the amf_info_list of this NFProfile.


        :param amf_info_list: The amf_info_list of this NFProfile.
        :type amf_info_list: Dict[str, AmfInfo]
        """

        self._amf_info_list = amf_info_list

    @property
    def smf_info(self) -> SmfInfo:
        """Gets the smf_info of this NFProfile.


        :return: The smf_info of this NFProfile.
        :rtype: SmfInfo
        """
        return self._smf_info

    @smf_info.setter
    def smf_info(self, smf_info: SmfInfo):
        """Sets the smf_info of this NFProfile.


        :param smf_info: The smf_info of this NFProfile.
        :type smf_info: SmfInfo
        """

        self._smf_info = smf_info

    @property
    def smf_info_list(self) -> Dict[str, SmfInfo]:
        """Gets the smf_info_list of this NFProfile.


        :return: The smf_info_list of this NFProfile.
        :rtype: Dict[str, SmfInfo]
        """
        return self._smf_info_list

    @smf_info_list.setter
    def smf_info_list(self, smf_info_list: Dict[str, SmfInfo]):
        """Sets the smf_info_list of this NFProfile.


        :param smf_info_list: The smf_info_list of this NFProfile.
        :type smf_info_list: Dict[str, SmfInfo]
        """

        self._smf_info_list = smf_info_list

    @property
    def upf_info(self) -> UpfInfo:
        """Gets the upf_info of this NFProfile.


        :return: The upf_info of this NFProfile.
        :rtype: UpfInfo
        """
        return self._upf_info

    @upf_info.setter
    def upf_info(self, upf_info: UpfInfo):
        """Sets the upf_info of this NFProfile.


        :param upf_info: The upf_info of this NFProfile.
        :type upf_info: UpfInfo
        """

        self._upf_info = upf_info

    @property
    def upf_info_list(self) -> Dict[str, UpfInfo]:
        """Gets the upf_info_list of this NFProfile.


        :return: The upf_info_list of this NFProfile.
        :rtype: Dict[str, UpfInfo]
        """
        return self._upf_info_list

    @upf_info_list.setter
    def upf_info_list(self, upf_info_list: Dict[str, UpfInfo]):
        """Sets the upf_info_list of this NFProfile.


        :param upf_info_list: The upf_info_list of this NFProfile.
        :type upf_info_list: Dict[str, UpfInfo]
        """

        self._upf_info_list = upf_info_list

    @property
    def pcf_info(self) -> PcfInfo:
        """Gets the pcf_info of this NFProfile.


        :return: The pcf_info of this NFProfile.
        :rtype: PcfInfo
        """
        return self._pcf_info

    @pcf_info.setter
    def pcf_info(self, pcf_info: PcfInfo):
        """Sets the pcf_info of this NFProfile.


        :param pcf_info: The pcf_info of this NFProfile.
        :type pcf_info: PcfInfo
        """

        self._pcf_info = pcf_info

    @property
    def pcf_info_list(self) -> Dict[str, PcfInfo]:
        """Gets the pcf_info_list of this NFProfile.


        :return: The pcf_info_list of this NFProfile.
        :rtype: Dict[str, PcfInfo]
        """
        return self._pcf_info_list

    @pcf_info_list.setter
    def pcf_info_list(self, pcf_info_list: Dict[str, PcfInfo]):
        """Sets the pcf_info_list of this NFProfile.


        :param pcf_info_list: The pcf_info_list of this NFProfile.
        :type pcf_info_list: Dict[str, PcfInfo]
        """

        self._pcf_info_list = pcf_info_list

    @property
    def bsf_info(self) -> BsfInfo:
        """Gets the bsf_info of this NFProfile.


        :return: The bsf_info of this NFProfile.
        :rtype: BsfInfo
        """
        return self._bsf_info

    @bsf_info.setter
    def bsf_info(self, bsf_info: BsfInfo):
        """Sets the bsf_info of this NFProfile.


        :param bsf_info: The bsf_info of this NFProfile.
        :type bsf_info: BsfInfo
        """

        self._bsf_info = bsf_info

    @property
    def bsf_info_list(self) -> Dict[str, BsfInfo]:
        """Gets the bsf_info_list of this NFProfile.


        :return: The bsf_info_list of this NFProfile.
        :rtype: Dict[str, BsfInfo]
        """
        return self._bsf_info_list

    @bsf_info_list.setter
    def bsf_info_list(self, bsf_info_list: Dict[str, BsfInfo]):
        """Sets the bsf_info_list of this NFProfile.


        :param bsf_info_list: The bsf_info_list of this NFProfile.
        :type bsf_info_list: Dict[str, BsfInfo]
        """

        self._bsf_info_list = bsf_info_list

    @property
    def chf_info(self) -> ChfInfo:
        """Gets the chf_info of this NFProfile.


        :return: The chf_info of this NFProfile.
        :rtype: ChfInfo
        """
        return self._chf_info

    @chf_info.setter
    def chf_info(self, chf_info: ChfInfo):
        """Sets the chf_info of this NFProfile.


        :param chf_info: The chf_info of this NFProfile.
        :type chf_info: ChfInfo
        """

        self._chf_info = chf_info

    @property
    def chf_info_list(self) -> Dict[str, ChfInfo]:
        """Gets the chf_info_list of this NFProfile.


        :return: The chf_info_list of this NFProfile.
        :rtype: Dict[str, ChfInfo]
        """
        return self._chf_info_list

    @chf_info_list.setter
    def chf_info_list(self, chf_info_list: Dict[str, ChfInfo]):
        """Sets the chf_info_list of this NFProfile.


        :param chf_info_list: The chf_info_list of this NFProfile.
        :type chf_info_list: Dict[str, ChfInfo]
        """

        self._chf_info_list = chf_info_list

    @property
    def nef_info(self) -> NefInfo:
        """Gets the nef_info of this NFProfile.


        :return: The nef_info of this NFProfile.
        :rtype: NefInfo
        """
        return self._nef_info

    @nef_info.setter
    def nef_info(self, nef_info: NefInfo):
        """Sets the nef_info of this NFProfile.


        :param nef_info: The nef_info of this NFProfile.
        :type nef_info: NefInfo
        """

        self._nef_info = nef_info

    @property
    def nrf_info(self) -> NrfInfo:
        """Gets the nrf_info of this NFProfile.


        :return: The nrf_info of this NFProfile.
        :rtype: NrfInfo
        """
        return self._nrf_info

    @nrf_info.setter
    def nrf_info(self, nrf_info: NrfInfo):
        """Sets the nrf_info of this NFProfile.


        :param nrf_info: The nrf_info of this NFProfile.
        :type nrf_info: NrfInfo
        """

        self._nrf_info = nrf_info

    @property
    def udsf_info(self) -> UdsfInfo:
        """Gets the udsf_info of this NFProfile.


        :return: The udsf_info of this NFProfile.
        :rtype: UdsfInfo
        """
        return self._udsf_info

    @udsf_info.setter
    def udsf_info(self, udsf_info: UdsfInfo):
        """Sets the udsf_info of this NFProfile.


        :param udsf_info: The udsf_info of this NFProfile.
        :type udsf_info: UdsfInfo
        """

        self._udsf_info = udsf_info

    @property
    def udsf_info_list(self) -> Dict[str, UdsfInfo]:
        """Gets the udsf_info_list of this NFProfile.


        :return: The udsf_info_list of this NFProfile.
        :rtype: Dict[str, UdsfInfo]
        """
        return self._udsf_info_list

    @udsf_info_list.setter
    def udsf_info_list(self, udsf_info_list: Dict[str, UdsfInfo]):
        """Sets the udsf_info_list of this NFProfile.


        :param udsf_info_list: The udsf_info_list of this NFProfile.
        :type udsf_info_list: Dict[str, UdsfInfo]
        """

        self._udsf_info_list = udsf_info_list

    @property
    def nwdaf_info(self) -> NwdafInfo:
        """Gets the nwdaf_info of this NFProfile.


        :return: The nwdaf_info of this NFProfile.
        :rtype: NwdafInfo
        """
        return self._nwdaf_info

    @nwdaf_info.setter
    def nwdaf_info(self, nwdaf_info: NwdafInfo):
        """Sets the nwdaf_info of this NFProfile.


        :param nwdaf_info: The nwdaf_info of this NFProfile.
        :type nwdaf_info: NwdafInfo
        """

        self._nwdaf_info = nwdaf_info

    @property
    def pcscf_info_list(self) -> Dict[str, PcscfInfo]:
        """Gets the pcscf_info_list of this NFProfile.


        :return: The pcscf_info_list of this NFProfile.
        :rtype: Dict[str, PcscfInfo]
        """
        return self._pcscf_info_list

    @pcscf_info_list.setter
    def pcscf_info_list(self, pcscf_info_list: Dict[str, PcscfInfo]):
        """Sets the pcscf_info_list of this NFProfile.


        :param pcscf_info_list: The pcscf_info_list of this NFProfile.
        :type pcscf_info_list: Dict[str, PcscfInfo]
        """

        self._pcscf_info_list = pcscf_info_list

    @property
    def hss_info_list(self) -> Dict[str, HssInfo]:
        """Gets the hss_info_list of this NFProfile.


        :return: The hss_info_list of this NFProfile.
        :rtype: Dict[str, HssInfo]
        """
        return self._hss_info_list

    @hss_info_list.setter
    def hss_info_list(self, hss_info_list: Dict[str, HssInfo]):
        """Sets the hss_info_list of this NFProfile.


        :param hss_info_list: The hss_info_list of this NFProfile.
        :type hss_info_list: Dict[str, HssInfo]
        """

        self._hss_info_list = hss_info_list

    @property
    def custom_info(self) -> object:
        """Gets the custom_info of this NFProfile.


        :return: The custom_info of this NFProfile.
        :rtype: object
        """
        return self._custom_info

    @custom_info.setter
    def custom_info(self, custom_info: object):
        """Sets the custom_info of this NFProfile.


        :param custom_info: The custom_info of this NFProfile.
        :type custom_info: object
        """

        self._custom_info = custom_info

    @property
    def recovery_time(self) -> datetime:
        """Gets the recovery_time of this NFProfile.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The recovery_time of this NFProfile.
        :rtype: datetime
        """
        return self._recovery_time

    @recovery_time.setter
    def recovery_time(self, recovery_time: datetime):
        """Sets the recovery_time of this NFProfile.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param recovery_time: The recovery_time of this NFProfile.
        :type recovery_time: datetime
        """

        self._recovery_time = recovery_time

    @property
    def nf_service_persistence(self) -> bool:
        """Gets the nf_service_persistence of this NFProfile.


        :return: The nf_service_persistence of this NFProfile.
        :rtype: bool
        """
        return self._nf_service_persistence

    @nf_service_persistence.setter
    def nf_service_persistence(self, nf_service_persistence: bool):
        """Sets the nf_service_persistence of this NFProfile.


        :param nf_service_persistence: The nf_service_persistence of this NFProfile.
        :type nf_service_persistence: bool
        """

        self._nf_service_persistence = nf_service_persistence

    @property
    def nf_services(self) -> List[NFService]:
        """Gets the nf_services of this NFProfile.


        :return: The nf_services of this NFProfile.
        :rtype: List[NFService]
        """
        return self._nf_services

    @nf_services.setter
    def nf_services(self, nf_services: List[NFService]):
        """Sets the nf_services of this NFProfile.


        :param nf_services: The nf_services of this NFProfile.
        :type nf_services: List[NFService]
        """

        self._nf_services = nf_services

    @property
    def nf_service_list(self) -> Dict[str, NFService]:
        """Gets the nf_service_list of this NFProfile.


        :return: The nf_service_list of this NFProfile.
        :rtype: Dict[str, NFService]
        """
        return self._nf_service_list

    @nf_service_list.setter
    def nf_service_list(self, nf_service_list: Dict[str, NFService]):
        """Sets the nf_service_list of this NFProfile.


        :param nf_service_list: The nf_service_list of this NFProfile.
        :type nf_service_list: Dict[str, NFService]
        """

        self._nf_service_list = nf_service_list

    @property
    def nf_profile_changes_support_ind(self) -> bool:
        """Gets the nf_profile_changes_support_ind of this NFProfile.


        :return: The nf_profile_changes_support_ind of this NFProfile.
        :rtype: bool
        """
        return self._nf_profile_changes_support_ind

    @nf_profile_changes_support_ind.setter
    def nf_profile_changes_support_ind(self, nf_profile_changes_support_ind: bool):
        """Sets the nf_profile_changes_support_ind of this NFProfile.


        :param nf_profile_changes_support_ind: The nf_profile_changes_support_ind of this NFProfile.
        :type nf_profile_changes_support_ind: bool
        """

        self._nf_profile_changes_support_ind = nf_profile_changes_support_ind

    @property
    def nf_profile_changes_ind(self) -> bool:
        """Gets the nf_profile_changes_ind of this NFProfile.


        :return: The nf_profile_changes_ind of this NFProfile.
        :rtype: bool
        """
        return self._nf_profile_changes_ind

    @nf_profile_changes_ind.setter
    def nf_profile_changes_ind(self, nf_profile_changes_ind: bool):
        """Sets the nf_profile_changes_ind of this NFProfile.


        :param nf_profile_changes_ind: The nf_profile_changes_ind of this NFProfile.
        :type nf_profile_changes_ind: bool
        """

        self._nf_profile_changes_ind = nf_profile_changes_ind

    @property
    def default_notification_subscriptions(self) -> List[DefaultNotificationSubscription]:
        """Gets the default_notification_subscriptions of this NFProfile.


        :return: The default_notification_subscriptions of this NFProfile.
        :rtype: List[DefaultNotificationSubscription]
        """
        return self._default_notification_subscriptions

    @default_notification_subscriptions.setter
    def default_notification_subscriptions(self, default_notification_subscriptions: List[DefaultNotificationSubscription]):
        """Sets the default_notification_subscriptions of this NFProfile.


        :param default_notification_subscriptions: The default_notification_subscriptions of this NFProfile.
        :type default_notification_subscriptions: List[DefaultNotificationSubscription]
        """

        self._default_notification_subscriptions = default_notification_subscriptions

    @property
    def lmf_info(self) -> LmfInfo:
        """Gets the lmf_info of this NFProfile.


        :return: The lmf_info of this NFProfile.
        :rtype: LmfInfo
        """
        return self._lmf_info

    @lmf_info.setter
    def lmf_info(self, lmf_info: LmfInfo):
        """Sets the lmf_info of this NFProfile.


        :param lmf_info: The lmf_info of this NFProfile.
        :type lmf_info: LmfInfo
        """

        self._lmf_info = lmf_info

    @property
    def gmlc_info(self) -> GmlcInfo:
        """Gets the gmlc_info of this NFProfile.


        :return: The gmlc_info of this NFProfile.
        :rtype: GmlcInfo
        """
        return self._gmlc_info

    @gmlc_info.setter
    def gmlc_info(self, gmlc_info: GmlcInfo):
        """Sets the gmlc_info of this NFProfile.


        :param gmlc_info: The gmlc_info of this NFProfile.
        :type gmlc_info: GmlcInfo
        """

        self._gmlc_info = gmlc_info

    @property
    def nf_set_id_list(self) -> List[str]:
        """Gets the nf_set_id_list of this NFProfile.


        :return: The nf_set_id_list of this NFProfile.
        :rtype: List[str]
        """
        return self._nf_set_id_list

    @nf_set_id_list.setter
    def nf_set_id_list(self, nf_set_id_list: List[str]):
        """Sets the nf_set_id_list of this NFProfile.


        :param nf_set_id_list: The nf_set_id_list of this NFProfile.
        :type nf_set_id_list: List[str]
        """

        self._nf_set_id_list = nf_set_id_list

    @property
    def serving_scope(self) -> List[str]:
        """Gets the serving_scope of this NFProfile.


        :return: The serving_scope of this NFProfile.
        :rtype: List[str]
        """
        return self._serving_scope

    @serving_scope.setter
    def serving_scope(self, serving_scope: List[str]):
        """Sets the serving_scope of this NFProfile.


        :param serving_scope: The serving_scope of this NFProfile.
        :type serving_scope: List[str]
        """

        self._serving_scope = serving_scope

    @property
    def lc_h_support_ind(self) -> bool:
        """Gets the lc_h_support_ind of this NFProfile.


        :return: The lc_h_support_ind of this NFProfile.
        :rtype: bool
        """
        return self._lc_h_support_ind

    @lc_h_support_ind.setter
    def lc_h_support_ind(self, lc_h_support_ind: bool):
        """Sets the lc_h_support_ind of this NFProfile.


        :param lc_h_support_ind: The lc_h_support_ind of this NFProfile.
        :type lc_h_support_ind: bool
        """

        self._lc_h_support_ind = lc_h_support_ind

    @property
    def olc_h_support_ind(self) -> bool:
        """Gets the olc_h_support_ind of this NFProfile.


        :return: The olc_h_support_ind of this NFProfile.
        :rtype: bool
        """
        return self._olc_h_support_ind

    @olc_h_support_ind.setter
    def olc_h_support_ind(self, olc_h_support_ind: bool):
        """Sets the olc_h_support_ind of this NFProfile.


        :param olc_h_support_ind: The olc_h_support_ind of this NFProfile.
        :type olc_h_support_ind: bool
        """

        self._olc_h_support_ind = olc_h_support_ind

    @property
    def nf_set_recovery_time_list(self) -> Dict[str, datetime]:
        """Gets the nf_set_recovery_time_list of this NFProfile.


        :return: The nf_set_recovery_time_list of this NFProfile.
        :rtype: Dict[str, datetime]
        """
        return self._nf_set_recovery_time_list

    @nf_set_recovery_time_list.setter
    def nf_set_recovery_time_list(self, nf_set_recovery_time_list: Dict[str, datetime]):
        """Sets the nf_set_recovery_time_list of this NFProfile.


        :param nf_set_recovery_time_list: The nf_set_recovery_time_list of this NFProfile.
        :type nf_set_recovery_time_list: Dict[str, datetime]
        """

        self._nf_set_recovery_time_list = nf_set_recovery_time_list

    @property
    def service_set_recovery_time_list(self) -> Dict[str, datetime]:
        """Gets the service_set_recovery_time_list of this NFProfile.


        :return: The service_set_recovery_time_list of this NFProfile.
        :rtype: Dict[str, datetime]
        """
        return self._service_set_recovery_time_list

    @service_set_recovery_time_list.setter
    def service_set_recovery_time_list(self, service_set_recovery_time_list: Dict[str, datetime]):
        """Sets the service_set_recovery_time_list of this NFProfile.


        :param service_set_recovery_time_list: The service_set_recovery_time_list of this NFProfile.
        :type service_set_recovery_time_list: Dict[str, datetime]
        """

        self._service_set_recovery_time_list = service_set_recovery_time_list

    @property
    def scp_domains(self) -> List[str]:
        """Gets the scp_domains of this NFProfile.


        :return: The scp_domains of this NFProfile.
        :rtype: List[str]
        """
        return self._scp_domains

    @scp_domains.setter
    def scp_domains(self, scp_domains: List[str]):
        """Sets the scp_domains of this NFProfile.


        :param scp_domains: The scp_domains of this NFProfile.
        :type scp_domains: List[str]
        """

        self._scp_domains = scp_domains

    @property
    def scp_info(self) -> ScpInfo:
        """Gets the scp_info of this NFProfile.


        :return: The scp_info of this NFProfile.
        :rtype: ScpInfo
        """
        return self._scp_info

    @scp_info.setter
    def scp_info(self, scp_info: ScpInfo):
        """Sets the scp_info of this NFProfile.


        :param scp_info: The scp_info of this NFProfile.
        :type scp_info: ScpInfo
        """

        self._scp_info = scp_info
