# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class ReportItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None, reason=None):  # noqa: E501
        """ReportItem - a model defined in OpenAPI

        :param path: The path of this ReportItem.  # noqa: E501
        :type path: str
        :param reason: The reason of this ReportItem.  # noqa: E501
        :type reason: str
        """
        self.openapi_types = {
            'path': str,
            'reason': str
        }

        self.attribute_map = {
            'path': 'path',
            'reason': 'reason'
        }

        self._path = path
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'ReportItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportItem of this ReportItem.  # noqa: E501
        :rtype: ReportItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self):
        """Gets the path of this ReportItem.

        Contains a JSON pointer value (as defined in IETF RFC 6901) that references a  location of a resource to which the modification is subject.   # noqa: E501

        :return: The path of this ReportItem.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ReportItem.

        Contains a JSON pointer value (as defined in IETF RFC 6901) that references a  location of a resource to which the modification is subject.   # noqa: E501

        :param path: The path of this ReportItem.
        :type path: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def reason(self):
        """Gets the reason of this ReportItem.

        A human-readable reason providing details on the reported modification failure.  The reason string should identify the operation that failed using the operation's  array index to assist in correlation of the invalid parameter with the failed  operation, e.g. \"Replacement value invalid for attribute (failed operation index= 4)\".   # noqa: E501

        :return: The reason of this ReportItem.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ReportItem.

        A human-readable reason providing details on the reported modification failure.  The reason string should identify the operation that failed using the operation's  array index to assist in correlation of the invalid parameter with the failed  operation, e.g. \"Replacement value invalid for attribute (failed operation index= 4)\".   # noqa: E501

        :param reason: The reason of this ReportItem.
        :type reason: str
        """

        self._reason = reason
