# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.fqdn import Fqdn  # noqa: F401,E501
from models.ip_end_point import IpEndPoint  # noqa: F401,E501
import util


class ScpDomainInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, scp_fqdn: Fqdn=None, scp_ip_end_points: List[IpEndPoint]=None, scp_prefix: str=None, scp_ports: Dict[str, int]=None):  # noqa: E501
        """ScpDomainInfo - a model defined in Swagger

        :param scp_fqdn: The scp_fqdn of this ScpDomainInfo.  # noqa: E501
        :type scp_fqdn: Fqdn
        :param scp_ip_end_points: The scp_ip_end_points of this ScpDomainInfo.  # noqa: E501
        :type scp_ip_end_points: List[IpEndPoint]
        :param scp_prefix: The scp_prefix of this ScpDomainInfo.  # noqa: E501
        :type scp_prefix: str
        :param scp_ports: The scp_ports of this ScpDomainInfo.  # noqa: E501
        :type scp_ports: Dict[str, int]
        """
        self.openapi_types = {
            'scp_fqdn': Fqdn,
            'scp_ip_end_points': List[IpEndPoint],
            'scp_prefix': str,
            'scp_ports': Dict[str, int]
        }

        self.attribute_map = {
            'scp_fqdn': 'scpFqdn',
            'scp_ip_end_points': 'scpIpEndPoints',
            'scp_prefix': 'scpPrefix',
            'scp_ports': 'scpPorts'
        }
        self._scp_fqdn = scp_fqdn
        self._scp_ip_end_points = scp_ip_end_points
        self._scp_prefix = scp_prefix
        self._scp_ports = scp_ports

    @classmethod
    def from_dict(cls, dikt) -> 'ScpDomainInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScpDomainInfo of this ScpDomainInfo.  # noqa: E501
        :rtype: ScpDomainInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scp_fqdn(self) -> Fqdn:
        """Gets the scp_fqdn of this ScpDomainInfo.


        :return: The scp_fqdn of this ScpDomainInfo.
        :rtype: Fqdn
        """
        return self._scp_fqdn

    @scp_fqdn.setter
    def scp_fqdn(self, scp_fqdn: Fqdn):
        """Sets the scp_fqdn of this ScpDomainInfo.


        :param scp_fqdn: The scp_fqdn of this ScpDomainInfo.
        :type scp_fqdn: Fqdn
        """

        self._scp_fqdn = scp_fqdn

    @property
    def scp_ip_end_points(self) -> List[IpEndPoint]:
        """Gets the scp_ip_end_points of this ScpDomainInfo.


        :return: The scp_ip_end_points of this ScpDomainInfo.
        :rtype: List[IpEndPoint]
        """
        return self._scp_ip_end_points

    @scp_ip_end_points.setter
    def scp_ip_end_points(self, scp_ip_end_points: List[IpEndPoint]):
        """Sets the scp_ip_end_points of this ScpDomainInfo.


        :param scp_ip_end_points: The scp_ip_end_points of this ScpDomainInfo.
        :type scp_ip_end_points: List[IpEndPoint]
        """

        self._scp_ip_end_points = scp_ip_end_points

    @property
    def scp_prefix(self) -> str:
        """Gets the scp_prefix of this ScpDomainInfo.


        :return: The scp_prefix of this ScpDomainInfo.
        :rtype: str
        """
        return self._scp_prefix

    @scp_prefix.setter
    def scp_prefix(self, scp_prefix: str):
        """Sets the scp_prefix of this ScpDomainInfo.


        :param scp_prefix: The scp_prefix of this ScpDomainInfo.
        :type scp_prefix: str
        """

        self._scp_prefix = scp_prefix

    @property
    def scp_ports(self) -> Dict[str, int]:
        """Gets the scp_ports of this ScpDomainInfo.


        :return: The scp_ports of this ScpDomainInfo.
        :rtype: Dict[str, int]
        """
        return self._scp_ports

    @scp_ports.setter
    def scp_ports(self, scp_ports: Dict[str, int]):
        """Sets the scp_ports of this ScpDomainInfo.


        :param scp_ports: The scp_ports of this ScpDomainInfo.
        :type scp_ports: Dict[str, int]
        """

        self._scp_ports = scp_ports
