# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.ipv4_address_range import Ipv4AddressRange  # noqa: F401,E501
from models.ipv6_prefix_range import Ipv6PrefixRange  # noqa: F401,E501
from models.nf_profile_plmn_list import NFProfilePlmnList  # noqa: F401,E501
from models.scp_domain_info import ScpDomainInfo  # noqa: F401,E501
from models.all_of_scp_info_ipv6_prefixes_items import AllOfScpInfoIpv6PrefixesItems  # noqa: F401,E501
import util


class ScpInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, scp_domain_info_list: Dict[str, List[ScpDomainInfo]]=None, scp_prefix: str=None, scp_ports: Dict[str, int]=None, address_domains: List[str]=None, ipv4_addresses: List[str]=None, ipv6_prefixes: List[AllOfScpInfoIpv6PrefixesItems]=None, ipv4_addr_ranges: List[Ipv4AddressRange]=None, ipv6_prefix_ranges: List[Ipv6PrefixRange]=None, served_nf_set_id_list: List[str]=None, remote_plmn_list: List[NFProfilePlmnList]=None):  # noqa: E501
        """ScpInfo - a model defined in Swagger

        :param scp_domain_info_list: The scp_domain_info_list of this ScpInfo.  # noqa: E501
        :type scp_domain_info_list: Dict[str, List[ScpDomainInfo]]
        :param scp_prefix: The scp_prefix of this ScpInfo.  # noqa: E501
        :type scp_prefix: str
        :param scp_ports: The scp_ports of this ScpInfo.  # noqa: E501
        :type scp_ports: Dict[str, int]
        :param address_domains: The address_domains of this ScpInfo.  # noqa: E501
        :type address_domains: List[str]
        :param ipv4_addresses: The ipv4_addresses of this ScpInfo.  # noqa: E501
        :type ipv4_addresses: List[str]
        :param ipv6_prefixes: The ipv6_prefixes of this ScpInfo.  # noqa: E501
        :type ipv6_prefixes: List[AllOfScpInfoIpv6PrefixesItems]
        :param ipv4_addr_ranges: The ipv4_addr_ranges of this ScpInfo.  # noqa: E501
        :type ipv4_addr_ranges: List[Ipv4AddressRange]
        :param ipv6_prefix_ranges: The ipv6_prefix_ranges of this ScpInfo.  # noqa: E501
        :type ipv6_prefix_ranges: List[Ipv6PrefixRange]
        :param served_nf_set_id_list: The served_nf_set_id_list of this ScpInfo.  # noqa: E501
        :type served_nf_set_id_list: List[str]
        :param remote_plmn_list: The remote_plmn_list of this ScpInfo.  # noqa: E501
        :type remote_plmn_list: List[NFProfilePlmnList]
        """
        self.openapi_types = {
            'scp_domain_info_list': Dict[str, List[ScpDomainInfo]],
            'scp_prefix': str,
            'scp_ports': Dict[str, int],
            'address_domains': List[str],
            'ipv4_addresses': List[str],
            'ipv6_prefixes': List[AllOfScpInfoIpv6PrefixesItems],
            'ipv4_addr_ranges': List[Ipv4AddressRange],
            'ipv6_prefix_ranges': List[Ipv6PrefixRange],
            'served_nf_set_id_list': List[str],
            'remote_plmn_list': List[NFProfilePlmnList]
        }

        self.attribute_map = {
            'scp_domain_info_list': 'scpDomainInfoList',
            'scp_prefix': 'scpPrefix',
            'scp_ports': 'scpPorts',
            'address_domains': 'addressDomains',
            'ipv4_addresses': 'ipv4Addresses',
            'ipv6_prefixes': 'ipv6Prefixes',
            'ipv4_addr_ranges': 'ipv4AddrRanges',
            'ipv6_prefix_ranges': 'ipv6PrefixRanges',
            'served_nf_set_id_list': 'servedNfSetIdList',
            'remote_plmn_list': 'remotePlmnList'
        }
        self._scp_domain_info_list = scp_domain_info_list
        self._scp_prefix = scp_prefix
        self._scp_ports = scp_ports
        self._address_domains = address_domains
        self._ipv4_addresses = ipv4_addresses
        self._ipv6_prefixes = ipv6_prefixes
        self._ipv4_addr_ranges = ipv4_addr_ranges
        self._ipv6_prefix_ranges = ipv6_prefix_ranges
        self._served_nf_set_id_list = served_nf_set_id_list
        self._remote_plmn_list = remote_plmn_list

    @classmethod
    def from_dict(cls, dikt) -> 'ScpInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScpInfo of this ScpInfo.  # noqa: E501
        :rtype: ScpInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scp_domain_info_list(self) -> Dict[str, List[ScpDomainInfo]]:
        """Gets the scp_domain_info_list of this ScpInfo.


        :return: The scp_domain_info_list of this ScpInfo.
        :rtype: Dict[str, List[ScpDomainInfo]]
        """
        return self._scp_domain_info_list

    @scp_domain_info_list.setter
    def scp_domain_info_list(self, scp_domain_info_list: Dict[str, List[ScpDomainInfo]]):
        """Sets the scp_domain_info_list of this ScpInfo.


        :param scp_domain_info_list: The scp_domain_info_list of this ScpInfo.
        :type scp_domain_info_list: Dict[str, List[ScpDomainInfo]]
        """

        self._scp_domain_info_list = scp_domain_info_list

    @property
    def scp_prefix(self) -> str:
        """Gets the scp_prefix of this ScpInfo.


        :return: The scp_prefix of this ScpInfo.
        :rtype: str
        """
        return self._scp_prefix

    @scp_prefix.setter
    def scp_prefix(self, scp_prefix: str):
        """Sets the scp_prefix of this ScpInfo.


        :param scp_prefix: The scp_prefix of this ScpInfo.
        :type scp_prefix: str
        """

        self._scp_prefix = scp_prefix

    @property
    def scp_ports(self) -> Dict[str, int]:
        """Gets the scp_ports of this ScpInfo.


        :return: The scp_ports of this ScpInfo.
        :rtype: Dict[str, int]
        """
        return self._scp_ports

    @scp_ports.setter
    def scp_ports(self, scp_ports: Dict[str, int]):
        """Sets the scp_ports of this ScpInfo.


        :param scp_ports: The scp_ports of this ScpInfo.
        :type scp_ports: Dict[str, int]
        """

        self._scp_ports = scp_ports

    @property
    def address_domains(self) -> List[str]:
        """Gets the address_domains of this ScpInfo.


        :return: The address_domains of this ScpInfo.
        :rtype: List[str]
        """
        return self._address_domains

    @address_domains.setter
    def address_domains(self, address_domains: List[str]):
        """Sets the address_domains of this ScpInfo.


        :param address_domains: The address_domains of this ScpInfo.
        :type address_domains: List[str]
        """

        self._address_domains = address_domains

    @property
    def ipv4_addresses(self) -> List[str]:
        """Gets the ipv4_addresses of this ScpInfo.


        :return: The ipv4_addresses of this ScpInfo.
        :rtype: List[str]
        """
        return self._ipv4_addresses

    @ipv4_addresses.setter
    def ipv4_addresses(self, ipv4_addresses: List[str]):
        """Sets the ipv4_addresses of this ScpInfo.


        :param ipv4_addresses: The ipv4_addresses of this ScpInfo.
        :type ipv4_addresses: List[str]
        """

        self._ipv4_addresses = ipv4_addresses

    @property
    def ipv6_prefixes(self) -> List[AllOfScpInfoIpv6PrefixesItems]:
        """Gets the ipv6_prefixes of this ScpInfo.


        :return: The ipv6_prefixes of this ScpInfo.
        :rtype: List[AllOfScpInfoIpv6PrefixesItems]
        """
        return self._ipv6_prefixes

    @ipv6_prefixes.setter
    def ipv6_prefixes(self, ipv6_prefixes: List[AllOfScpInfoIpv6PrefixesItems]):
        """Sets the ipv6_prefixes of this ScpInfo.


        :param ipv6_prefixes: The ipv6_prefixes of this ScpInfo.
        :type ipv6_prefixes: List[AllOfScpInfoIpv6PrefixesItems]
        """

        self._ipv6_prefixes = ipv6_prefixes

    @property
    def ipv4_addr_ranges(self) -> List[Ipv4AddressRange]:
        """Gets the ipv4_addr_ranges of this ScpInfo.


        :return: The ipv4_addr_ranges of this ScpInfo.
        :rtype: List[Ipv4AddressRange]
        """
        return self._ipv4_addr_ranges

    @ipv4_addr_ranges.setter
    def ipv4_addr_ranges(self, ipv4_addr_ranges: List[Ipv4AddressRange]):
        """Sets the ipv4_addr_ranges of this ScpInfo.


        :param ipv4_addr_ranges: The ipv4_addr_ranges of this ScpInfo.
        :type ipv4_addr_ranges: List[Ipv4AddressRange]
        """

        self._ipv4_addr_ranges = ipv4_addr_ranges

    @property
    def ipv6_prefix_ranges(self) -> List[Ipv6PrefixRange]:
        """Gets the ipv6_prefix_ranges of this ScpInfo.


        :return: The ipv6_prefix_ranges of this ScpInfo.
        :rtype: List[Ipv6PrefixRange]
        """
        return self._ipv6_prefix_ranges

    @ipv6_prefix_ranges.setter
    def ipv6_prefix_ranges(self, ipv6_prefix_ranges: List[Ipv6PrefixRange]):
        """Sets the ipv6_prefix_ranges of this ScpInfo.


        :param ipv6_prefix_ranges: The ipv6_prefix_ranges of this ScpInfo.
        :type ipv6_prefix_ranges: List[Ipv6PrefixRange]
        """

        self._ipv6_prefix_ranges = ipv6_prefix_ranges

    @property
    def served_nf_set_id_list(self) -> List[str]:
        """Gets the served_nf_set_id_list of this ScpInfo.


        :return: The served_nf_set_id_list of this ScpInfo.
        :rtype: List[str]
        """
        return self._served_nf_set_id_list

    @served_nf_set_id_list.setter
    def served_nf_set_id_list(self, served_nf_set_id_list: List[str]):
        """Sets the served_nf_set_id_list of this ScpInfo.


        :param served_nf_set_id_list: The served_nf_set_id_list of this ScpInfo.
        :type served_nf_set_id_list: List[str]
        """

        self._served_nf_set_id_list = served_nf_set_id_list

    @property
    def remote_plmn_list(self) -> List[NFProfilePlmnList]:
        """Gets the remote_plmn_list of this ScpInfo.


        :return: The remote_plmn_list of this ScpInfo.
        :rtype: List[NFProfilePlmnList]
        """
        return self._remote_plmn_list

    @remote_plmn_list.setter
    def remote_plmn_list(self, remote_plmn_list: List[NFProfilePlmnList]):
        """Sets the remote_plmn_list of this ScpInfo.


        :param remote_plmn_list: The remote_plmn_list of this ScpInfo.
        :type remote_plmn_list: List[NFProfilePlmnList]
        """

        self._remote_plmn_list = remote_plmn_list
