# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
from models.dnai_change_type import DnaiChangeType
from models.eth_flow_description import EthFlowDescription
from models.flow_info import FlowInfo
from models.network_area_info2 import NetworkAreaInfo2
from models.route_to_location import RouteToLocation
from models.snssai import Snssai
from models.subscribed_event import SubscribedEvent
from models.temporal_validity import TemporalValidity
import re
import util

class TrafficInfluData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, up_path_chg_notif_corre_id=None, app_relo_ind=None, af_app_id=None, dnn=None, eth_traffic_filters=None, snssai=None, inter_group_id=None, supi=None, traffic_filters=None, traffic_routes=None, traff_corre_ind=None, valid_start_time=None, valid_end_time=None, temp_validities=None, nw_area_info=None, up_path_chg_notif_uri=None, headers=None, subscribed_events=None, dnai_chg_type=None, af_ack_ind=None, addr_preser_ind=None, max_allowed_up_lat=None, sim_conn_ind=None, sim_conn_term=None, supported_features=None, res_uri=None, reset_ids=None):  # noqa: E501
        """TrafficInfluData - a model defined in OpenAPI

        :param up_path_chg_notif_corre_id: The up_path_chg_notif_corre_id of this TrafficInfluData.  # noqa: E501
        :type up_path_chg_notif_corre_id: str
        :param app_relo_ind: The app_relo_ind of this TrafficInfluData.  # noqa: E501
        :type app_relo_ind: bool
        :param af_app_id: The af_app_id of this TrafficInfluData.  # noqa: E501
        :type af_app_id: str
        :param dnn: The dnn of this TrafficInfluData.  # noqa: E501
        :type dnn: str
        :param eth_traffic_filters: The eth_traffic_filters of this TrafficInfluData.  # noqa: E501
        :type eth_traffic_filters: List[EthFlowDescription]
        :param snssai: The snssai of this TrafficInfluData.  # noqa: E501
        :type snssai: Snssai
        :param inter_group_id: The inter_group_id of this TrafficInfluData.  # noqa: E501
        :type inter_group_id: str
        :param supi: The supi of this TrafficInfluData.  # noqa: E501
        :type supi: str
        :param traffic_filters: The traffic_filters of this TrafficInfluData.  # noqa: E501
        :type traffic_filters: List[FlowInfo]
        :param traffic_routes: The traffic_routes of this TrafficInfluData.  # noqa: E501
        :type traffic_routes: List[RouteToLocation]
        :param traff_corre_ind: The traff_corre_ind of this TrafficInfluData.  # noqa: E501
        :type traff_corre_ind: bool
        :param valid_start_time: The valid_start_time of this TrafficInfluData.  # noqa: E501
        :type valid_start_time: datetime
        :param valid_end_time: The valid_end_time of this TrafficInfluData.  # noqa: E501
        :type valid_end_time: datetime
        :param temp_validities: The temp_validities of this TrafficInfluData.  # noqa: E501
        :type temp_validities: List[TemporalValidity]
        :param nw_area_info: The nw_area_info of this TrafficInfluData.  # noqa: E501
        :type nw_area_info: NetworkAreaInfo2
        :param up_path_chg_notif_uri: The up_path_chg_notif_uri of this TrafficInfluData.  # noqa: E501
        :type up_path_chg_notif_uri: str
        :param headers: The headers of this TrafficInfluData.  # noqa: E501
        :type headers: List[str]
        :param subscribed_events: The subscribed_events of this TrafficInfluData.  # noqa: E501
        :type subscribed_events: List[SubscribedEvent]
        :param dnai_chg_type: The dnai_chg_type of this TrafficInfluData.  # noqa: E501
        :type dnai_chg_type: DnaiChangeType
        :param af_ack_ind: The af_ack_ind of this TrafficInfluData.  # noqa: E501
        :type af_ack_ind: bool
        :param addr_preser_ind: The addr_preser_ind of this TrafficInfluData.  # noqa: E501
        :type addr_preser_ind: bool
        :param max_allowed_up_lat: The max_allowed_up_lat of this TrafficInfluData.  # noqa: E501
        :type max_allowed_up_lat: int
        :param sim_conn_ind: The sim_conn_ind of this TrafficInfluData.  # noqa: E501
        :type sim_conn_ind: bool
        :param sim_conn_term: The sim_conn_term of this TrafficInfluData.  # noqa: E501
        :type sim_conn_term: int
        :param supported_features: The supported_features of this TrafficInfluData.  # noqa: E501
        :type supported_features: str
        :param res_uri: The res_uri of this TrafficInfluData.  # noqa: E501
        :type res_uri: str
        :param reset_ids: The reset_ids of this TrafficInfluData.  # noqa: E501
        :type reset_ids: List[str]
        """
        self.openapi_types = {
            'up_path_chg_notif_corre_id': str,
            'app_relo_ind': bool,
            'af_app_id': str,
            'dnn': str,
            'eth_traffic_filters': List[EthFlowDescription],
            'snssai': Snssai,
            'inter_group_id': str,
            'supi': str,
            'traffic_filters': List[FlowInfo],
            'traffic_routes': List[RouteToLocation],
            'traff_corre_ind': bool,
            'valid_start_time': datetime,
            'valid_end_time': datetime,
            'temp_validities': List[TemporalValidity],
            'nw_area_info': NetworkAreaInfo2,
            'up_path_chg_notif_uri': str,
            'headers': List[str],
            'subscribed_events': List[SubscribedEvent],
            'dnai_chg_type': DnaiChangeType,
            'af_ack_ind': bool,
            'addr_preser_ind': bool,
            'max_allowed_up_lat': int,
            'sim_conn_ind': bool,
            'sim_conn_term': int,
            'supported_features': str,
            'res_uri': str,
            'reset_ids': List[str]
        }

        self.attribute_map = {
            'up_path_chg_notif_corre_id': 'upPathChgNotifCorreId',
            'app_relo_ind': 'appReloInd',
            'af_app_id': 'afAppId',
            'dnn': 'dnn',
            'eth_traffic_filters': 'ethTrafficFilters',
            'snssai': 'snssai',
            'inter_group_id': 'interGroupId',
            'supi': 'supi',
            'traffic_filters': 'trafficFilters',
            'traffic_routes': 'trafficRoutes',
            'traff_corre_ind': 'traffCorreInd',
            'valid_start_time': 'validStartTime',
            'valid_end_time': 'validEndTime',
            'temp_validities': 'tempValidities',
            'nw_area_info': 'nwAreaInfo',
            'up_path_chg_notif_uri': 'upPathChgNotifUri',
            'headers': 'headers',
            'subscribed_events': 'subscribedEvents',
            'dnai_chg_type': 'dnaiChgType',
            'af_ack_ind': 'afAckInd',
            'addr_preser_ind': 'addrPreserInd',
            'max_allowed_up_lat': 'maxAllowedUpLat',
            'sim_conn_ind': 'simConnInd',
            'sim_conn_term': 'simConnTerm',
            'supported_features': 'supportedFeatures',
            'res_uri': 'resUri',
            'reset_ids': 'resetIds'
        }

        self._up_path_chg_notif_corre_id = up_path_chg_notif_corre_id
        self._app_relo_ind = app_relo_ind
        self._af_app_id = af_app_id
        self._dnn = dnn
        self._eth_traffic_filters = eth_traffic_filters
        self._snssai = snssai
        self._inter_group_id = inter_group_id
        self._supi = supi
        self._traffic_filters = traffic_filters
        self._traffic_routes = traffic_routes
        self._traff_corre_ind = traff_corre_ind
        self._valid_start_time = valid_start_time
        self._valid_end_time = valid_end_time
        self._temp_validities = temp_validities
        self._nw_area_info = nw_area_info
        self._up_path_chg_notif_uri = up_path_chg_notif_uri
        self._headers = headers
        self._subscribed_events = subscribed_events
        self._dnai_chg_type = dnai_chg_type
        self._af_ack_ind = af_ack_ind
        self._addr_preser_ind = addr_preser_ind
        self._max_allowed_up_lat = max_allowed_up_lat
        self._sim_conn_ind = sim_conn_ind
        self._sim_conn_term = sim_conn_term
        self._supported_features = supported_features
        self._res_uri = res_uri
        self._reset_ids = reset_ids

    @classmethod
    def from_dict(cls, dikt) -> 'TrafficInfluData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrafficInfluData of this TrafficInfluData.  # noqa: E501
        :rtype: TrafficInfluData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def up_path_chg_notif_corre_id(self):
        """Gets the up_path_chg_notif_corre_id of this TrafficInfluData.

        Contains the Notification Correlation Id allocated by the NEF for the UP path change notification.   # noqa: E501

        :return: The up_path_chg_notif_corre_id of this TrafficInfluData.
        :rtype: str
        """
        return self._up_path_chg_notif_corre_id

    @up_path_chg_notif_corre_id.setter
    def up_path_chg_notif_corre_id(self, up_path_chg_notif_corre_id):
        """Sets the up_path_chg_notif_corre_id of this TrafficInfluData.

        Contains the Notification Correlation Id allocated by the NEF for the UP path change notification.   # noqa: E501

        :param up_path_chg_notif_corre_id: The up_path_chg_notif_corre_id of this TrafficInfluData.
        :type up_path_chg_notif_corre_id: str
        """

        self._up_path_chg_notif_corre_id = up_path_chg_notif_corre_id

    @property
    def app_relo_ind(self):
        """Gets the app_relo_ind of this TrafficInfluData.

        Identifies whether an application can be relocated once a location of the application has been selected.   # noqa: E501

        :return: The app_relo_ind of this TrafficInfluData.
        :rtype: bool
        """
        return self._app_relo_ind

    @app_relo_ind.setter
    def app_relo_ind(self, app_relo_ind):
        """Sets the app_relo_ind of this TrafficInfluData.

        Identifies whether an application can be relocated once a location of the application has been selected.   # noqa: E501

        :param app_relo_ind: The app_relo_ind of this TrafficInfluData.
        :type app_relo_ind: bool
        """

        self._app_relo_ind = app_relo_ind

    @property
    def af_app_id(self):
        """Gets the af_app_id of this TrafficInfluData.

        Identifies an application.  # noqa: E501

        :return: The af_app_id of this TrafficInfluData.
        :rtype: str
        """
        return self._af_app_id

    @af_app_id.setter
    def af_app_id(self, af_app_id):
        """Sets the af_app_id of this TrafficInfluData.

        Identifies an application.  # noqa: E501

        :param af_app_id: The af_app_id of this TrafficInfluData.
        :type af_app_id: str
        """

        self._af_app_id = af_app_id

    @property
    def dnn(self):
        """Gets the dnn of this TrafficInfluData.

        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").   # noqa: E501

        :return: The dnn of this TrafficInfluData.
        :rtype: str
        """
        return self._dnn

    @dnn.setter
    def dnn(self, dnn):
        """Sets the dnn of this TrafficInfluData.

        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").   # noqa: E501

        :param dnn: The dnn of this TrafficInfluData.
        :type dnn: str
        """

        self._dnn = dnn

    @property
    def eth_traffic_filters(self):
        """Gets the eth_traffic_filters of this TrafficInfluData.

        Identifies Ethernet packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable.   # noqa: E501

        :return: The eth_traffic_filters of this TrafficInfluData.
        :rtype: List[EthFlowDescription]
        """
        return self._eth_traffic_filters

    @eth_traffic_filters.setter
    def eth_traffic_filters(self, eth_traffic_filters):
        """Sets the eth_traffic_filters of this TrafficInfluData.

        Identifies Ethernet packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable.   # noqa: E501

        :param eth_traffic_filters: The eth_traffic_filters of this TrafficInfluData.
        :type eth_traffic_filters: List[EthFlowDescription]
        """
        if eth_traffic_filters is not None and len(eth_traffic_filters) < 1:
            raise ValueError("Invalid value for `eth_traffic_filters`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._eth_traffic_filters = eth_traffic_filters

    @property
    def snssai(self):
        """Gets the snssai of this TrafficInfluData.


        :return: The snssai of this TrafficInfluData.
        :rtype: Snssai
        """
        return self._snssai

    @snssai.setter
    def snssai(self, snssai):
        """Sets the snssai of this TrafficInfluData.


        :param snssai: The snssai of this TrafficInfluData.
        :type snssai: Snssai
        """

        self._snssai = snssai

    @property
    def inter_group_id(self):
        """Gets the inter_group_id of this TrafficInfluData.

        String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.    # noqa: E501

        :return: The inter_group_id of this TrafficInfluData.
        :rtype: str
        """
        return self._inter_group_id

    @inter_group_id.setter
    def inter_group_id(self, inter_group_id):
        """Sets the inter_group_id of this TrafficInfluData.

        String identifying a group of devices network internal globally unique ID which identifies a set of IMSIs, as specified in clause 19.9 of 3GPP TS 23.003.    # noqa: E501

        :param inter_group_id: The inter_group_id of this TrafficInfluData.
        :type inter_group_id: str
        """
        if inter_group_id is not None and (not re.search(r'^[A-Fa-f0-9]{8}-[0-9]{3}-[0-9]{2,3}-([A-Fa-f0-9][A-Fa-f0-9]){1,10}$', inter_group_id) or "AnyUE"):  # noqa: E501
            raise ValueError("Invalid value for `inter_group_id`, must be a follow pattern or equal to `/^[A-Fa-f0-9]{8}-[0-9]{3}-[0-9]{2,3}-([A-Fa-f0-9][A-Fa-f0-9]){1,10}$/`")  # noqa: E501

        self._inter_group_id = inter_group_id

    @property
    def supi(self):
        """Gets the supi of this TrafficInfluData.

        String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501.   # noqa: E501

        :return: The supi of this TrafficInfluData.
        :rtype: str
        """
        return self._supi

    @supi.setter
    def supi(self, supi):
        """Sets the supi of this TrafficInfluData.

        String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501.   # noqa: E501

        :param supi: The supi of this TrafficInfluData.
        :type supi: str
        """
        if supi is not None and not re.search(r'^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$', supi):  # noqa: E501
            raise ValueError("Invalid value for `supi`, must be a follow pattern or equal to `/^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$/`")  # noqa: E501

        self._supi = supi

    @property
    def traffic_filters(self):
        """Gets the traffic_filters of this TrafficInfluData.

        Identifies IP packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable.   # noqa: E501

        :return: The traffic_filters of this TrafficInfluData.
        :rtype: List[FlowInfo]
        """
        return self._traffic_filters

    @traffic_filters.setter
    def traffic_filters(self, traffic_filters):
        """Sets the traffic_filters of this TrafficInfluData.

        Identifies IP packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable.   # noqa: E501

        :param traffic_filters: The traffic_filters of this TrafficInfluData.
        :type traffic_filters: List[FlowInfo]
        """
        if traffic_filters is not None and len(traffic_filters) < 1:
            raise ValueError("Invalid value for `traffic_filters`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._traffic_filters = traffic_filters

    @property
    def traffic_routes(self):
        """Gets the traffic_routes of this TrafficInfluData.

        Identifies the N6 traffic routing requirement.  # noqa: E501

        :return: The traffic_routes of this TrafficInfluData.
        :rtype: List[RouteToLocation]
        """
        return self._traffic_routes

    @traffic_routes.setter
    def traffic_routes(self, traffic_routes):
        """Sets the traffic_routes of this TrafficInfluData.

        Identifies the N6 traffic routing requirement.  # noqa: E501

        :param traffic_routes: The traffic_routes of this TrafficInfluData.
        :type traffic_routes: List[RouteToLocation]
        """
        if traffic_routes is not None and len(traffic_routes) < 1:
            raise ValueError("Invalid value for `traffic_routes`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._traffic_routes = traffic_routes

    @property
    def traff_corre_ind(self):
        """Gets the traff_corre_ind of this TrafficInfluData.


        :return: The traff_corre_ind of this TrafficInfluData.
        :rtype: bool
        """
        return self._traff_corre_ind

    @traff_corre_ind.setter
    def traff_corre_ind(self, traff_corre_ind):
        """Sets the traff_corre_ind of this TrafficInfluData.


        :param traff_corre_ind: The traff_corre_ind of this TrafficInfluData.
        :type traff_corre_ind: bool
        """

        self._traff_corre_ind = traff_corre_ind

    @property
    def valid_start_time(self):
        """Gets the valid_start_time of this TrafficInfluData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The valid_start_time of this TrafficInfluData.
        :rtype: datetime
        """
        return self._valid_start_time

    @valid_start_time.setter
    def valid_start_time(self, valid_start_time):
        """Sets the valid_start_time of this TrafficInfluData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param valid_start_time: The valid_start_time of this TrafficInfluData.
        :type valid_start_time: datetime
        """

        self._valid_start_time = valid_start_time

    @property
    def valid_end_time(self):
        """Gets the valid_end_time of this TrafficInfluData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :return: The valid_end_time of this TrafficInfluData.
        :rtype: datetime
        """
        return self._valid_end_time

    @valid_end_time.setter
    def valid_end_time(self, valid_end_time):
        """Sets the valid_end_time of this TrafficInfluData.

        string with format 'date-time' as defined in OpenAPI.  # noqa: E501

        :param valid_end_time: The valid_end_time of this TrafficInfluData.
        :type valid_end_time: datetime
        """

        self._valid_end_time = valid_end_time

    @property
    def temp_validities(self):
        """Gets the temp_validities of this TrafficInfluData.

        Identifies the temporal validities for the N6 traffic routing requirement.  # noqa: E501

        :return: The temp_validities of this TrafficInfluData.
        :rtype: List[TemporalValidity]
        """
        return self._temp_validities

    @temp_validities.setter
    def temp_validities(self, temp_validities):
        """Sets the temp_validities of this TrafficInfluData.

        Identifies the temporal validities for the N6 traffic routing requirement.  # noqa: E501

        :param temp_validities: The temp_validities of this TrafficInfluData.
        :type temp_validities: List[TemporalValidity]
        """
        if temp_validities is not None and len(temp_validities) < 1:
            raise ValueError("Invalid value for `temp_validities`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._temp_validities = temp_validities

    @property
    def nw_area_info(self):
        """Gets the nw_area_info of this TrafficInfluData.


        :return: The nw_area_info of this TrafficInfluData.
        :rtype: NetworkAreaInfo2
        """
        return self._nw_area_info

    @nw_area_info.setter
    def nw_area_info(self, nw_area_info):
        """Sets the nw_area_info of this TrafficInfluData.


        :param nw_area_info: The nw_area_info of this TrafficInfluData.
        :type nw_area_info: NetworkAreaInfo2
        """

        self._nw_area_info = nw_area_info

    @property
    def up_path_chg_notif_uri(self):
        """Gets the up_path_chg_notif_uri of this TrafficInfluData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :return: The up_path_chg_notif_uri of this TrafficInfluData.
        :rtype: str
        """
        return self._up_path_chg_notif_uri

    @up_path_chg_notif_uri.setter
    def up_path_chg_notif_uri(self, up_path_chg_notif_uri):
        """Sets the up_path_chg_notif_uri of this TrafficInfluData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :param up_path_chg_notif_uri: The up_path_chg_notif_uri of this TrafficInfluData.
        :type up_path_chg_notif_uri: str
        """

        self._up_path_chg_notif_uri = up_path_chg_notif_uri

    @property
    def headers(self):
        """Gets the headers of this TrafficInfluData.


        :return: The headers of this TrafficInfluData.
        :rtype: List[str]
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this TrafficInfluData.


        :param headers: The headers of this TrafficInfluData.
        :type headers: List[str]
        """
        if headers is not None and len(headers) < 1:
            raise ValueError("Invalid value for `headers`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._headers = headers

    @property
    def subscribed_events(self):
        """Gets the subscribed_events of this TrafficInfluData.


        :return: The subscribed_events of this TrafficInfluData.
        :rtype: List[SubscribedEvent]
        """
        return self._subscribed_events

    @subscribed_events.setter
    def subscribed_events(self, subscribed_events):
        """Sets the subscribed_events of this TrafficInfluData.


        :param subscribed_events: The subscribed_events of this TrafficInfluData.
        :type subscribed_events: List[SubscribedEvent]
        """
        if subscribed_events is not None and len(subscribed_events) < 1:
            raise ValueError("Invalid value for `subscribed_events`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._subscribed_events = subscribed_events

    @property
    def dnai_chg_type(self):
        """Gets the dnai_chg_type of this TrafficInfluData.


        :return: The dnai_chg_type of this TrafficInfluData.
        :rtype: DnaiChangeType
        """
        return self._dnai_chg_type

    @dnai_chg_type.setter
    def dnai_chg_type(self, dnai_chg_type):
        """Sets the dnai_chg_type of this TrafficInfluData.


        :param dnai_chg_type: The dnai_chg_type of this TrafficInfluData.
        :type dnai_chg_type: DnaiChangeType
        """

        self._dnai_chg_type = dnai_chg_type

    @property
    def af_ack_ind(self):
        """Gets the af_ack_ind of this TrafficInfluData.


        :return: The af_ack_ind of this TrafficInfluData.
        :rtype: bool
        """
        return self._af_ack_ind

    @af_ack_ind.setter
    def af_ack_ind(self, af_ack_ind):
        """Sets the af_ack_ind of this TrafficInfluData.


        :param af_ack_ind: The af_ack_ind of this TrafficInfluData.
        :type af_ack_ind: bool
        """

        self._af_ack_ind = af_ack_ind

    @property
    def addr_preser_ind(self):
        """Gets the addr_preser_ind of this TrafficInfluData.


        :return: The addr_preser_ind of this TrafficInfluData.
        :rtype: bool
        """
        return self._addr_preser_ind

    @addr_preser_ind.setter
    def addr_preser_ind(self, addr_preser_ind):
        """Sets the addr_preser_ind of this TrafficInfluData.


        :param addr_preser_ind: The addr_preser_ind of this TrafficInfluData.
        :type addr_preser_ind: bool
        """

        self._addr_preser_ind = addr_preser_ind

    @property
    def max_allowed_up_lat(self):
        """Gets the max_allowed_up_lat of this TrafficInfluData.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :return: The max_allowed_up_lat of this TrafficInfluData.
        :rtype: int
        """
        return self._max_allowed_up_lat

    @max_allowed_up_lat.setter
    def max_allowed_up_lat(self, max_allowed_up_lat):
        """Sets the max_allowed_up_lat of this TrafficInfluData.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :param max_allowed_up_lat: The max_allowed_up_lat of this TrafficInfluData.
        :type max_allowed_up_lat: int
        """
        if max_allowed_up_lat is not None and max_allowed_up_lat < 0:  # noqa: E501
            raise ValueError("Invalid value for `max_allowed_up_lat`, must be a value greater than or equal to `0`")  # noqa: E501

        self._max_allowed_up_lat = max_allowed_up_lat

    @property
    def sim_conn_ind(self):
        """Gets the sim_conn_ind of this TrafficInfluData.

        Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.   # noqa: E501

        :return: The sim_conn_ind of this TrafficInfluData.
        :rtype: bool
        """
        return self._sim_conn_ind

    @sim_conn_ind.setter
    def sim_conn_ind(self, sim_conn_ind):
        """Sets the sim_conn_ind of this TrafficInfluData.

        Indicates whether simultaneous connectivity should be temporarily maintained for the source and target PSA.   # noqa: E501

        :param sim_conn_ind: The sim_conn_ind of this TrafficInfluData.
        :type sim_conn_ind: bool
        """

        self._sim_conn_ind = sim_conn_ind

    @property
    def sim_conn_term(self):
        """Gets the sim_conn_term of this TrafficInfluData.

        indicating a time in seconds.  # noqa: E501

        :return: The sim_conn_term of this TrafficInfluData.
        :rtype: int
        """
        return self._sim_conn_term

    @sim_conn_term.setter
    def sim_conn_term(self, sim_conn_term):
        """Sets the sim_conn_term of this TrafficInfluData.

        indicating a time in seconds.  # noqa: E501

        :param sim_conn_term: The sim_conn_term of this TrafficInfluData.
        :type sim_conn_term: int
        """

        self._sim_conn_term = sim_conn_term

    @property
    def supported_features(self):
        """Gets the supported_features of this TrafficInfluData.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supported_features of this TrafficInfluData.
        :rtype: str
        """
        return self._supported_features

    @supported_features.setter
    def supported_features(self, supported_features):
        """Sets the supported_features of this TrafficInfluData.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supported_features: The supported_features of this TrafficInfluData.
        :type supported_features: str
        """
        if supported_features is not None and not re.search(r'^[A-Fa-f0-9]*$', supported_features):  # noqa: E501
            raise ValueError("Invalid value for `supported_features`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._supported_features = supported_features

    @property
    def res_uri(self):
        """Gets the res_uri of this TrafficInfluData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :return: The res_uri of this TrafficInfluData.
        :rtype: str
        """
        return self._res_uri

    @res_uri.setter
    def res_uri(self, res_uri):
        """Sets the res_uri of this TrafficInfluData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :param res_uri: The res_uri of this TrafficInfluData.
        :type res_uri: str
        """

        self._res_uri = res_uri

    @property
    def reset_ids(self):
        """Gets the reset_ids of this TrafficInfluData.


        :return: The reset_ids of this TrafficInfluData.
        :rtype: List[str]
        """
        return self._reset_ids

    @reset_ids.setter
    def reset_ids(self, reset_ids):
        """Sets the reset_ids of this TrafficInfluData.


        :param reset_ids: The reset_ids of this TrafficInfluData.
        :type reset_ids: List[str]
        """
        if reset_ids is not None and len(reset_ids) < 1:
            raise ValueError("Invalid value for `reset_ids`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._reset_ids = reset_ids
